/* ============================================================
   ORÁCULO MÍSTICO · ARCANA CONTENT · ENGLISH
   Phase 13A. Same keys as every other language: M00-M21 and
   B/C/E/O 01-14. yesNo holds a code, never a label.
   ============================================================ */

export const CONTENIDO = {
  M00: {
    keywords: ['Beginning', 'Freedom', 'Trust'],
    energy: 'The urge to begin something before you have it all worked out.',
    advice: 'Take the first step even with an incomplete map; you will draw the rest as you go.',
    light: ['Openness to the new', 'Spontaneity', 'Freedom from prejudice'],
    shadow: ['Improvising without measure', 'Avoiding commitment', 'Scattered focus'],
    upright: 'The Fool marks the point where a story has not begun to be written. It speaks of availability: the ability to look at something without the weight of what you already know. In a reading it often points to a beginning that asks for trust rather than planning.',
    reversed: 'Reversed, the impulse jams. It may show fear of letting go of the familiar, or the opposite: leaping without hearing a single warning. Worth telling which of the two is happening before you move.',
    love: 'May point to a bond in its lightest phase, where nothing is settled yet. It invites you to speak about expectations rather than assume them.',
    work: 'A good moment to explore, learn something different or test an idea on a small scale. If a project is under way, check what you have taken for granted without confirming.',
    growth: 'Ask yourself what you would do if getting it wrong did not worry you. The answer usually points at what you have been putting off.',
    yesNo: 'likely_yes',
    astrology: 'Symbolically linked to Uranus and to air not yet given form.'
  },
  M01: {
    keywords: ['Initiative', 'Skill', 'Manifestation'],
    energy: 'The push that turns an intention into action.',
    advice: 'Use what you already have before going out to look for more.',
    light: ['Clear purpose', 'Talent applied', 'Effective communication'],
    shadow: ['Promising more than you can hold', 'Using skill to manipulate', 'Starting without finishing'],
    upright: 'The Magician gathers everything needed on the table and puts it to work. It speaks of practical capacity: knowing what you have and what it is for. In a spread it usually marks a moment when will and means line up.',
    reversed: 'Reversed it can show potential that never takes shape, or skill spent on persuading rather than building. It also appears when focus is missing: too many tools and none chosen.',
    love: 'May speak of attraction born from conversation and genuine interest. It invites you to say what you want instead of hinting at it.',
    work: 'Favours pitching an idea, starting a project or picking something up again with method. In study, it suggests the material you need is probably already within reach.',
    growth: 'Look at which of your skills you have not used for a while. Recovering it is often worth more than learning a new one.',
    yesNo: 'yes',
    astrology: 'Symbolically related to Mercury.'
  },
  M02: {
    keywords: ['Intuition', 'Silence', 'Mystery'],
    energy: 'Knowing something before you can explain it.',
    advice: 'Before deciding, give the question one night of silence.',
    light: ['Inner listening', 'Discretion', 'Patience with the unseen'],
    shadow: ['Keeping what ought to be said', 'Mistaking fear for intuition', 'Withdrawal'],
    upright: 'The High Priestess guards what is not ready to be shown. She speaks of a knowing that arrives by routes other than reasoning, and of the sense in not forcing answers. In a reading she often means information is still missing, and that it will come on its own.',
    reversed: 'Reversed she can point to being cut off from your own inner voice, or to secrets that now weigh more than they protect. Sometimes it simply means it is time to speak.',
    love: 'May point to a bond with more depth than words. It invites you to ask rather than interpret what the other leaves unsaid.',
    work: 'A time to observe before stepping in. In study it favours slow reading over hurried revision.',
    growth: 'Tell apart intuition, which arrives calm, from fear, which arrives in a hurry.',
    yesNo: 'depends',
    astrology: 'Symbolically linked to the Moon.'
  },
  M03: {
    keywords: ['Abundance', 'Care', 'Creation'],
    energy: 'What you planted begins to take a shape of its own.',
    advice: 'Tend what is already growing before you plant something else.',
    light: ['Generosity', 'Creative fertility', 'A welcoming setting'],
    shadow: ['Caring for everyone but yourself', 'Overprotection', 'Comfort that stalls'],
    upright: 'The Empress speaks of the moment when something no longer needs effort but attention. She stands for what nourishes: projects, bonds, bodies. In a spread she often marks a fertile stage, more about holding than starting.',
    reversed: 'Reversed she can show blocked creativity, giving that is not returned, or care that has hardened into control. She also appears when someone forgets themselves while tending others.',
    love: 'May speak of a warm, sustained bond. It invites you to check whether the care runs both ways.',
    work: 'Favours creative projects and teamwork. In study, a good time to produce rather than only gather notes.',
    growth: 'Ask how much of your energy goes to you. If the answer stings, that is the work.',
    yesNo: 'yes',
    astrology: 'Symbolically related to Venus.'
  },
  M04: {
    keywords: ['Structure', 'Authority', 'Protection'],
    energy: 'The stability that comes from setting a clear boundary.',
    advice: 'Decide what the rule is before the situation decides for you.',
    light: ['Order that sustains', 'Responsibility taken on', 'Reliable presence'],
    shadow: ['Rigidity', 'Control disguised as care', 'Fear of the unplanned'],
    upright: 'The Emperor speaks of the frame that holds a thing up: schedules, limits, agreements. In a reading it usually points to a matter that will improve less through inspiration than through structure. It is the card of what stays standing because someone built it that way.',
    reversed: 'Reversed it can show authority turned into stiffness, or the opposite: a life without any frame at all, where every decision starts from zero. It also appears when a rule is being obeyed that nobody has checked in years.',
    love: 'May point to a bond that needs clear agreements more than grand declarations. It invites you to name what each of you expects.',
    work: 'Favours planning, defining roles and putting limits on what you accept. If something feels chaotic, the fix is probably structural rather than motivational.',
    growth: 'Look at which of your rules you inherited and never examined. Some still serve you; others only weigh.',
    yesNo: 'yes',
    astrology: 'Symbolically linked to Aries.'
  },
  M05: {
    keywords: ['Tradition', 'Teaching', 'Belonging'],
    energy: 'Knowledge that comes from those who walked ahead.',
    advice: 'Before inventing the path, ask whether someone has already mapped it.',
    light: ['Shared learning', 'Sense of belonging', 'Guidance with foundation'],
    shadow: ['Repeating without questioning', 'Dogma', 'Fear of stepping outside the group'],
    upright: 'The Hierophant speaks of what is handed down: a craft, a faith, a way of doing things. In a spread it often marks a moment for learning from an established source, or for recognising the value of what a community already knows.',
    reversed: 'Reversed it can mark the point where the inherited stops fitting. It may show rebellion for its own sake, or a tradition kept out of inertia rather than conviction.',
    love: 'May speak of a bond that moves toward the formal or the shared. It invites you to look at which family model you are repeating without noticing.',
    work: 'Favours training, mentoring and working within an established framework. If you feel stuck, an experienced voice will probably help more than another attempt alone.',
    growth: 'Ask which belief of yours you have never put to the test. Examining it does not mean losing it.',
    yesNo: 'neutral',
    astrology: 'Symbolically linked to Taurus.'
  },
  M06: {
    keywords: ['Choice', 'Union', 'Values'],
    energy: 'The moment when two paths cannot both be walked.',
    advice: 'Choose from what you value, not from what you fear losing.',
    light: ['Genuine connection', 'Decision made in alignment', 'Honesty about desire'],
    shadow: ['Endless indecision', 'Choosing to please others', 'Idealising the option not taken'],
    upright: 'The Lovers is less about romance than about choosing. It speaks of the point where you must say yes to one thing and, in doing so, no to another. In a reading it usually asks what you actually value, once appearances are set aside.',
    reversed: 'Reversed it can show a decision postponed until circumstances make it for you, or a union entered without honesty about what each side wants. It also appears when values and actions have drifted apart.',
    love: 'May point to a bond at a defining moment, where something has to be named out loud. It invites you to say what you want without softening it into a hint.',
    work: 'Often marks a choice between two directions, or a partnership that needs its terms made explicit. Worth writing down what each option really costs.',
    growth: 'Look at where you say yes with your mouth and no with your body. That gap is the message.',
    yesNo: 'depends',
    astrology: 'Symbolically linked to Gemini.'
  },
  M07: {
    keywords: ['Direction', 'Will', 'Advance'],
    energy: 'Forward motion held together by an act of will.',
    advice: 'Pull the reins in one direction; two at once cancel each other out.',
    light: ['Determination', 'Self-command', 'Momentum sustained'],
    shadow: ['Forcing the pace', 'Advancing without looking sideways', 'Winning at any cost'],
    upright: 'The Chariot speaks of movement that does not happen on its own: someone is steering. In a spread it usually marks a stage where effort pays off, as long as the direction stays single. It is the card of holding opposing forces together long enough to arrive.',
    reversed: 'Reversed it can show energy scattered across too many fronts, or a push that has become pressure. It also appears when you are moving fast in a direction nobody has re-examined.',
    love: 'May speak of a bond that needs a shared direction more than more intensity. It invites you to check whether you both want the same thing.',
    work: 'Favours pushing a project through and defending it. If progress has stalled, the cause is usually divided attention rather than lack of ability.',
    growth: 'Ask what you are steering out of conviction and what out of momentum. They are not the same fuel.',
    yesNo: 'yes',
    astrology: 'Symbolically linked to Cancer.'
  },
  M08: {
    keywords: ['Strength', 'Patience', 'Restraint'],
    energy: 'The quiet force that persuades instead of imposing.',
    advice: 'Meet what frightens you gently; force would only harden it.',
    light: ['Serene courage', 'Compassion toward oneself', 'Self-mastery'],
    shadow: ['Swallowing what needs saying', 'Confusing patience with resignation', 'Denying anger'],
    upright: 'Strength speaks of a power that does not need to raise its voice. In a reading it usually points to a situation that will yield to steadiness rather than pressure. It is the card of taming what is wild by staying with it, not by defeating it.',
    reversed: 'Reversed it can show patience worn thin, or its counterfeit: enduring what should have been named long ago. It also appears when the effort of holding everything together starts to cost more than it saves.',
    love: 'May point to a bond that grows through tenderness and time. It invites you to look at what you tolerate and call acceptance.',
    work: 'Favours sustained effort and difficult conversations handled calmly. If something resists, insisting harder will probably not help.',
    growth: 'Look at which part of you you treat as an enemy. It usually only wants to be heard.',
    yesNo: 'likely_yes',
    astrology: 'Symbolically linked to Leo.'
  },
  M09: {
    keywords: ['Search', 'Solitude', 'Discernment'],
    energy: 'Withdrawing in order to see clearly.',
    advice: 'Give yourself the silence you need before asking anyone else.',
    light: ['Honest introspection', 'Wisdom earned', 'Chosen solitude'],
    shadow: ['Isolation as escape', 'Overthinking without deciding', 'Refusing help'],
    upright: 'The Hermit speaks of the step back that lets you see the whole. In a spread it often marks a time for looking inward rather than outward, and for trusting a slower kind of answer. It is the card of the light you carry rather than the one you are given.',
    reversed: 'Reversed it can show solitude that stopped being useful and became a hiding place. It also appears when the search never ends because deciding feels riskier than looking.',
    love: 'May speak of a need for space that is not rejection. It invites you to say you need time instead of simply taking it.',
    work: 'Favours study, review and independent work. Good time to examine a process nobody has questioned in a while.',
    growth: 'Ask what you would understand if you stopped filling every silence.',
    yesNo: 'depends',
    astrology: 'Symbolically linked to Virgo.'
  },
  M10: {
    keywords: ['Cycle', 'Turn', 'Timing'],
    energy: 'Something moves on its own and asks to be read rather than pushed.',
    advice: 'Notice which part of this depends on you and which simply turns.',
    light: ['Favourable timing', 'Change that unblocks', 'Perspective on the cycle'],
    shadow: ['Waiting for luck to do the work', 'Resisting the turn', 'Blaming circumstance'],
    upright: 'The Wheel of Fortune speaks of the movement that does not ask permission. In a reading it usually points to a shift already under way, where the useful question is how you position yourself rather than how you stop it.',
    reversed: 'Reversed it can show clinging to a phase that has ended, or the sense of going round without advancing. It also appears when everything is left to chance and nothing to choice.',
    love: 'May point to a bond entering a different phase. It invites you to look at what has changed rather than what you remember.',
    work: 'Favours adapting to a shift rather than fighting it. If a cycle is closing, the useful move is preparing the next one.',
    growth: 'Look at which pattern in your life has come round again. Recognising it is half the way out.',
    yesNo: 'likely_yes',
    astrology: 'Symbolically linked to Jupiter.'
  },
  M11: {
    keywords: ['Balance', 'Truth', 'Consequence'],
    energy: 'What was set in motion returns with its full weight.',
    advice: 'Look at the facts before looking for who is to blame.',
    light: ['Honesty with oneself', 'Fair decision', 'Responsibility assumed'],
    shadow: ['Rigid judgement', 'Blaming to avoid looking', 'Weighing without deciding'],
    upright: 'Justice speaks of cause and effect without drama. In a spread it usually points to a matter that will resolve according to what is actually true, not what would be convenient. It is the card of accounts that balance.',
    reversed: 'Reversed it can show a decision made on partial information, or an imbalance that has been tolerated so long it looks normal. It also appears when honesty is demanded of others and not of oneself.',
    love: 'May speak of a bond that needs its terms made even. It invites you to look at what each side gives and what each receives.',
    work: 'Favours contracts, reviews and clear agreements. Good moment to check what you signed up to and whether it still holds.',
    growth: 'Ask what you already know and have chosen not to look at directly.',
    yesNo: 'depends',
    astrology: 'Symbolically linked to Libra.'
  },
  M12: {
    keywords: ['Pause', 'Perspective', 'Surrender'],
    energy: 'A stop that is not defeat but a change of angle.',
    advice: 'Stop pushing and look at the same thing from the other side.',
    light: ['Useful pause', 'Letting go of control', 'New point of view'],
    shadow: ['Waiting as an excuse', 'Sacrifice nobody asked for', 'Getting used to being stuck'],
    upright: 'The Hanged Man speaks of the moment when advancing is no longer the answer. In a reading it usually marks a suspension that lets something be understood differently. It is the card of what is gained by letting go rather than gripping.',
    reversed: 'Reversed it can show a pause that has stretched into paralysis, or a sacrifice made without anyone having asked for it. It also appears when waiting is more comfortable than deciding.',
    love: 'May point to a bond in a suspended phase. It invites you to look at whether you are waiting for something real or for something you have imagined.',
    work: 'Favours reviewing an approach rather than working harder at it. If a project is stuck, the block is probably in the premise.',
    growth: 'Ask what you would see if you stopped defending your version of this.',
    yesNo: 'depends',
    astrology: 'Symbolically linked to Neptune.'
  },
  M13: {
    keywords: ['Ending', 'Transformation', 'Threshold'],
    energy: 'Something reaches its end so that something else has room.',
    advice: 'Let go of what has already finished; carrying it does not preserve it.',
    light: ['Necessary closure', 'Deep renewal', 'Release from what weighed'],
    shadow: ['Clinging to what has passed', 'Fearing every change', 'Ending abruptly to avoid the grief'],
    upright: 'Death rarely speaks of a literal end. It marks a threshold: a stage that closes and cannot be reopened. In a spread it usually points to a transformation already begun, where resistance costs more than acceptance.',
    reversed: 'Reversed it can show a change refused, kept in place at high cost. It also appears when an ending is forced quickly to skip over what it hurts to feel.',
    love: 'May speak of a bond that is no longer what it was. It invites you to look at what is actually there rather than what it used to be.',
    work: 'Favours closing a cycle, leaving what is finished, or transforming a way of working. What ends here makes room for the next thing.',
    growth: 'Look at what part of your identity you defend because you fear the empty space.',
    yesNo: 'no',
    astrology: 'Symbolically linked to Scorpio.'
  },
  M14: {
    keywords: ['Measure', 'Blend', 'Middle way'],
    energy: 'The patience of combining two things until they work together.',
    advice: 'Look for the proportion, not the extreme.',
    light: ['Balance found', 'Patient adjustment', 'Serenity in the process'],
    shadow: ['Endless lukewarmness', 'Avoiding conflict by diluting it', 'Adjusting without ever committing'],
    upright: 'Temperance speaks of what is achieved by mixing well rather than choosing hard. In a reading it usually points to a matter that will resolve through gradual adjustment. It is the card of the right dose.',
    reversed: 'Reversed it can show imbalance held in place, or a moderation that is really avoidance. It also appears when the middle is chosen to keep the peace rather than because it is right.',
    love: 'May point to a bond that needs rhythm more than intensity. It invites you to look at what each of you can genuinely sustain.',
    work: 'Favours negotiation, gradual process and sustainable pace. If something burns you out, the problem is likely the dose rather than the direction.',
    growth: 'Ask where you swing between all and nothing, and what the middle would look like.',
    yesNo: 'likely_yes',
    astrology: 'Symbolically linked to Sagittarius.'
  },
  M15: {
    keywords: ['Attachment', 'Desire', 'Chain'],
    energy: 'What holds you and calls itself necessity.',
    advice: 'Look at the chain closely: often it is not locked.',
    light: ['Seeing the bond clearly', 'Owning your desire', 'Humour about your own shadow'],
    shadow: ['Dependence', 'Justifying what harms you', 'Confusing intensity with love'],
    upright: 'The Devil speaks of what binds without being imposed. In a spread it usually points to a habit, a bond or a belief that is sustained because letting it go looks harder than keeping it. It is the card of the chain you can see once you decide to look.',
    reversed: 'Reversed it often marks the beginning of release: the moment you name what was holding you. It can also show an attachment defended more fiercely the closer it comes to being seen.',
    love: 'May point to a bond where desire and dependence are tangled. It invites you to separate what you want from what you fear losing.',
    work: 'Watch for situations tolerated for security. Worth checking what the arrangement actually costs you.',
    growth: 'Look at what you call impossible to change. That sentence is usually part of the chain.',
    yesNo: 'no',
    astrology: 'Symbolically linked to Capricorn.'
  },
  M16: {
    keywords: ['Rupture', 'Revelation', 'Collapse'],
    energy: 'What was built on a false premise gives way at once.',
    advice: 'Do not rebuild the same thing on the same ground.',
    light: ['Truth that frees', 'Liberation from a false structure', 'Clarity after the shock'],
    shadow: ['Fear of everything falling', 'Rebuilding the same error', 'Destroying to avoid repairing'],
    upright: 'The Tower speaks of the sudden collapse of something that was not holding. In a reading it usually points to a revelation that arrives without warning and changes the picture. It is uncomfortable, but it tends to remove more weight than it adds.',
    reversed: 'Reversed it can show a collapse being postponed at growing cost, or a crisis passed through without learning what it came to show.',
    love: 'May point to a truth that changes how the bond is seen. It invites you to look at what was being held up by silence.',
    work: 'A moment for reviewing foundations rather than details. If something breaks, worth asking what it was really resting on.',
    growth: 'Ask which of your certainties would not survive an honest question.',
    yesNo: 'no',
    astrology: 'Symbolically linked to Mars.'
  },
  M17: {
    keywords: ['Hope', 'Calm', 'Guidance'],
    energy: 'The quiet that returns after the storm has passed.',
    advice: 'Trust the small light; it does not need to illuminate everything.',
    light: ['Renewed faith', 'Serenity', 'Clear direction'],
    shadow: ['Waiting without acting', 'Idealising the outcome', 'Hope used to avoid the present'],
    upright: 'The Star speaks of what is restored slowly after a hard passage. In a spread it usually marks a period of calm and orientation, where the way forward is not yet obvious but no longer frightening.',
    reversed: 'Reversed it can show discouragement, or hope placed somewhere that cannot hold it. It also appears when waiting replaces the small step that would actually help.',
    love: 'May point to a bond that heals with time and honesty. It invites you to look at what has already improved, not only at what is missing.',
    work: 'Favours long-term projects and patient recovery. Good time to set a direction without demanding immediate results.',
    growth: 'Look at what sustains you when nothing is going well. That is worth naming.',
    yesNo: 'yes',
    astrology: 'Symbolically linked to Aquarius.'
  },
  M18: {
    keywords: ['Uncertainty', 'Imagination', 'What is hidden'],
    energy: 'What is seen only partly and the mind completes on its own.',
    advice: 'Separate what you know from what you are assuming.',
    light: ['Access to the intuitive', 'Rich imagination', 'Recognising the unclear'],
    shadow: ['Anticipated fear', 'Self-deception', 'Deciding without seeing'],
    upright: 'The Moon speaks of the territory where the outline is not clean. In a reading it usually points to a situation with information missing, where imagination fills the gaps faster than the facts do. It asks for caution, not alarm.',
    reversed: 'Reversed it can mark the moment confusion begins to clear, or the opposite: illusion defended because looking directly would cost something.',
    love: 'May point to a bond where too much is left unsaid. It invites you to ask instead of interpreting.',
    work: 'Not the best moment for irreversible decisions. Better to gather what is missing before committing.',
    growth: 'Ask what fear of yours you have never checked against reality.',
    yesNo: 'likely_no',
    astrology: 'Symbolically linked to Pisces.'
  },
  M19: {
    keywords: ['Clarity', 'Vitality', 'Recognition'],
    energy: 'Everything is visible and there is nothing to hide.',
    advice: 'Let yourself be seen as you are; it costs less than the alternative.',
    light: ['Simple joy', 'Clarity without shadow', 'Confidence that is earned'],
    shadow: ['Blinding optimism', 'Needing to be admired', 'Ignoring what does not shine'],
    upright: 'The Sun speaks of what shows itself plainly. In a spread it usually marks a period of clarity, energy and things that work without needing to be forced. It is the card of the visible and the well-lit.',
    reversed: 'Reversed it can show light dimmed by tiredness or doubt, or a brightness kept up for others at private cost. It also appears when good news is not allowed to be enjoyed.',
    love: 'May point to a bond that is going well and does not need complicating. It invites you to enjoy what is present.',
    work: 'Favours visibility, recognition and projects that come to fruition. Good moment to show what you have done.',
    growth: 'Look at what you would do if you did not need anyone to approve of it.',
    yesNo: 'yes',
    astrology: 'Symbolically linked to the Sun.'
  },
  M20: {
    keywords: ['Reckoning', 'Call', 'Awakening'],
    energy: 'Something from the past returns asking to be resolved.',
    advice: 'Look back once, honestly, and then close it.',
    light: ['Lucid review', 'Forgiveness that frees', 'Answering a real call'],
    shadow: ['Judging yourself without mercy', 'Reopening what was already settled', 'Ignoring the obvious'],
    upright: 'Judgement speaks of the moment when the whole is seen at once. In a reading it usually points to a review that changes how a stage is understood, and to a decision that follows from it. It is the card of what wakes up when it is finally named.',
    reversed: 'Reversed it can show a review turned into self-punishment, or a call heard and set aside. It also appears when the past is revisited so often that nothing new is decided.',
    love: 'May point to something pending that needs to be spoken. It invites you to say it once and clearly.',
    work: 'Favours evaluating a stage and deciding what continues. Good moment for balance sheets rather than new starts.',
    growth: 'Ask what you would forgive yourself for if you looked at it without the verdict attached.',
    yesNo: 'likely_yes',
    astrology: 'Symbolically linked to Pluto.'
  },
  M21: {
    keywords: ['Completion', 'Integration', 'Whole'],
    energy: 'A cycle closes with everything in its place.',
    advice: 'Recognise what you finished before running toward the next thing.',
    light: ['Cycle completed', 'Sense of belonging', 'Integration of what was learnt'],
    shadow: ['Settling because it worked once', 'Fearing the next beginning', 'Closing without acknowledging'],
    upright: 'The World speaks of the point where the pieces fit. In a spread it usually marks a completion earned rather than granted, and the calm that comes with it. It is the card of what is whole enough to be let go.',
    reversed: 'Reversed it can show a closure almost reached and postponed, or an ending declared before it was real. It also appears when arriving is harder than travelling.',
    love: 'May point to a bond that has reached maturity. It invites you to look at how far it has come rather than what is still missing.',
    work: 'Favours delivering, closing and consolidating. Good moment to acknowledge the work before opening the next front.',
    growth: 'Look at what you finished and never allowed yourself to celebrate.',
    yesNo: 'yes',
    astrology: 'Symbolically linked to Saturn.'
  },
  B01: {
    keywords: ['Spark', 'Impulse', 'Initiative'],
    energy: 'The first flash of an idea that wants to become action.',
    advice: 'Do something small with it today, before enthusiasm cools.',
    light: ['Creative energy', 'Genuine enthusiasm', 'Clear beginning'],
    shadow: ['Impulse with no follow-through', 'Starting everything at once', 'Excitement that burns out'],
    upright: 'The Ace of Wands speaks of the moment an idea appears with heat behind it. In a reading it usually marks an opportunity to begin, where the energy is available and the shape is not yet fixed.',
    reversed: 'Reversed it can show an impulse that never landed, or the flatness that follows an idea nobody acted on. It also appears when energy is spread too thin to catch anywhere.',
    love: 'May point to attraction in its earliest, most unformed phase. It invites you to let it happen without immediately defining it.',
    work: 'Favours launching something, proposing an idea or reviving a project. Good moment for a first version rather than a perfect one.',
    growth: 'Ask what excites you that you have not made room for.',
    yesNo: 'yes',
    astrology: 'Fire in its purest form.'
  },
  B02: {
    keywords: ['Planning', 'Horizon', 'Decision'],
    energy: 'The pause between having the idea and choosing where to take it.',
    advice: 'Pick one direction; holding both keeps you where you are.',
    light: ['Vision of the future', 'Deliberate choice', 'Preparation before moving'],
    shadow: ['Planning to avoid acting', 'Fear of leaving the known', 'Comparing options endlessly'],
    upright: 'The Two of Wands speaks of standing with the map in hand. In a spread it usually points to a moment of choosing scope: whether to stay with what is safe or to reach for something larger.',
    reversed: 'Reversed it can show a plan that never leaves the page, or a decision handed to circumstance. It also appears when the horizon is looked at so long that the present goes unattended.',
    love: 'May point to a bond at a decision about where it is going. It invites you to say what you actually want from it.',
    work: 'Favours strategy, planning and evaluating a real expansion. Good moment to define the next stage.',
    growth: 'Look at what you would attempt if the outcome were not guaranteed either way.',
    yesNo: 'depends',
    astrology: 'Mars in Aries.'
  },
  B03: {
    keywords: ['Expansion', 'Waiting', 'Foresight'],
    energy: 'The first move is made and now the horizon is watched.',
    advice: 'Prepare what comes next while the current step is still travelling.',
    light: ['Long view', 'Patience with purpose', 'Growth under way'],
    shadow: ['Waiting passively', 'Losing interest before the result', 'Expecting more than was sown'],
    upright: 'The Three of Wands speaks of the moment after committing, when the outcome is not in yet. In a reading it usually points to a project already launched that needs perspective rather than more pushing.',
    reversed: 'Reversed it can show impatience with a process that simply takes time, or plans that grew larger than the means behind them.',
    love: 'May point to a bond that needs room to develop. It invites you to look further than the immediate.',
    work: 'Favours expansion, collaboration and thinking beyond the current scale. Good moment to prepare the next phase.',
    growth: 'Ask what you planted and have not given time to grow.',
    yesNo: 'likely_yes',
    astrology: 'Sun in Aries.'
  },
  B04: {
    keywords: ['Celebration', 'Home', 'Stability'],
    energy: 'A stage that is complete enough to be enjoyed.',
    advice: 'Stop and mark it; not everything has to lead somewhere else.',
    light: ['Shared joy', 'Sense of belonging', 'Solid foundation'],
    shadow: ['Celebrating what is not finished', 'Settling too early', 'Keeping up appearances'],
    upright: 'The Four of Wands speaks of the ground that holds steady. In a spread it usually marks a moment of stability, of belonging or of something worth acknowledging together.',
    reversed: 'Reversed it can show a stability that feels borrowed, or a celebration that hides what has not been dealt with.',
    love: 'May point to a bond entering a settled phase. It invites you to enjoy it without rushing to the next milestone.',
    work: 'Favours consolidating, closing a stage well and recognising a team. Good moment for gratitude rather than pressure.',
    growth: 'Look at where you feel at home, and what makes it so.',
    yesNo: 'yes',
    astrology: 'Venus in Aries.'
  },
  B05: {
    keywords: ['Friction', 'Competition', 'Noise'],
    energy: 'Several forces pulling at once without anyone leading.',
    advice: 'Slow the argument down and find out what is actually being disputed.',
    light: ['Healthy debate', 'Energy that sharpens', 'Differences brought into the open'],
    shadow: ['Conflict for its own sake', 'Exhausting friction', 'Confusing noise with progress'],
    upright: 'The Five of Wands speaks of clashing energies that have not yet organised themselves. In a reading it usually points to disagreement or competition that is more tiring than dangerous.',
    reversed: 'Reversed it can show conflict avoided until it goes underground, or a fight kept alive because ending it would mean conceding something.',
    love: 'May point to friction over small things that stands in for a larger one. It invites you to name the real subject.',
    work: 'Watch for teams pulling in different directions. Worth agreeing on the goal before arguing about the method.',
    growth: 'Ask what you defend loudest, and why it matters that much.',
    yesNo: 'likely_no',
    astrology: 'Saturn in Leo.'
  },
  B06: {
    keywords: ['Recognition', 'Success', 'Visibility'],
    energy: 'Effort that finally shows and is acknowledged.',
    advice: 'Accept the recognition without needing to explain it away.',
    light: ['Well-earned success', 'Confidence that is grounded', 'Leadership that carries others'],
    shadow: ['Needing applause', 'Success that isolates', 'Believing your own publicity'],
    upright: 'The Six of Wands speaks of the moment the work becomes visible. In a spread it usually marks recognition, a goal reached, or a position gained through what was actually done.',
    reversed: 'Reversed it can show recognition that does not arrive, or one that arrives and does not satisfy. It also appears when the image matters more than the substance.',
    love: 'May point to a bond that is going well and is seen that way. It invites you to share the good news rather than downplay it.',
    work: 'Favours presenting results, applying for something, or leading a stage. Good moment to be visible.',
    growth: 'Look at whether you can hold a compliment without deflecting it.',
    yesNo: 'yes',
    astrology: 'Jupiter in Leo.'
  },
  B07: {
    keywords: ['Defence', 'Position', 'Persistence'],
    energy: 'Holding ground when everything pushes the other way.',
    advice: 'Check the position is worth the effort before digging in further.',
    light: ['Courage under pressure', 'Conviction sustained', 'Advantageous ground'],
    shadow: ['Defending out of pride', 'Exhaustion from resisting', 'Seeing enemies everywhere'],
    upright: 'The Seven of Wands speaks of standing firm against pressure. In a reading it usually points to a position that must be defended, and to the energy that costs.',
    reversed: 'Reversed it can show a defence given up too soon, or one kept up long after the reason has gone.',
    love: 'May point to a bond that needs boundaries stated plainly. It invites you to say no without apologising for it.',
    work: 'Favours defending a criterion or a project under scrutiny. Worth choosing which battles are actually yours.',
    growth: 'Ask what you defend that nobody is attacking.',
    yesNo: 'depends',
    astrology: 'Mars in Leo.'
  },
  B08: {
    keywords: ['Speed', 'News', 'Movement'],
    energy: 'Everything accelerates at once and arrives together.',
    advice: 'Ride the pace, but decide where you are heading first.',
    light: ['Rapid progress', 'News that unblocks', 'Timely action'],
    shadow: ['Rushing without direction', 'Reacting instead of choosing', 'Missing detail in the hurry'],
    upright: 'The Eight of Wands speaks of things in flight. In a spread it usually marks a period of speed: messages, movement, matters resolving faster than expected.',
    reversed: 'Reversed it can show delays and messages that do not arrive, or speed applied in the wrong direction.',
    love: 'May point to a bond moving quickly. It invites you to check the pace suits both of you.',
    work: 'Favours communication, launches and anything time-sensitive. Good moment to send what has been sitting in drafts.',
    growth: 'Look at what you would do today if you stopped waiting for a better moment.',
    yesNo: 'yes',
    astrology: 'Mercury in Sagittarius.'
  },
  B09: {
    keywords: ['Resistance', 'Fatigue', 'Guard'],
    energy: 'Tired, still standing, and not sure whether to keep going.',
    advice: 'Rest before deciding; exhaustion is a poor adviser.',
    light: ['Resilience proven', 'Learning from experience', 'Guard that protects'],
    shadow: ['Distrusting everything', 'Carrying on out of stubbornness', 'Old wounds running the present'],
    upright: 'The Nine of Wands speaks of the last stretch, when the reserves are low. In a reading it usually points to something almost finished that is being sustained on willpower.',
    reversed: 'Reversed it can show a guard so high nothing gets in, or giving up just before the end.',
    love: 'May point to caution born of past experience. It invites you to check whether the guard still fits the present.',
    work: 'Good moment to finish rather than start. Worth asking what genuinely needs your effort now.',
    growth: 'Ask what you are protecting yourself from that has already passed.',
    yesNo: 'depends',
    astrology: 'Moon in Sagittarius.'
  },
  B10: {
    keywords: ['Overload', 'Burden', 'Excess'],
    energy: 'Carrying more than fits in two hands.',
    advice: 'Put something down; not everything on the list is yours.',
    light: ['Responsibility owned', 'Effort near completion', 'Awareness of the limit'],
    shadow: ['Taking on what is not yours', 'Not asking for help', 'Confusing worth with workload'],
    upright: 'The Ten of Wands speaks of the weight accumulated along the way. In a spread it usually points to overload: a commitment that grew larger than intended.',
    reversed: 'Reversed it can mark the moment of putting down what was not yours, or the opposite: carrying on until something breaks.',
    love: 'May point to a bond where one side carries most of the weight. It invites you to look at how the load is shared.',
    work: 'Watch for accumulated tasks and unnamed responsibilities. Worth delegating or cutting.',
    growth: 'Look at what you carry because you believe nobody else would.',
    yesNo: 'likely_no',
    astrology: 'Saturn in Sagittarius.'
  },
  B11: {
    keywords: ['Curiosity', 'Message', 'Enthusiasm'],
    energy: 'Someone who wants to try before knowing how.',
    advice: 'Follow the curiosity; it does not need to justify itself yet.',
    light: ['Fresh enthusiasm', 'Willingness to learn', 'Good news'],
    shadow: ['Restlessness with no follow-through', 'Impatience', 'Promising more than is known'],
    upright: 'The Page of Wands speaks of a beginning driven by interest rather than plan. In a reading it often marks news, an invitation, or the wish to explore something new.',
    reversed: 'Reversed it can show enthusiasm that fades quickly, or an idea talked about more than tried.',
    love: 'May point to something starting with lightness and curiosity. It invites you to enjoy it without labelling it.',
    work: 'Favours learning, trying and asking. Good moment to say you do not know something.',
    growth: 'Ask what you are curious about and have dismissed as pointless.',
    yesNo: 'likely_yes',
    astrology: 'Earth within fire.'
  },
  B12: {
    keywords: ['Action', 'Daring', 'Departure'],
    energy: 'The decision to go, taken more with the body than the head.',
    advice: 'Move, but know what you are leaving behind.',
    light: ['Courage to act', 'Adventure', 'Decisive momentum'],
    shadow: ['Leaving things half done', 'Reckless haste', 'Running rather than choosing'],
    upright: 'The Knight of Wands speaks of energy that will not sit still. In a spread it usually marks a departure, a change of scene, or an action taken with conviction and little caution.',
    reversed: 'Reversed it can show impulse that scatters, or a departure that is really an escape.',
    love: 'May point to intensity that arrives fast. It invites you to see whether it also stays.',
    work: 'Favours bold moves and changes of direction. Worth leaving your current work in a state someone else could pick up.',
    growth: 'Look at what you would do if you stopped asking permission.',
    yesNo: 'yes',
    astrology: 'Fire within fire.'
  },
  B13: {
    keywords: ['Magnetism', 'Confidence', 'Warmth'],
    energy: 'A presence that lights up what it comes near.',
    advice: 'Use your warmth to open doors, not to fill the room.',
    light: ['Natural charisma', 'Confidence that inspires', 'Generosity of spirit'],
    shadow: ['Needing to be the centre', 'Impatience with slower people', 'Warmth that consumes'],
    upright: 'The Queen of Wands speaks of self-assurance that does not need to be defended. In a reading it usually points to someone who leads through presence, or to a moment for showing up as yourself.',
    reversed: 'Reversed it can show confidence that has become display, or a light dimmed by comparison with others.',
    love: 'May point to a bond built on admiration and warmth. It invites you to be generous without disappearing into it.',
    work: 'Favours leading, motivating and representing something. Good moment to take a visible role.',
    growth: 'Ask where you shrink yourself so others are comfortable.',
    yesNo: 'yes',
    astrology: 'Water within fire.'
  },
  B14: {
    keywords: ['Vision', 'Leadership', 'Drive'],
    energy: 'Someone who sees where this goes and makes others want to go too.',
    advice: 'Say the direction out loud; people cannot follow what stays in your head.',
    light: ['Clear vision', 'Leadership that inspires', 'Bold decisions'],
    shadow: ['Imposing the vision', 'Impatience with detail', 'Confusing conviction with certainty'],
    upright: 'The King of Wands speaks of mature fire: energy that has learned direction. In a spread it usually marks the capacity to lead a project and carry others with it.',
    reversed: 'Reversed it can show authority that has become authoritarianism, or a vision nobody was invited into.',
    love: 'May point to a bond where one side sets the pace. It invites you to check the direction is shared.',
    work: 'Favours taking charge, deciding and defending a direction. Good moment for the difficult call.',
    growth: 'Look at what you would build if you trusted your own judgement.',
    yesNo: 'yes',
    astrology: 'Air within fire.'
  },
  C01: {
    keywords: ['Opening', 'Feeling', 'Offering'],
    energy: 'Something begins to be felt before it can be explained.',
    advice: 'Let yourself feel it without deciding yet what it means.',
    light: ['Emotional openness', 'New affection', 'Genuine receptivity'],
    shadow: ['Closing off in advance', 'Flooding without direction', 'Confusing intensity with depth'],
    upright: 'The Ace of Cups speaks of the moment the heart opens. In a reading it usually marks the start of something felt: a bond, a reconciliation, or the return of feeling after a numb stretch.',
    reversed: 'Reversed it can show emotion blocked, or offered where it cannot be received. It also appears when feeling is suppressed because it seems inconvenient.',
    love: 'May point to a beginning with real emotional weight. It invites you to receive as well as give.',
    work: 'Favours anything creative or relational. Good moment to work with people rather than around them.',
    growth: 'Ask what you feel and have not let yourself name.',
    yesNo: 'yes',
    astrology: 'Water in its purest form.'
  },
  C02: {
    keywords: ['Bond', 'Reciprocity', 'Encounter'],
    energy: 'Two people who choose each other at the same time.',
    advice: 'Look at whether what you give is also what you receive.',
    light: ['Mutual attraction', 'Balanced bond', 'Understanding'],
    shadow: ['Idealising the other', 'Merging without separateness', 'Giving to be chosen'],
    upright: 'The Two of Cups speaks of connection between equals. In a spread it usually marks an encounter, an agreement, or a bond where both sides show up.',
    reversed: 'Reversed it can show imbalance, or a bond sustained by one side alone. It also appears when closeness is confused with losing yourself.',
    love: 'May point to a bond of real reciprocity. It invites you to keep being yourself inside it.',
    work: 'Favours partnerships and collaborations. Good moment to agree terms with someone.',
    growth: 'Look at what you offer freely and what you offer expecting something back.',
    yesNo: 'yes',
    astrology: 'Venus in Cancer.'
  },
  C03: {
    keywords: ['Friendship', 'Celebration', 'Community'],
    energy: 'Joy that grows because it is shared.',
    advice: 'Tell someone; keeping the good news does not multiply it.',
    light: ['Warm company', 'Shared happiness', 'Genuine support'],
    shadow: ['Company that avoids intimacy', 'Celebrating to avoid feeling', 'Losing yourself in the group'],
    upright: 'The Three of Cups speaks of the pleasure of belonging. In a reading it usually marks friendship, celebration, or the relief of not being alone with something.',
    reversed: 'Reversed it can show a group that no longer nourishes, or a social life that fills time without filling anything else.',
    love: 'May point to a bond that begins in shared company. It invites you to keep the friendships around it alive.',
    work: 'Favours teamwork and collective recognition. Good moment to celebrate with the people involved.',
    growth: 'Ask who you can be entirely yourself with.',
    yesNo: 'yes',
    astrology: 'Mercury in Cancer.'
  },
  C04: {
    keywords: ['Apathy', 'Saturation', 'Offer unseen'],
    energy: 'Something is offered and there is no appetite for it.',
    advice: 'Look again at what is in front of you before dismissing it.',
    light: ['Honest reassessment', 'Recognising what does not satisfy', 'Necessary pause'],
    shadow: ['Boredom that closes everything', 'Ignoring what is available', 'Waiting for something better'],
    upright: 'The Four of Cups speaks of emotional saturation. In a spread it usually points to a stretch of flatness where nothing appeals, including things that objectively should.',
    reversed: 'Reversed it often marks the moment interest returns, or the decision to accept what was being ignored.',
    love: 'May point to a bond gone routine. It invites you to look at whether the problem is the bond or the tiredness.',
    work: 'Watch for opportunities dismissed without examination. Worth reviewing what you turned down.',
    growth: 'Look at what you already have and have stopped seeing.',
    yesNo: 'likely_no',
    astrology: 'Moon in Cancer.'
  },
  C05: {
    keywords: ['Loss', 'Grief', 'What remains'],
    energy: 'Looking at what spilled and not yet at what is still standing.',
    advice: 'Grieve properly, then turn round; something is still there.',
    light: ['Grief allowed', 'Honest acceptance', 'Seeing what survived'],
    shadow: ['Staying in the loss', 'Idealising what was lost', 'Refusing consolation'],
    upright: 'The Five of Cups speaks of the weight of what did not work out. In a reading it usually points to disappointment or grief that is occupying the whole field of view.',
    reversed: 'Reversed it often marks the beginning of recovery, or the moment attention shifts to what remains.',
    love: 'May point to a wound that is still open. It invites you to allow the sadness without letting it write the future.',
    work: 'Watch for discouragement after something failed. Worth naming what was learnt before moving on.',
    growth: 'Ask what you still have that you have stopped counting.',
    yesNo: 'no',
    astrology: 'Mars in Scorpio.'
  },
  C06: {
    keywords: ['Memory', 'Innocence', 'Past'],
    energy: 'Something from before returns with its warmth intact.',
    advice: 'Take the good from the memory without moving back into it.',
    light: ['Kind nostalgia', 'Reconnection', 'Recovered simplicity'],
    shadow: ['Living in the past', 'Idealising what was', 'Refusing the present'],
    upright: 'The Six of Cups speaks of what remains from earlier. In a spread it usually marks a return: a person, a place, or a way of feeling that belonged to another time.',
    reversed: 'Reversed it can show a past that will not let go, or a nostalgia that makes the present unlivable.',
    love: 'May point to a reappearance, or to a bond with deep shared history. It invites you to see the person now, not then.',
    work: 'Favours reconnecting with old contacts or reviving a shelved project.',
    growth: 'Look at what you enjoyed before you decided it was childish.',
    yesNo: 'likely_yes',
    astrology: 'Sun in Scorpio.'
  },
  C07: {
    keywords: ['Options', 'Fantasy', 'Confusion'],
    energy: 'Too many possibilities and none of them tested.',
    advice: 'Discard two before choosing one; the list itself is the problem.',
    light: ['Rich imagination', 'Breadth of vision', 'Creative possibility'],
    shadow: ['Choosing nothing', 'Confusing wish with plan', 'Being seduced by the unreal'],
    upright: 'The Seven of Cups speaks of the moment options multiply faster than they can be examined. In a reading it usually points to confusion born of abundance rather than scarcity.',
    reversed: 'Reversed it often marks clarity arriving, or the decision to test one option instead of imagining seven.',
    love: 'May point to idealisation. It invites you to look at the person rather than the version of them you built.',
    work: 'Not a good moment for irreversible choices. Better to make one option concrete and see what happens.',
    growth: 'Ask which of your plans exist only as conversations.',
    yesNo: 'depends',
    astrology: 'Venus in Scorpio.'
  },
  C08: {
    keywords: ['Departure', 'Search', 'Letting go'],
    energy: 'Leaving something that works, because it no longer means anything.',
    advice: 'Go, but say why; leaving without naming it repeats the pattern.',
    light: ['Honest departure', 'Search for meaning', 'Courage to leave'],
    shadow: ['Leaving before understanding', 'Wandering as habit', 'Abandoning without closing'],
    upright: 'The Eight of Cups speaks of the choice to walk away from something that is not wrong, only finished. In a spread it usually marks a departure driven by meaning rather than by conflict.',
    reversed: 'Reversed it can show staying out of guilt, or leaving over and over without ever arriving.',
    love: 'May point to a bond that has run its course emotionally. It invites you to say it rather than let it fade.',
    work: 'Watch for a role that no longer fits. Worth planning the exit rather than improvising it.',
    growth: 'Look at what you keep out of loyalty to who you used to be.',
    yesNo: 'likely_no',
    astrology: 'Saturn in Pisces.'
  },
  C09: {
    keywords: ['Satisfaction', 'Wish', 'Enjoyment'],
    energy: 'Something wanted arrives and can be enjoyed without guilt.',
    advice: 'Let yourself have it; you do not owe an explanation.',
    light: ['Contentment', 'Wish fulfilled', 'Well-being that is felt'],
    shadow: ['Comfort that stops growth', 'Pleasure that covers something', 'Wanting more of the same'],
    upright: 'The Nine of Cups speaks of satisfaction that has actually landed. In a reading it usually marks a good moment, a wish met, or simple contentment with where things are.',
    reversed: 'Reversed it can show having what you asked for and still feeling empty, or pleasure used to avoid something else.',
    love: 'May point to a bond that gives real comfort. It invites you to enjoy it without waiting for the catch.',
    work: 'Favours enjoying a result and consolidating it. Good moment to acknowledge what went well.',
    growth: 'Ask what you actually want, separate from what you should want.',
    yesNo: 'yes',
    astrology: 'Jupiter in Pisces.'
  },
  C10: {
    keywords: ['Harmony', 'Family', 'Fullness'],
    energy: 'Emotional wellbeing that includes other people.',
    advice: 'Take care of what is already working; it does not maintain itself.',
    light: ['Shared happiness', 'Bonds that hold', 'Emotional peace'],
    shadow: ['Idealising the picture', 'Keeping harmony by silence', 'Fearing to disturb it'],
    upright: 'The Ten of Cups speaks of fullness that is lived with others. In a spread it usually marks a stage of emotional stability where the important bonds are in good order.',
    reversed: 'Reversed it can show a harmony maintained on the surface, or the distance between the picture and the reality.',
    love: 'May point to a bond at a settled and generous stage. It invites you to keep saying the things that go without saying.',
    work: 'Favours environments where people work well together. Good moment to look after the atmosphere.',
    growth: 'Look at who you would call if something good happened right now.',
    yesNo: 'yes',
    astrology: 'Mars in Pisces.'
  },
  C11: {
    keywords: ['Sensitivity', 'Intuition', 'Message'],
    energy: 'Something felt arrives before it can be explained.',
    advice: 'Pay attention to the impression; you do not have to act on it yet.',
    light: ['Fine intuition', 'Emotional openness', 'Creativity that surfaces'],
    shadow: ['Excessive sensitivity', 'Taking everything personally', 'Feeling without acting'],
    upright: 'The Page of Cups speaks of the beginnings of feeling and intuition. In a reading it often marks a message, an invitation, or a hunch worth listening to.',
    reversed: 'Reversed it can show emotion that overwhelms, or intuition dismissed because it cannot be justified.',
    love: 'May point to something starting tenderly and without defences. It invites you to let it be gentle.',
    work: 'Favours creative work and listening to people. Good moment for the idea that arrives sideways.',
    growth: 'Ask what you sensed and talked yourself out of.',
    yesNo: 'likely_yes',
    astrology: 'Earth within water.'
  },
  C12: {
    keywords: ['Offer', 'Romance', 'Idealism'],
    energy: 'Someone approaches with a proposal that comes from the heart.',
    advice: 'Accept the gesture and check what is behind it, both at once.',
    light: ['Sincere offer', 'Romanticism', 'Following what you feel'],
    shadow: ['Promising more than can be sustained', 'Idealising', 'Feeling that avoids commitment'],
    upright: 'The Knight of Cups speaks of movement driven by feeling. In a spread it usually marks an offer, a declaration, or a step taken because it felt right.',
    reversed: 'Reversed it can show charm without substance, or feeling that evaporates once it has to become practical.',
    love: 'May point to someone approaching with genuine intent. It invites you to look at actions alongside words.',
    work: 'Favours pitching an idea you believe in. Worth grounding it in something concrete.',
    growth: 'Look at what you would offer if you were not afraid it would be refused.',
    yesNo: 'likely_yes',
    astrology: 'Fire within water.'
  },
  C13: {
    keywords: ['Empathy', 'Depth', 'Care'],
    energy: 'Someone who understands what is not being said.',
    advice: 'Care for others without dissolving into them.',
    light: ['Deep empathy', 'Emotional intelligence', 'Presence that comforts'],
    shadow: ['Absorbing what is not yours', 'Caring to be needed', 'Forgetting your own needs'],
    upright: 'The Queen of Cups speaks of emotional maturity: feeling deeply and staying steady. In a reading it usually points to someone who supports, or to a moment for listening more than solving.',
    reversed: 'Reversed it can show emotion that overflows onto others, or care given until nothing is left for yourself.',
    love: 'May point to a bond with real emotional depth. It invites you to keep your own centre inside it.',
    work: 'Favours mentoring, care work and mediating. Good moment to notice how people are, not just what they deliver.',
    growth: 'Ask how much of your energy goes to you. If the answer stings, that is the work.',
    yesNo: 'yes',
    astrology: 'Water within water.'
  },
  C14: {
    keywords: ['Serenity', 'Mastery', 'Balance'],
    energy: 'Feeling deeply and still choosing calmly.',
    advice: 'Feel it fully, then decide from the calm rather than the wave.',
    light: ['Emotional balance', 'Wisdom that comforts', 'Composure under pressure'],
    shadow: ['Calm that hides distance', 'Repressing to stay steady', 'Advising instead of feeling'],
    upright: 'The King of Cups speaks of mature water: emotion that has learned governance. In a spread it usually marks the capacity to handle a delicate matter without being swept along by it.',
    reversed: 'Reversed it can show serenity used as a wall, or feeling controlled so tightly it stops being felt at all.',
    love: 'May point to a bond where someone holds steady. It invites you to share what you feel, not only what you have resolved.',
    work: 'Favours handling conflict and difficult conversations. Good moment to be the calm voice.',
    growth: 'Look at what you feel and manage instead of live.',
    yesNo: 'yes',
    astrology: 'Air within water.'
  },
  E01: {
    keywords: ['Clarity', 'Truth', 'Decision'],
    energy: 'An idea cuts through and the picture becomes plain.',
    advice: 'Say it clearly; ambiguity costs more than the truth.',
    light: ['Mental clarity', 'Truth spoken', 'Decision taken cleanly'],
    shadow: ['Truth used to wound', 'Cold logic', 'Deciding without weighing'],
    upright: 'The Ace of Swords speaks of the moment understanding arrives. In a reading it usually marks clarity, a decision that becomes obvious, or a truth that changes the terms.',
    reversed: 'Reversed it can show confusion, or clarity used as a weapon. It also appears when the truth is known and kept quiet.',
    love: 'May point to a conversation that needs having. It invites you to be honest and kind at the same time.',
    work: 'Favours analysis, decisions and clear communication. Good moment to define the problem precisely.',
    growth: 'Ask what you know and pretend not to.',
    yesNo: 'yes',
    astrology: 'Air in its purest form.'
  },
  E02: {
    keywords: ['Impasse', 'Avoidance', 'Balance held'],
    energy: 'Not looking, so as not to have to choose.',
    advice: 'Take the blindfold off; the information is already there.',
    light: ['Necessary pause before deciding', 'Truce', 'Weighing carefully'],
    shadow: ['Refusing to see', 'Indecision that costs', 'Keeping the peace by silence'],
    upright: 'The Two of Swords speaks of a stalemate sustained on purpose. In a spread it usually points to a decision postponed because both options carry a cost.',
    reversed: 'Reversed it often marks the moment the blindfold comes off, or a stalemate breaking with more noise than needed.',
    love: 'May point to something being avoided by both sides. It invites you to name it first.',
    work: 'Watch for decisions delayed until they decide themselves. Worth setting a date.',
    growth: 'Look at what you would have to accept if you looked at this directly.',
    yesNo: 'depends',
    astrology: 'Moon in Libra.'
  },
  E03: {
    keywords: ['Wound', 'Sorrow', 'Truth that hurts'],
    energy: 'Something true is said and it hurts exactly as much as expected.',
    advice: 'Let the pain pass through; explaining it away only delays it.',
    light: ['Clarity after the pain', 'Grief named', 'Honesty even when it costs'],
    shadow: ['Rehearsing the wound', 'Blaming to avoid grieving', 'Closing the heart afterwards'],
    upright: 'The Three of Swords speaks of the sorrow that comes with knowing. In a reading it usually marks a disappointment or a truth that changes something, and the time it needs to be felt.',
    reversed: 'Reversed it often marks the start of healing, or the opposite: a wound kept open because letting it close would mean moving on.',
    love: 'May point to a hurt that has to be spoken. It invites you to say it once, fully, rather than in fragments.',
    work: 'Watch for a setback taken personally. Worth separating the outcome from your worth.',
    growth: 'Ask what you have not allowed yourself to grieve.',
    yesNo: 'no',
    astrology: 'Saturn in Libra.'
  },
  E04: {
    keywords: ['Rest', 'Recovery', 'Retreat'],
    energy: 'Stopping because carrying on would break something.',
    advice: 'Rest properly; half a pause repairs nothing.',
    light: ['Real recovery', 'Silence that restores', 'Recognising the limit'],
    shadow: ['Withdrawing indefinitely', 'Rest that becomes avoidance', 'Resting badly out of guilt'],
    upright: 'The Four of Swords speaks of necessary retreat. In a spread it usually points to a moment for recovery rather than effort, where doing less is what actually helps.',
    reversed: 'Reversed it can show exhaustion ignored, or a rest so prolonged that returning becomes hard.',
    love: 'May point to a bond that needs quiet more than conversation. It invites you to allow the pause without reading meaning into it.',
    work: 'Good moment to stop rather than push. Worth stepping back before deciding anything.',
    growth: 'Look at what you would understand if you were not tired.',
    yesNo: 'depends',
    astrology: 'Jupiter in Libra.'
  },
  E05: {
    keywords: ['Winning badly', 'Conflict', 'Cost'],
    energy: 'The argument is won and something else is lost.',
    advice: 'Ask what winning this actually buys you.',
    light: ['Recognising the real cost', 'Defending what matters', 'Ending a dispute honestly'],
    shadow: ['Winning at any price', 'Humiliating', 'Being right instead of being well'],
    upright: 'The Five of Swords speaks of victories that leave damage. In a reading it usually points to a conflict where the cost outweighs the prize.',
    reversed: 'Reversed it can mark the wish to repair, or a conflict that keeps restarting because nobody conceded anything.',
    love: 'May point to arguments where the aim is to win. It invites you to look at what you actually want from the conversation.',
    work: 'Watch for competition that damages the environment. Worth choosing what is worth arguing about.',
    growth: 'Ask when being right last made you feel better.',
    yesNo: 'no',
    astrology: 'Venus in Aquarius.'
  },
  E06: {
    keywords: ['Passage', 'Transition', 'Calmer waters'],
    energy: 'Leaving difficulty behind, still carrying some of it.',
    advice: 'Move on without pretending nothing happened.',
    light: ['Transition toward the better', 'Help accepted', 'Distance gained'],
    shadow: ['Fleeing without resolving', 'Carrying the whole past along', 'Moving without direction'],
    upright: 'The Six of Swords speaks of the crossing between one state and another. In a spread it usually marks a move away from something hard, gradual rather than sudden.',
    reversed: 'Reversed it can show a departure that cannot be made, or a change of place that changes nothing else.',
    love: 'May point to a bond leaving a rough patch. It invites you to name what you are taking with you.',
    work: 'Favours a change of role or environment. Good moment to close well before starting.',
    growth: 'Look at what you would leave behind if you could choose.',
    yesNo: 'likely_yes',
    astrology: 'Mercury in Aquarius.'
  },
  E07: {
    keywords: ['Strategy', 'Concealment', 'Cunning'],
    energy: 'Getting something done without saying it out loud.',
    advice: 'Check whether the discretion is strategy or evasion.',
    light: ['Useful strategy', 'Timely discretion', 'Choosing your battles'],
    shadow: ['Acting behind backs', 'Self-deception', 'Avoiding the direct route'],
    upright: 'The Seven of Swords speaks of the indirect approach. In a reading it usually points to a situation handled by manoeuvre rather than confrontation, for better or worse.',
    reversed: 'Reversed it can mark something coming to light, or the decision to be straight after a stretch of avoidance.',
    love: 'May point to something withheld. It invites you to look at what silence is protecting.',
    work: 'Watch for information not being shared. Worth asking directly instead of inferring.',
    growth: 'Ask what you tell yourself that you would not say aloud.',
    yesNo: 'likely_no',
    astrology: 'Moon in Aquarius.'
  },
  E08: {
    keywords: ['Restriction', 'Blockage', 'Belief'],
    energy: 'Feeling trapped by something that is partly a thought.',
    advice: 'List what actually stops you; some of it will not survive the list.',
    light: ['Seeing the real limit', 'Distinguishing fear from fact', 'First step out'],
    shadow: ['Believing there is no way out', 'Waiting to be rescued', 'Confusing difficult with impossible'],
    upright: 'The Eight of Swords speaks of confinement built as much from belief as from circumstance. In a spread it usually points to a blockage where the restriction is real but smaller than it feels.',
    reversed: 'Reversed it often marks the moment the way out becomes visible, or an escape attempted before the situation was understood.',
    love: 'May point to a bond that feels inescapable. It invites you to separate what binds you from what you fear.',
    work: 'Watch for a situation described as having no alternative. Worth testing that claim.',
    growth: 'Look at which of your limits you have never actually tried to cross.',
    yesNo: 'no',
    astrology: 'Jupiter in Gemini.'
  },
  E09: {
    keywords: ['Anxiety', 'Night', 'Anticipation'],
    energy: 'The mind rehearsing what has not happened.',
    advice: 'Write down the fear; on paper it is usually smaller.',
    light: ['Naming the fear', 'Asking for help', 'Distinguishing thought from fact'],
    shadow: ['Insomnia of the mind', 'Anticipating disaster', 'Suffering in advance'],
    upright: 'The Nine of Swords speaks of the worry that grows at night. In a reading it usually points to anxiety that has outgrown the situation causing it.',
    reversed: 'Reversed it can mark relief arriving, or the moment the fear is finally spoken to someone.',
    love: 'May point to worry that has not been shared. It invites you to say it rather than manage it alone.',
    work: 'Watch for pressure carried privately. Worth checking the deadline against the panic.',
    growth: 'Ask how many of last year fears actually happened.',
    yesNo: 'no',
    astrology: 'Mars in Gemini.'
  },
  E10: {
    keywords: ['End', 'Bottom', 'Release'],
    energy: 'The worst has happened and there is nothing left to fear about it.',
    advice: 'It is over; stop replaying how it went.',
    light: ['Definitive ending', 'Relief after the fall', 'Freedom to start again'],
    shadow: ['Dramatising the ending', 'Staying in the role of victim', 'Believing nothing can follow'],
    upright: 'The Ten of Swords speaks of the end of a cycle that could not continue. In a spread it usually marks a hard closure, and the paradoxical calm that comes once it has happened.',
    reversed: 'Reversed it often marks recovery beginning, or an ending refused long after it arrived.',
    love: 'May point to something finished. It invites you to accept it rather than negotiate with it.',
    work: 'Watch for a project or role that has run out. Worth closing it cleanly.',
    growth: 'Look at what you can build now that this is no longer standing.',
    yesNo: 'no',
    astrology: 'Sun in Gemini.'
  },
  E11: {
    keywords: ['Alertness', 'Curiosity', 'Watchfulness'],
    energy: 'Someone paying close attention to what others skip over.',
    advice: 'Ask the question; you do not have to already know the answer.',
    light: ['Sharp observation', 'Honest curiosity', 'Quick learning'],
    shadow: ['Suspicion of everything', 'Talking more than listening', 'Analysing to avoid feeling'],
    upright: 'The Page of Swords speaks of the mind at its most alert. In a reading it often marks news, a question worth asking, or the start of learning something demanding.',
    reversed: 'Reversed it can show scattered attention, or sharpness used to criticise rather than understand.',
    love: 'May point to a bond that begins in conversation. It invites you to listen as much as you observe.',
    work: 'Favours research, review and asking awkward questions. Good moment to check assumptions.',
    growth: 'Ask what you have decided without evidence.',
    yesNo: 'depends',
    astrology: 'Earth within air.'
  },
  E12: {
    keywords: ['Charge', 'Urgency', 'Directness'],
    energy: 'Going straight at it, at speed, without looking sideways.',
    advice: 'Slow down half a step; the direction is right, the pace may not be.',
    light: ['Decisive action', 'Directness', 'Courage to confront'],
    shadow: ['Acting without listening', 'Aggression', 'Deciding on incomplete information'],
    upright: 'The Knight of Swords speaks of the mind in full charge. In a spread it usually marks a rapid decision, a direct confrontation, or the wish to resolve something now.',
    reversed: 'Reversed it can show haste that damages, or a charge that loses momentum halfway.',
    love: 'May point to a conversation held too bluntly. It invites you to be honest without being blunt.',
    work: 'Favours cutting through delay. Worth checking the facts before the charge.',
    growth: 'Look at what you would say if you took a breath first.',
    yesNo: 'likely_yes',
    astrology: 'Fire within air.'
  },
  E13: {
    keywords: ['Lucidity', 'Independence', 'Honesty'],
    energy: 'Seeing clearly, including what is uncomfortable.',
    advice: 'Say the truth plainly; softening it too far erases it.',
    light: ['Clear judgement', 'Honest independence', 'Experience turned into clarity'],
    shadow: ['Coldness', 'Cutting truth', 'Isolating through self-sufficiency'],
    upright: 'The Queen of Swords speaks of clarity earned through experience. In a reading it usually points to someone who sees things as they are, or to a moment for honesty over comfort.',
    reversed: 'Reversed it can show clarity that has hardened into distance, or truth used to keep people at arm length.',
    love: 'May point to a bond that needs plain speech. It invites you to be clear and warm together.',
    work: 'Favours evaluating honestly and setting standards. Good moment for the direct assessment.',
    growth: 'Ask what you protect by staying self-sufficient.',
    yesNo: 'depends',
    astrology: 'Water within air.'
  },
  E14: {
    keywords: ['Judgement', 'Principle', 'Authority'],
    energy: 'Deciding by criteria rather than by mood.',
    advice: 'State the criterion before applying it.',
    light: ['Sound judgement', 'Ethical clarity', 'Authority that is earned'],
    shadow: ['Rigidity', 'Judging without context', 'Reason without warmth'],
    upright: 'The King of Swords speaks of mature air: thinking that has learned responsibility. In a spread it usually marks the capacity to decide fairly on a difficult matter.',
    reversed: 'Reversed it can show authority used to close conversation, or logic detached from consequence.',
    love: 'May point to a bond that needs clear terms. It invites you to make room for what cannot be argued.',
    work: 'Favours decisions, standards and difficult calls. Good moment to write down the rule.',
    growth: 'Look at where you use reason to avoid feeling.',
    yesNo: 'depends',
    astrology: 'Air within air.'
  },
  O01: {
    keywords: ['Opportunity', 'Seed', 'Ground'],
    energy: 'Something concrete is offered and it can be built on.',
    advice: 'Take it and give it a shape; potential alone does not grow.',
    light: ['Real opportunity', 'Solid foundation', 'Tangible beginning'],
    shadow: ['Letting it pass', 'Wanting certainty first', 'Confusing offer with result'],
    upright: 'The Ace of Pentacles speaks of a beginning with material ground under it. In a reading it usually marks an opportunity that is concrete: work, money, a place, a resource.',
    reversed: 'Reversed it can show a chance not taken, or a plan with no foundation beneath it.',
    love: 'May point to a bond that starts on solid ground. It invites you to value the everyday over the dramatic.',
    work: 'Favours a new role, a contract or an investment. Good moment to accept and then organise.',
    growth: 'Ask what you have available and have not used.',
    yesNo: 'yes',
    astrology: 'Earth in its purest form.'
  },
  O02: {
    keywords: ['Juggling', 'Adaptation', 'Priorities'],
    energy: 'Keeping several things in the air and just about managing.',
    advice: 'Decide what can fall; something has to.',
    light: ['Flexibility', 'Managing several fronts', 'Adapting well'],
    shadow: ['Taking on too much', 'Constant improvisation', 'Postponing the choice'],
    upright: 'The Two of Pentacles speaks of balance kept in motion. In a spread it usually points to a period of juggling commitments, workable but not sustainable indefinitely.',
    reversed: 'Reversed it can show the balance breaking, or juggling used to avoid deciding.',
    love: 'May point to a bond squeezed between other demands. It invites you to give it real time, not leftover time.',
    work: 'Watch for too many parallel tasks. Worth ordering by importance rather than urgency.',
    growth: 'Look at what you keep in the air only because dropping it feels like failure.',
    yesNo: 'depends',
    astrology: 'Jupiter in Capricorn.'
  },
  O03: {
    keywords: ['Craft', 'Collaboration', 'Skill'],
    energy: 'Doing something well, with others, and being recognised for it.',
    advice: 'Say what you need from the others; nobody guesses well.',
    light: ['Recognised competence', 'Effective teamwork', 'Learning by doing'],
    shadow: ['Working alone out of pride', 'Perfectionism that stalls', 'Not asking for what you are owed'],
    upright: 'The Three of Pentacles speaks of work that comes together because several people know their part. In a reading it usually marks a project going well and skill being acknowledged.',
    reversed: 'Reversed it can show unclear roles, or effort that goes unrecognised.',
    love: 'May point to a bond that is built rather than found. It invites you to look at what you both contribute.',
    work: 'Favours collaboration, apprenticeship and technical work. Good moment to ask for feedback.',
    growth: 'Ask what you do well and rarely say aloud.',
    yesNo: 'yes',
    astrology: 'Mars in Capricorn.'
  },
  O04: {
    keywords: ['Holding', 'Security', 'Control'],
    energy: 'Gripping tightly what you are afraid to lose.',
    advice: 'Open your hand a little; nothing circulates in a closed fist.',
    light: ['Prudence', 'Saving with purpose', 'Protecting what matters'],
    shadow: ['Hoarding out of fear', 'Rigidity', 'Confusing security with control'],
    upright: 'The Four of Pentacles speaks of holding on. In a spread it usually points to caution with resources, time or affection, useful up to the point where it stops movement.',
    reversed: 'Reversed it can mark the decision to let something circulate, or a grip so tight it costs more than it saves.',
    love: 'May point to a bond held rather than lived. It invites you to give without keeping score.',
    work: 'Watch for excessive caution. Worth distinguishing prudence from paralysis.',
    growth: 'Look at what you hold onto out of fear rather than value.',
    yesNo: 'likely_no',
    astrology: 'Sun in Capricorn.'
  },
  O05: {
    keywords: ['Lack', 'Exclusion', 'Help nearby'],
    energy: 'Going through a hard patch and not asking for help.',
    advice: 'Knock on the door; it is closer than it looks.',
    light: ['Recognising the need', 'Asking for support', 'Solidarity found'],
    shadow: ['Enduring alone', 'Shame about the situation', 'Not seeing the help available'],
    upright: 'The Five of Pentacles speaks of material or emotional difficulty gone through in isolation. In a reading it usually points to a hard stretch where support exists but has not been asked for.',
    reversed: 'Reversed it often marks recovery beginning, or help finally accepted.',
    love: 'May point to feeling alone inside a bond. It invites you to say so plainly.',
    work: 'Watch for insecurity about resources. Worth asking rather than assuming the answer.',
    growth: 'Ask who you would call if you allowed yourself to.',
    yesNo: 'no',
    astrology: 'Mercury in Taurus.'
  },
  O06: {
    keywords: ['Giving', 'Receiving', 'Fair exchange'],
    energy: 'Something passes from one hand to another and both are counted.',
    advice: 'Check who holds the scales in this exchange.',
    light: ['Generosity', 'Help that is real', 'Balanced exchange'],
    shadow: ['Giving to keep power', 'Receiving with debt attached', 'Charity that humiliates'],
    upright: 'The Six of Pentacles speaks of exchange and the balance inside it. In a spread it usually marks giving or receiving support, and the question of what each side gets from it.',
    reversed: 'Reversed it can show help with strings attached, or a dependency dressed as generosity.',
    love: 'May point to imbalance in what each side gives. It invites you to look honestly at the ledger.',
    work: 'Favours agreements, salaries and negotiations. Good moment to state what your work is worth.',
    growth: 'Look at whether you find it harder to give or to receive.',
    yesNo: 'likely_yes',
    astrology: 'Moon in Taurus.'
  },
  O07: {
    keywords: ['Patience', 'Assessment', 'Slow growth'],
    energy: 'Looking at what was planted and wondering if it is worth it.',
    advice: 'Decide whether to keep watering or plant elsewhere.',
    light: ['Honest evaluation', 'Patience with process', 'Investment that matures'],
    shadow: ['Impatience with what takes time', 'Persisting out of sunk cost', 'Abandoning just before it works'],
    upright: 'The Seven of Pentacles speaks of the pause to assess a long effort. In a reading it usually points to a project mid-way, where the useful question is whether the return justifies the time.',
    reversed: 'Reversed it can show effort poured into something that will not yield, or giving up too early.',
    love: 'May point to a bond that needs review rather than more effort. It invites you to be honest about progress.',
    work: 'Good moment to measure results and decide what continues. Worth setting a real criterion.',
    growth: 'Ask what you keep investing in out of habit.',
    yesNo: 'depends',
    astrology: 'Saturn in Taurus.'
  },
  O08: {
    keywords: ['Practice', 'Craft', 'Repetition'],
    energy: 'Doing the same thing again, a bit better each time.',
    advice: 'Keep at it; this is the stage that is meant to feel unremarkable.',
    light: ['Dedication', 'Skill improving', 'Rewarding routine'],
    shadow: ['Repeating without learning', 'Perfectionism', 'Working to avoid thinking'],
    upright: 'The Eight of Pentacles speaks of the patient acquisition of skill. In a spread it usually marks a period of steady work where progress is real but not yet visible.',
    reversed: 'Reversed it can show mechanical repetition, or work done without care.',
    love: 'May point to a bond that needs daily tending. It invites you to keep showing up in small ways.',
    work: 'Favours training, practice and detailed work. Good moment to improve the craft itself.',
    growth: 'Look at what you would master if you gave it a year.',
    yesNo: 'likely_yes',
    astrology: 'Sun in Virgo.'
  },
  O09: {
    keywords: ['Autonomy', 'Enjoyment', 'Achievement'],
    energy: 'Enjoying what you built by yourself.',
    advice: 'Enjoy it without apologising for having it.',
    light: ['Earned independence', 'Refined enjoyment', 'Self-sufficiency'],
    shadow: ['Isolating yourself in comfort', 'Pride that keeps others out', 'Achievement without company'],
    upright: 'The Nine of Pentacles speaks of the wellbeing that comes from your own effort. In a reading it usually marks autonomy, comfort, and the ability to enjoy what has been achieved.',
    reversed: 'Reversed it can show independence that has turned into isolation, or comfort that costs more than it gives.',
    love: 'May point to someone who is well alone and chooses company rather than needing it. It invites you to share without giving up your ground.',
    work: 'Favours working independently and enjoying results. Good moment to raise your standard.',
    growth: 'Ask what you have built that you never stopped to look at.',
    yesNo: 'yes',
    astrology: 'Venus in Virgo.'
  },
  O10: {
    keywords: ['Legacy', 'Stability', 'Inheritance'],
    energy: 'Something built that outlasts the person who built it.',
    advice: 'Look at what you are leaving, not only what you are earning.',
    light: ['Lasting security', 'Family and continuity', 'Wealth that is shared'],
    shadow: ['Wealth without meaning', 'Inherited weight', 'Keeping up a structure nobody wanted'],
    upright: 'The Ten of Pentacles speaks of material and family stability. In a spread it usually marks consolidation: something solid enough to be passed on.',
    reversed: 'Reversed it can show inherited burdens, or stability preserved at the cost of everyone inside it.',
    love: 'May point to a bond with long-term plans. It invites you to look at whether you both want the same structure.',
    work: 'Favours long-term projects, property and lasting decisions. Good moment to think in years.',
    growth: 'Look at what you inherited and never chose.',
    yesNo: 'yes',
    astrology: 'Mercury in Virgo.'
  },
  O11: {
    keywords: ['Study', 'Beginning', 'Application'],
    energy: 'Someone who starts learning something with real intent.',
    advice: 'Begin small and concrete; the plan can grow later.',
    light: ['Willingness to learn', 'Practical beginning', 'Steady focus'],
    shadow: ['Studying without applying', 'Postponing the start', 'Wanting results too early'],
    upright: 'The Page of Pentacles speaks of a beginning grounded in effort. In a reading it often marks study, a new job, or an opportunity that requires learning first.',
    reversed: 'Reversed it can show a project that never gets past the planning, or attention that drifts.',
    love: 'May point to a bond starting slowly and carefully. It invites you to let it build.',
    work: 'Favours training, internships and first steps. Good moment to learn the basics well.',
    growth: 'Ask what you would learn if you allowed yourself to be a beginner.',
    yesNo: 'likely_yes',
    astrology: 'Earth within earth.'
  },
  O12: {
    keywords: ['Constancy', 'Method', 'Reliability'],
    energy: 'Slow, steady, and it arrives.',
    advice: 'Trust the routine; this is the pace that finishes things.',
    light: ['Reliability', 'Sustained effort', 'Work well done'],
    shadow: ['Rigidity', 'Resistance to change', 'Routine without direction'],
    upright: 'The Knight of Pentacles speaks of unspectacular progress that does not stop. In a spread it usually marks patient, methodical work that will get there.',
    reversed: 'Reversed it can show stagnation dressed as consistency, or method applied without purpose.',
    love: 'May point to a bond built on reliability. It invites you to value the ordinary.',
    work: 'Favours long processes and anything requiring discipline. Good moment for the unglamorous task.',
    growth: 'Look at what you would achieve with the same effort applied for longer.',
    yesNo: 'likely_yes',
    astrology: 'Fire within earth.'
  },
  O13: {
    keywords: ['Care', 'Abundance', 'Groundedness'],
    energy: 'Someone who looks after what is in their care, including themselves.',
    advice: 'Look after the practical; it is what holds everything else up.',
    light: ['Practical generosity', 'Nurturing presence', 'Connection with the body'],
    shadow: ['Caring for everyone but yourself', 'Overprotecting', 'Measuring worth by usefulness'],
    upright: 'The Queen of Pentacles speaks of care made concrete. In a reading it usually points to someone who provides and sustains, or to a moment for tending the material side of life.',
    reversed: 'Reversed it can show care that exhausts, or attention to everyone except yourself.',
    love: 'May point to a bond where care shows in actions. It invites you to also receive.',
    work: 'Favours management, hospitality and anything that keeps a structure running. Good moment to look after the basics.',
    growth: 'Ask when you last did something for your own body.',
    yesNo: 'yes',
    astrology: 'Water within earth.'
  },
  O14: {
    keywords: ['Prosperity', 'Mastery', 'Provision'],
    energy: 'Someone who has built something solid and knows how to keep it.',
    advice: 'Administer what you have before pursuing more.',
    light: ['Material mastery', 'Reliable provision', 'Generosity from abundance'],
    shadow: ['Measuring worth by wealth', 'Rigidity in what has worked', 'Control disguised as provision'],
    upright: 'The King of Pentacles speaks of mature earth: effort that has become structure. In a spread it usually marks the ability to sustain something over time and provide for others through it.',
    reversed: 'Reversed it can show attachment to security, or a structure defended past its usefulness.',
    love: 'May point to a bond that offers real stability. It invites you to keep the warmth alongside the reliability.',
    work: 'Favours managing, investing and taking financial responsibility. Good moment for the long view.',
    growth: 'Look at what enough would actually mean for you.',
    yesNo: 'yes',
    astrology: 'Air within earth.'
  },
};
