/* ============================================================
   ORÁCULO MÍSTICO · CONTENU DES ARCANES · FRANÇAIS
   Phase 13A. Mêmes clés que dans les autres langues : M00-M21 et
   B/C/E/O 01-14. yesNo contient un code, jamais un libellé.
   ============================================================ */

export const CONTENIDO = {
  M00: {
    keywords: ['Commencement', 'Liberté', 'Confiance'],
    energy: "L'élan de commencer quelque chose sans tout avoir résolu.",
    advice: 'Fais le premier pas même si la carte est incomplète ; tu la dessineras en chemin.',
    light: ['Ouverture au neuf', 'Spontanéité', 'Absence de préjugé'],
    shadow: ['Improviser sans mesure', 'Fuir les engagements', 'Dispersion'],
    upright: "Le Mat marque le point où une histoire n'a pas encore commencé à s'écrire. Il parle de disponibilité : la capacité de regarder quelque chose sans le poids de ce que tu sais déjà. En lecture, il indique souvent un début qui demande plus de confiance que de planification.",
    reversed: "À l'envers, l'élan se bloque. Cela peut montrer la peur de lâcher le connu, ou l'inverse : se lancer sans écouter le moindre signal. Mieux vaut savoir laquelle des deux se joue avant de bouger.",
    love: "Peut indiquer un lien dans sa phase la plus légère, où rien n'est encore défini. Invite à parler des attentes plutôt qu'à les supposer.",
    work: "Bon moment pour explorer, apprendre autre chose ou tester une idée à petite échelle. Si un projet est en cours, vérifie ce que tu tiens pour acquis sans l'avoir confirmé.",
    growth: "Demande-toi ce que tu ferais si te tromper ne t'inquiétait pas. La réponse pointe souvent ce que tu remets à plus tard.",
    yesNo: 'likely_yes',
    astrology: "Symboliquement lié à Uranus et à l'air sans forme."
  },
  M01: {
    keywords: ['Initiative', 'Habileté', 'Manifestation'],
    energy: 'Un élan pour transformer une intention en action.',
    advice: "Sers-toi d'abord de ce que tu as déjà avant de chercher ailleurs.",
    light: ['Clarté du but', 'Talent appliqué', 'Communication efficace'],
    shadow: ['Promettre plus que ce qui tient', "Se servir de l'habileté pour manipuler", 'Commencer sans finir'],
    upright: "Le Bateleur rassemble sur la table tout le nécessaire et le met au travail. Il parle de capacité pratique : savoir ce que tu as et à quoi cela sert. Dans un tirage, il marque souvent un moment où la volonté et les moyens coïncident.",
    reversed: "À l'envers, il peut montrer un potentiel qui ne se concrétise pas, ou une adresse dépensée à convaincre plutôt qu'à construire. Il apparaît aussi quand le focus manque : trop d'outils et aucun choisi.",
    love: "Peut parler d'une attraction née de la conversation et d'un intérêt sincère. Invite à dire ce que tu veux au lieu de le suggérer.",
    work: "Favorise présenter une idée, lancer un projet ou reprendre quelque chose avec méthode. En études, indique que le matériel dont tu as besoin est sans doute déjà à portée.",
    growth: "Regarde quelle de tes compétences dort depuis longtemps. La reprendre vaut souvent mieux que d'en apprendre une neuve.",
    yesNo: 'yes',
    astrology: 'Symboliquement lié à Mercure.'
  },
  M02: {
    keywords: ['Intuition', 'Silence', 'Savoir intérieur'],
    energy: "Ce que l'on sait sans encore pouvoir l'expliquer.",
    advice: 'Écoute avant de répondre ; tout ne demande pas une réponse immédiate.',
    light: ['Intuition fine', 'Discrétion', 'Patience avec le processus'],
    shadow: ['Tout garder pour soi', 'Confondre distance et sagesse', 'Attendre sans agir'],
    upright: "La Papesse garde ce qu'il n'est pas encore temps de dire. En lecture, elle indique souvent un moment pour recueillir plutôt que pour décider, et la confiance en une perception qui n'a pas encore de mots.",
    reversed: "À l'envers, elle peut montrer une intuition négligée, ou un secret gardé au-delà de son utilité. Elle apparaît aussi quand le silence cesse de protéger et commence à isoler.",
    love: "Peut indiquer un lien où il se passe plus de choses sous la surface qu'on ne le dit. Invite à demander plutôt qu'à deviner.",
    work: 'Bon moment pour observer et se documenter avant de bouger. Cela vaut la peine d’écouter ce qui n’a pas été dit à voix haute.',
    growth: "Demande-toi ce que tu sais et ne t'es pas encore autorisé à reconnaître.",
    yesNo: 'depends',
    astrology: 'Symboliquement liée à la Lune.'
  },
  M03: {
    keywords: ['Abondance', 'Soin', 'Fertilité'],
    energy: "Ce qui pousse quand on lui donne du temps et de l'attention.",
    advice: "Prends soin de ce que tu as déjà semé avant de semer autre chose.",
    light: ['Générosité', 'Créativité qui porte ses fruits', 'Présence nourrissante'],
    shadow: ['Prendre soin de tous sauf de soi', 'Surprotection', 'Confort qui immobilise'],
    upright: "L'Impératrice parle de ce qui fleurit par un soin soutenu. Dans un tirage, elle marque souvent une étape fertile : des projets qui prennent, des liens qui se consolident, des corps qui demandent de l'attention.",
    reversed: "À l'envers, elle peut montrer un épuisement à force de donner sans mesure, ou une créativité bloquée par l'exigence. Elle apparaît aussi quand on confond prendre soin et contrôler.",
    love: "Peut indiquer un lien chaleureux et durable. Invite à recevoir autant que tu donnes.",
    work: 'Favorise le travail créatif et tout ce qui demande une constance douce. Bon moment pour faire grandir ce qui marche déjà.',
    growth: 'Regarde quelle part de ton énergie va vers toi. Si la réponse pique, c’est là qu’est le travail.',
    yesNo: 'yes',
    astrology: 'Symboliquement liée à Vénus.'
  },
  M04: {
    keywords: ['Structure', 'Autorité', 'Protection'],
    energy: "La stabilité qui vient d'une limite clairement posée.",
    advice: 'Décide quelle est la règle avant que la situation ne décide pour toi.',
    light: ['Ordre qui soutient', 'Responsabilité assumée', 'Présence fiable'],
    shadow: ['Rigidité', 'Contrôle déguisé en attention', "Peur de l'imprévu"],
    upright: "L'Empereur parle du cadre qui tient les choses : horaires, limites, accords. En lecture, il indique souvent une affaire qui s'améliorera moins par inspiration que par structure. C'est la carte de ce qui reste debout parce que quelqu'un l'a bâti ainsi.",
    reversed: "À l'envers, il peut montrer une autorité devenue raideur, ou l'inverse : une vie sans aucun cadre, où chaque décision repart de zéro. Il apparaît aussi quand on obéit à une règle que personne n'a revue depuis des années.",
    love: "Peut indiquer un lien qui a besoin d'accords clairs plus que de grandes déclarations. Invite à nommer ce que chacun attend.",
    work: 'Favorise planifier, définir les rôles et poser des limites à ce que tu acceptes. Si quelque chose paraît chaotique, la réponse est structurelle plutôt que motivationnelle.',
    growth: 'Regarde lesquelles de tes règles tu as héritées sans jamais les examiner. Certaines servent encore ; d’autres ne font que peser.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Bélier.'
  },
  M05: {
    keywords: ['Tradition', 'Enseignement', 'Appartenance'],
    energy: 'Un savoir qui vient de ceux qui ont marché avant.',
    advice: "Avant d'inventer le chemin, demande si quelqu'un l'a déjà tracé.",
    light: ['Apprentissage partagé', "Sentiment d'appartenance", 'Guidance fondée'],
    shadow: ['Répéter sans questionner', 'Dogme', 'Peur de sortir du groupe'],
    upright: "Le Pape parle de ce qui se transmet : un métier, une foi, une manière de faire. Dans un tirage, il marque souvent un moment pour apprendre d'une source établie, ou pour reconnaître la valeur de ce qu'une communauté sait déjà.",
    reversed: "À l'envers, il peut marquer le point où l'hérité cesse de convenir. Il peut montrer une révolte pour la révolte, ou une tradition maintenue par inertie plus que par conviction.",
    love: "Peut parler d'un lien qui va vers le formel ou le partagé. Invite à regarder quel modèle familial tu répètes sans le voir.",
    work: "Favorise se former, accompagner et travailler dans un cadre établi. Si tu te sens bloqué, une voix expérimentée aidera sans doute plus qu'un essai solitaire de plus.",
    growth: "Demande-toi quelle de tes croyances tu n'as jamais mise à l'épreuve. L'examiner ne veut pas dire la perdre.",
    yesNo: 'neutral',
    astrology: 'Symboliquement lié au Taureau.'
  },
  M06: {
    keywords: ['Choix', 'Union', 'Valeurs'],
    energy: 'Le moment où deux chemins ne peuvent pas être pris ensemble.',
    advice: 'Choisis depuis ce que tu values, pas depuis ce que tu crains de perdre.',
    light: ['Connexion sincère', 'Décision alignée', 'Honnêteté sur le désir'],
    shadow: ['Indécision sans fin', 'Choisir pour plaire', "Idéaliser l'option écartée"],
    upright: "L'Amoureux parle moins de romance que de choix. Il parle du point où il faut dire oui à une chose et, ce faisant, non à une autre. En lecture, il demande souvent ce que tu values vraiment, une fois les apparences mises de côté.",
    reversed: "À l'envers, il peut montrer une décision repoussée jusqu'à ce que les circonstances la prennent pour toi, ou une union nouée sans honnêteté sur ce que chacun veut. Il apparaît aussi quand valeurs et actes se sont éloignés.",
    love: "Peut indiquer un lien à un moment qui demande d'être nommé à voix haute. Invite à dire ce que tu veux sans l'adoucir jusqu'à le faire disparaître.",
    work: "Marque souvent un choix entre deux directions, ou une association qui a besoin de termes explicites. Cela vaut la peine d'écrire ce que chaque option coûte vraiment.",
    growth: 'Regarde où tu dis oui avec la bouche et non avec le corps. Cet écart est le message.',
    yesNo: 'depends',
    astrology: 'Symboliquement lié aux Gémeaux.'
  },
  M07: {
    keywords: ['Direction', 'Volonté', 'Avancée'],
    energy: 'Un mouvement en avant tenu par un acte de volonté.',
    advice: "Tire les rênes dans une seule direction ; deux à la fois s'annulent.",
    light: ['Détermination', 'Maîtrise de soi', 'Élan soutenu'],
    shadow: ['Forcer le rythme', 'Avancer sans regarder de côté', 'Gagner à tout prix'],
    upright: "Le Chariot parle d'un mouvement qui ne se fait pas tout seul : quelqu'un conduit. Dans un tirage, il marque souvent une étape où l'effort paie, tant que la direction reste unique. C'est la carte de tenir des forces opposées assez longtemps pour arriver.",
    reversed: "À l'envers, il peut montrer une énergie éparpillée sur trop de fronts, ou une poussée devenue pression. Il apparaît aussi quand tu vas vite dans une direction que personne n'a réexaminée.",
    love: "Peut parler d'un lien qui a besoin d'une direction commune plus que d'intensité. Invite à vérifier si vous voulez la même chose.",
    work: "Favorise pousser un projet et le défendre. Si l'avancée s'est arrêtée, la cause est plus souvent l'attention divisée que le manque de capacité.",
    growth: 'Demande-toi ce que tu conduis par conviction et ce que tu conduis par élan. Ce ne sont pas les mêmes carburants.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Cancer.'
  },
  M08: {
    keywords: ['Force', 'Patience', 'Retenue'],
    energy: "La force tranquille qui persuade au lieu d'imposer.",
    advice: 'Approche avec douceur ce qui te fait peur ; forcer ne ferait que le durcir.',
    light: ['Courage serein', 'Compassion envers soi', 'Maîtrise de soi'],
    shadow: ['Ravaler ce qui doit se dire', 'Confondre patience et résignation', 'Nier la colère'],
    upright: "La Force parle d'un pouvoir qui n'a pas besoin d'élever la voix. En lecture, elle indique souvent une situation qui cédera à la constance plutôt qu'à la pression. C'est la carte d'apprivoiser le sauvage en restant avec lui, non en le vainquant.",
    reversed: "À l'envers, elle peut montrer une patience à bout, ou sa contrefaçon : endurer ce qu'il aurait fallu nommer depuis longtemps. Elle apparaît aussi quand l'effort de tout tenir commence à coûter plus qu'il ne rapporte.",
    love: "Peut indiquer un lien qui grandit par la tendresse et le temps. Invite à regarder ce que tu tolères et appelles acceptation.",
    work: 'Favorise un effort soutenu et des conversations difficiles menées au calme. Si quelque chose résiste, insister plus fort n’aidera sans doute pas.',
    growth: 'Regarde quelle part de toi tu traites en ennemie. Elle veut souvent seulement être entendue.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée au Lion.'
  },
  M09: {
    keywords: ['Recherche', 'Solitude', 'Discernement'],
    energy: 'Se retirer pour y voir clair.',
    advice: "Offre-toi le silence dont tu as besoin avant de demander à quiconque.",
    light: ['Introspection honnête', 'Sagesse acquise', 'Solitude choisie'],
    shadow: ['Isolement comme fuite', 'Ruminer sans décider', "Refuser l'aide"],
    upright: "L'Ermite parle du pas en arrière qui permet de voir l'ensemble. Dans un tirage, il marque souvent un temps pour regarder au-dedans plutôt qu'au-dehors, et pour se fier à une réponse plus lente. C'est la carte de la lumière que tu portes, non de celle qu'on te donne.",
    reversed: "À l'envers, il peut montrer une solitude qui a cessé d'être utile et est devenue une cachette. Il apparaît aussi quand la recherche ne finit jamais parce que décider semble plus risqué que continuer à chercher.",
    love: "Peut parler d'un besoin d'espace qui n'est pas un rejet. Invite à dire que tu as besoin de temps plutôt qu'à le prendre sans rien dire.",
    work: "Favorise l'étude, la révision et le travail indépendant. Bon moment pour examiner un processus que personne n'a questionné depuis longtemps.",
    growth: "Demande-toi ce que tu comprendrais si tu cessais de remplir chaque silence.",
    yesNo: 'depends',
    astrology: 'Symboliquement lié à la Vierge.'
  },
  M10: {
    keywords: ['Cycle', 'Tour', 'Moment'],
    energy: "Quelque chose bouge tout seul et demande à être lu plutôt que poussé.",
    advice: 'Regarde quelle part dépend de toi et quelle part tourne simplement.',
    light: ['Moment favorable', 'Changement qui débloque', 'Perspective sur le cycle'],
    shadow: ['Attendre que la chance travaille', 'Résister au tour', 'Accuser les circonstances'],
    upright: "La Roue de Fortune parle du mouvement qui ne demande pas la permission. En lecture, elle indique souvent un changement déjà en cours, où la bonne question est comment tu t'y places, non comment tu l'arrêtes.",
    reversed: "À l'envers, elle peut montrer l'attachement à une phase terminée, ou l'impression de tourner sans avancer. Elle apparaît aussi quand tout est laissé au hasard et rien au choix.",
    love: "Peut indiquer un lien qui entre dans une autre phase. Invite à regarder ce qui a changé, pas ce dont tu te souviens.",
    work: "Favorise s'adapter à un changement plutôt que le combattre. Si un cycle se ferme, le geste utile est de préparer le suivant.",
    growth: 'Regarde quel schéma de ta vie est revenu. Le reconnaître fait la moitié du chemin.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée à Jupiter.'
  },
  M11: {
    keywords: ['Équilibre', 'Vérité', 'Conséquence'],
    energy: "Ce qui a été mis en route revient avec tout son poids.",
    advice: 'Regarde les faits avant de chercher un coupable.',
    light: ['Honnêteté envers soi', 'Décision juste', 'Responsabilité assumée'],
    shadow: ['Jugement rigide', 'Accuser pour ne pas regarder', 'Peser sans décider'],
    upright: "La Justice parle de cause et d'effet sans drame. Dans un tirage, elle indique souvent une affaire qui se réglera selon ce qui est vrai, non selon ce qui arrangerait. C'est la carte des comptes qui s'équilibrent.",
    reversed: "À l'envers, elle peut montrer une décision prise sur une information partielle, ou un déséquilibre toléré si longtemps qu'il paraît normal. Elle apparaît aussi quand on exige l'honnêteté des autres et pas de soi.",
    love: "Peut parler d'un lien qui a besoin d'égaliser ses termes. Invite à regarder ce que chacun donne et reçoit.",
    work: 'Favorise contrats, révisions et accords clairs. Bon moment pour vérifier ce que tu as signé et si cela tient encore.',
    growth: 'Demande-toi ce que tu sais déjà et as choisi de ne pas regarder en face.',
    yesNo: 'depends',
    astrology: 'Symboliquement liée à la Balance.'
  },
  M12: {
    keywords: ['Pause', 'Perspective', 'Lâcher-prise'],
    energy: "Un arrêt qui n'est pas une défaite mais un changement d'angle.",
    advice: "Cesse de pousser et regarde la même chose depuis l'autre côté.",
    light: ['Pause utile', 'Lâcher le contrôle', 'Point de vue neuf'],
    shadow: ['Attendre comme prétexte', "Sacrifice que personne n'a demandé", "S'habituer à être bloqué"],
    upright: "Le Pendu parle du moment où avancer n'est plus la réponse. En lecture, il marque souvent une suspension qui permet de comprendre autrement. C'est la carte de ce qui se gagne en lâchant plutôt qu'en serrant.",
    reversed: "À l'envers, il peut montrer une pause devenue paralysie, ou un sacrifice consenti sans que personne l'ait demandé. Il apparaît aussi quand attendre est plus confortable que décider.",
    love: "Peut indiquer un lien en phase suspendue. Invite à regarder si tu attends quelque chose de réel ou d'imaginé.",
    work: 'Favorise revoir une approche plutôt que travailler plus fort. Si un projet cale, le blocage est sans doute dans la prémisse.',
    growth: 'Demande-toi ce que tu verrais si tu cessais de défendre ta version.',
    yesNo: 'depends',
    astrology: 'Symboliquement lié à Neptune.'
  },
  M13: {
    keywords: ['Fin', 'Transformation', 'Seuil'],
    energy: "Quelque chose s'achève pour qu'autre chose ait de la place.",
    advice: "Lâche ce qui est déjà fini ; le porter ne le conserve pas.",
    light: ['Clôture nécessaire', 'Renouveau profond', 'Se délester de ce qui pesait'],
    shadow: ['S’accrocher au passé', 'Craindre tout changement', 'Finir brutalement pour éviter le deuil'],
    upright: "La Mort parle rarement d'une fin littérale. Elle marque un seuil : une étape qui se ferme et ne se rouvrira pas. Dans un tirage, elle indique souvent une transformation déjà commencée, où résister coûte plus qu'accepter.",
    reversed: "À l'envers, elle peut montrer un changement refusé, maintenu à grands frais. Elle apparaît aussi quand une fin est précipitée pour sauter ce qu'il fait mal de sentir.",
    love: "Peut parler d'un lien qui n'est plus ce qu'il était. Invite à regarder ce qui est là, pas ce qui y était.",
    work: 'Favorise fermer un cycle, quitter ce qui est fini ou transformer une manière de travailler. Ce qui s’achève ici fait place à la suite.',
    growth: 'Regarde quelle part de ton identité tu défends par peur du vide.',
    yesNo: 'no',
    astrology: 'Symboliquement liée au Scorpion.'
  },
  M14: {
    keywords: ['Mesure', 'Mélange', 'Juste milieu'],
    energy: "La patience de combiner deux choses jusqu'à ce qu'elles fonctionnent ensemble.",
    advice: "Cherche la proportion, pas l'extrême.",
    light: ['Équilibre trouvé', 'Ajustement patient', 'Sérénité dans le processus'],
    shadow: ['Tiédeur sans fin', 'Éviter le conflit en le diluant', "Ajuster sans jamais s'engager"],
    upright: "Tempérance parle de ce qui s'obtient en mélangeant bien plutôt qu'en tranchant fort. En lecture, elle indique souvent une affaire qui se réglera par ajustement graduel. C'est la carte de la juste dose.",
    reversed: "À l'envers, elle peut montrer un déséquilibre maintenu, ou une modération qui est en fait de l'évitement. Elle apparaît aussi quand on choisit le milieu pour ne pas déranger et non parce qu'il est juste.",
    love: "Peut indiquer un lien qui a besoin de rythme plus que d'intensité. Invite à regarder ce que chacun peut tenir vraiment.",
    work: 'Favorise la négociation, le processus graduel et un rythme soutenable. Si quelque chose t’épuise, le problème est la dose plutôt que la direction.',
    growth: 'Demande-toi où tu oscilles entre tout et rien, et à quoi ressemblerait le milieu.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée au Sagittaire.'
  },
  M15: {
    keywords: ['Attachement', 'Désir', 'Chaîne'],
    energy: "Ce qui te retient et s'appelle nécessité.",
    advice: "Regarde la chaîne de près : souvent elle n'est pas fermée.",
    light: ['Voir le lien clairement', 'Assumer son désir', 'Humour envers sa propre ombre'],
    shadow: ['Dépendance', 'Justifier ce qui te fait mal', 'Confondre intensité et amour'],
    upright: "Le Diable parle de ce qui lie sans s'imposer. Dans un tirage, il indique souvent une habitude, un lien ou une croyance qui tiennent parce que les lâcher paraît plus dur que les garder. C'est la carte de la chaîne qu'on voit dès qu'on décide de regarder.",
    reversed: "À l'envers, il marque souvent le début de la libération : le moment où tu nommes ce qui te retenait. Il peut aussi montrer un attachement défendu d'autant plus fort qu'il est près d'être vu.",
    love: "Peut indiquer un lien où désir et dépendance se sont emmêlés. Invite à séparer ce que tu veux de ce que tu crains de perdre.",
    work: 'Surveille les situations tolérées par sécurité. Cela vaut la peine de regarder ce que l’arrangement te coûte vraiment.',
    growth: 'Regarde ce que tu appelles impossible à changer. Cette phrase fait souvent partie de la chaîne.',
    yesNo: 'no',
    astrology: 'Symboliquement lié au Capricorne.'
  },
  M16: {
    keywords: ['Rupture', 'Révélation', 'Effondrement'],
    energy: "Ce qui reposait sur une prémisse fausse cède d'un coup.",
    advice: 'Ne rebâtis pas la même chose sur le même terrain.',
    light: ['Vérité qui libère', "Libération d'une structure fausse", 'Clarté après le choc'],
    shadow: ['Peur que tout tombe', 'Reconstruire la même erreur', 'Détruire pour ne pas réparer'],
    upright: "La Maison Dieu parle de l'effondrement soudain de ce qui ne tenait pas. En lecture, elle indique souvent une révélation qui arrive sans prévenir et change le tableau. C'est inconfortable, mais cela retire d'ordinaire plus de poids que cela n'en ajoute.",
    reversed: "À l'envers, elle peut montrer un effondrement repoussé à un coût croissant, ou une crise traversée sans apprendre ce qu'elle venait montrer.",
    love: 'Peut indiquer une vérité qui change la façon de voir le lien. Invite à regarder ce que le silence soutenait.',
    work: 'Moment pour revoir les fondations plutôt que les détails. Si quelque chose casse, demande sur quoi cela reposait.',
    growth: "Demande-toi laquelle de tes certitudes ne survivrait pas à une question honnête.",
    yesNo: 'no',
    astrology: 'Symboliquement liée à Mars.'
  },
  M17: {
    keywords: ['Espérance', 'Calme', 'Orientation'],
    energy: "Le calme qui revient une fois la tempête passée.",
    advice: "Fie-toi à la petite lumière ; elle n'a pas besoin de tout éclairer.",
    light: ['Foi renouvelée', 'Sérénité', 'Direction claire'],
    shadow: ['Attendre sans agir', 'Idéaliser le résultat', "Se servir de l'espoir pour éviter le présent"],
    upright: "L'Étoile parle de ce qui se restaure lentement après un passage dur. Dans un tirage, elle marque souvent une période de calme et d'orientation, où le chemin n'est pas encore évident mais ne fait plus peur.",
    reversed: "À l'envers, elle peut montrer le découragement, ou un espoir déposé là où il ne peut pas tenir. Elle apparaît aussi quand attendre remplace le petit pas qui aiderait vraiment.",
    love: "Peut indiquer un lien qui se répare avec le temps et l'honnêteté. Invite à regarder ce qui s'est déjà amélioré, pas seulement ce qui manque.",
    work: 'Favorise les projets longs et les reprises patientes. Bon moment pour poser une direction sans exiger de résultats immédiats.',
    growth: 'Regarde ce qui te soutient quand rien ne va. Cela mérite d’être nommé.',
    yesNo: 'yes',
    astrology: 'Symboliquement liée au Verseau.'
  },
  M18: {
    keywords: ['Incertitude', 'Imagination', 'Ce qui est caché'],
    energy: "Ce qu'on ne voit qu'à moitié et que l'esprit complète tout seul.",
    advice: 'Sépare ce que tu sais de ce que tu supposes.',
    light: ["Accès à l'intuitif", 'Imagination riche', "Reconnaître ce qui n'est pas clair"],
    shadow: ['Peur anticipée', 'Se mentir à soi-même', 'Décider sans voir'],
    upright: "La Lune parle du territoire où le contour n'est pas net. En lecture, elle indique souvent une situation où il manque de l'information, et où l'imagination comble les vides plus vite que les faits. Elle demande de la prudence, pas de l'alarme.",
    reversed: "À l'envers, elle peut marquer le moment où la confusion se dissipe, ou l'inverse : une illusion défendue parce que regarder en face coûterait quelque chose.",
    love: 'Peut indiquer un lien où trop de choses restent non dites. Invite à demander plutôt qu’à interpréter.',
    work: "Pas le meilleur moment pour des décisions irréversibles. Mieux vaut réunir ce qui manque avant de s'engager.",
    growth: "Demande-toi quelle peur tu n'as jamais confrontée au réel.",
    yesNo: 'likely_no',
    astrology: 'Symboliquement liée aux Poissons.'
  },
  M19: {
    keywords: ['Clarté', 'Vitalité', 'Reconnaissance'],
    energy: "Tout est visible et il n'y a rien à cacher.",
    advice: "Laisse-toi voir tel que tu es ; cela coûte moins que l'inverse.",
    light: ['Joie simple', 'Clarté sans ombre', 'Confiance méritée'],
    shadow: ['Optimisme aveuglant', "Besoin d'être admiré", 'Ignorer ce qui ne brille pas'],
    upright: "Le Soleil parle de ce qui se montre sans détour. Dans un tirage, il marque souvent une période de clarté, d'énergie et de choses qui fonctionnent sans avoir à être forcées. C'est la carte du visible et du bien éclairé.",
    reversed: "À l'envers, il peut montrer une lumière ternie par la fatigue ou le doute, ou un éclat entretenu pour les autres à un coût privé. Il apparaît aussi quand on ne s'autorise pas à savourer une bonne nouvelle.",
    love: 'Peut indiquer un lien qui va bien et n’a pas besoin d’être compliqué. Invite à profiter de ce qui est là.',
    work: 'Favorise la visibilité, la reconnaissance et les projets qui aboutissent. Bon moment pour montrer ce que tu as fait.',
    growth: "Regarde ce que tu ferais si tu n'avais besoin de l'approbation de personne.",
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Soleil.'
  },
  M20: {
    keywords: ['Bilan', 'Appel', 'Éveil'],
    energy: 'Quelque chose du passé revient en demandant à être réglé.',
    advice: 'Regarde en arrière une fois, honnêtement, puis referme.',
    light: ['Révision lucide', 'Pardon qui libère', 'Répondre à un appel réel'],
    shadow: ['Se juger sans pitié', 'Rouvrir ce qui était réglé', "Ignorer l'évidence"],
    upright: "Le Jugement parle du moment où l'ensemble se voit d'un coup. En lecture, il indique souvent une révision qui change la façon de comprendre une étape, et une décision qui en découle. C'est la carte de ce qui s'éveille une fois enfin nommé.",
    reversed: "À l'envers, il peut montrer une révision devenue autopunition, ou un appel entendu et mis de côté. Il apparaît aussi quand on revient si souvent au passé que rien de neuf ne se décide.",
    love: 'Peut indiquer quelque chose en suspens qui a besoin d’être dit. Invite à le dire une fois et clairement.',
    work: 'Favorise évaluer une étape et décider ce qui continue. Bon moment pour les bilans plutôt que pour les débuts.',
    growth: "Demande-toi ce que tu te pardonnerais en le regardant sans le verdict par-dessus.",
    yesNo: 'likely_yes',
    astrology: 'Symboliquement lié à Pluton.'
  },
  M21: {
    keywords: ['Achèvement', 'Intégration', 'Ensemble'],
    energy: 'Un cycle se referme avec chaque chose à sa place.',
    advice: 'Reconnais ce que tu as terminé avant de courir vers la suite.',
    light: ['Cycle accompli', "Sentiment d'appartenance", 'Intégration de ce qui a été appris'],
    shadow: ["S'installer parce que cela a marché une fois", 'Craindre le prochain début', 'Fermer sans reconnaître'],
    upright: "Le Monde parle du point où les pièces s'emboîtent. Dans un tirage, il marque souvent un achèvement gagné plutôt qu'accordé, et le calme qui l'accompagne. C'est la carte de ce qui est assez entier pour être lâché.",
    reversed: "À l'envers, il peut montrer une clôture presque atteinte et repoussée, ou une fin déclarée avant d'être réelle. Il apparaît aussi quand arriver est plus difficile que voyager.",
    love: 'Peut indiquer un lien parvenu à maturité. Invite à regarder le chemin parcouru plutôt que ce qui manque.',
    work: 'Favorise livrer, clore et consolider. Bon moment pour reconnaître le travail avant d’ouvrir le front suivant.',
    growth: 'Regarde ce que tu as terminé et ne t’es jamais permis de célébrer.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié à Saturne.'
  },
};
