/* ============================================================
   ORÁCULO MÍSTICO · CONTENU DES ARCANES · FRANÇAIS
   Phase 13A. Mêmes clés que dans les autres langues : M00-M21 et
   B/C/E/O 01-14. yesNo contient un code, jamais un libellé.
   ============================================================ */

export const CONTENIDO = {
  M00: {
    keywords: ['Commencement', 'Liberté', 'Confiance'],
    energy: "L'élan de commencer quelque chose sans tout avoir résolu.",
    advice: 'Fais le premier pas même si la carte est incomplète ; tu la dessineras en chemin.',
    light: ['Ouverture au neuf', 'Spontanéité', 'Absence de préjugé'],
    shadow: ['Improviser sans mesure', 'Fuir les engagements', 'Dispersion'],
    upright: "Le Mat marque le point où une histoire n'a pas encore commencé à s'écrire. Il parle de disponibilité : la capacité de regarder quelque chose sans le poids de ce que tu sais déjà. En lecture, il indique souvent un début qui demande plus de confiance que de planification.",
    reversed: "À l'envers, l'élan se bloque. Cela peut montrer la peur de lâcher le connu, ou l'inverse : se lancer sans écouter le moindre signal. Mieux vaut savoir laquelle des deux se joue avant de bouger.",
    love: "Peut indiquer un lien dans sa phase la plus légère, où rien n'est encore défini. Invite à parler des attentes plutôt qu'à les supposer.",
    work: "Bon moment pour explorer, apprendre autre chose ou tester une idée à petite échelle. Si un projet est en cours, vérifie ce que tu tiens pour acquis sans l'avoir confirmé.",
    growth: "Demande-toi ce que tu ferais si te tromper ne t'inquiétait pas. La réponse pointe souvent ce que tu remets à plus tard.",
    yesNo: 'likely_yes',
    astrology: "Symboliquement lié à Uranus et à l'air sans forme."
  },
  M01: {
    keywords: ['Initiative', 'Habileté', 'Manifestation'],
    energy: 'Un élan pour transformer une intention en action.',
    advice: "Sers-toi d'abord de ce que tu as déjà avant de chercher ailleurs.",
    light: ['Clarté du but', 'Talent appliqué', 'Communication efficace'],
    shadow: ['Promettre plus que ce qui tient', "Se servir de l'habileté pour manipuler", 'Commencer sans finir'],
    upright: "Le Bateleur rassemble sur la table tout le nécessaire et le met au travail. Il parle de capacité pratique : savoir ce que tu as et à quoi cela sert. Dans un tirage, il marque souvent un moment où la volonté et les moyens coïncident.",
    reversed: "À l'envers, il peut montrer un potentiel qui ne se concrétise pas, ou une adresse dépensée à convaincre plutôt qu'à construire. Il apparaît aussi quand le focus manque : trop d'outils et aucun choisi.",
    love: "Peut parler d'une attraction née de la conversation et d'un intérêt sincère. Invite à dire ce que tu veux au lieu de le suggérer.",
    work: "Favorise présenter une idée, lancer un projet ou reprendre quelque chose avec méthode. En études, indique que le matériel dont tu as besoin est sans doute déjà à portée.",
    growth: "Regarde quelle de tes compétences dort depuis longtemps. La reprendre vaut souvent mieux que d'en apprendre une neuve.",
    yesNo: 'yes',
    astrology: 'Symboliquement lié à Mercure.'
  },
  M02: {
    keywords: ['Intuition', 'Silence', 'Savoir intérieur'],
    energy: "Ce que l'on sait sans encore pouvoir l'expliquer.",
    advice: 'Écoute avant de répondre ; tout ne demande pas une réponse immédiate.',
    light: ['Intuition fine', 'Discrétion', 'Patience avec le processus'],
    shadow: ['Tout garder pour soi', 'Confondre distance et sagesse', 'Attendre sans agir'],
    upright: "La Papesse garde ce qu'il n'est pas encore temps de dire. En lecture, elle indique souvent un moment pour recueillir plutôt que pour décider, et la confiance en une perception qui n'a pas encore de mots.",
    reversed: "À l'envers, elle peut montrer une intuition négligée, ou un secret gardé au-delà de son utilité. Elle apparaît aussi quand le silence cesse de protéger et commence à isoler.",
    love: "Peut indiquer un lien où il se passe plus de choses sous la surface qu'on ne le dit. Invite à demander plutôt qu'à deviner.",
    work: 'Bon moment pour observer et se documenter avant de bouger. Cela vaut la peine d’écouter ce qui n’a pas été dit à voix haute.',
    growth: "Demande-toi ce que tu sais et ne t'es pas encore autorisé à reconnaître.",
    yesNo: 'depends',
    astrology: 'Symboliquement liée à la Lune.'
  },
  M03: {
    keywords: ['Abondance', 'Soin', 'Fertilité'],
    energy: "Ce qui pousse quand on lui donne du temps et de l'attention.",
    advice: "Prends soin de ce que tu as déjà semé avant de semer autre chose.",
    light: ['Générosité', 'Créativité qui porte ses fruits', 'Présence nourrissante'],
    shadow: ['Prendre soin de tous sauf de soi', 'Surprotection', 'Confort qui immobilise'],
    upright: "L'Impératrice parle de ce qui fleurit par un soin soutenu. Dans un tirage, elle marque souvent une étape fertile : des projets qui prennent, des liens qui se consolident, des corps qui demandent de l'attention.",
    reversed: "À l'envers, elle peut montrer un épuisement à force de donner sans mesure, ou une créativité bloquée par l'exigence. Elle apparaît aussi quand on confond prendre soin et contrôler.",
    love: "Peut indiquer un lien chaleureux et durable. Invite à recevoir autant que tu donnes.",
    work: 'Favorise le travail créatif et tout ce qui demande une constance douce. Bon moment pour faire grandir ce qui marche déjà.',
    growth: 'Regarde quelle part de ton énergie va vers toi. Si la réponse pique, c’est là qu’est le travail.',
    yesNo: 'yes',
    astrology: 'Symboliquement liée à Vénus.'
  },
  M04: {
    keywords: ['Structure', 'Autorité', 'Protection'],
    energy: "La stabilité qui vient d'une limite clairement posée.",
    advice: 'Décide quelle est la règle avant que la situation ne décide pour toi.',
    light: ['Ordre qui soutient', 'Responsabilité assumée', 'Présence fiable'],
    shadow: ['Rigidité', 'Contrôle déguisé en attention', "Peur de l'imprévu"],
    upright: "L'Empereur parle du cadre qui tient les choses : horaires, limites, accords. En lecture, il indique souvent une affaire qui s'améliorera moins par inspiration que par structure. C'est la carte de ce qui reste debout parce que quelqu'un l'a bâti ainsi.",
    reversed: "À l'envers, il peut montrer une autorité devenue raideur, ou l'inverse : une vie sans aucun cadre, où chaque décision repart de zéro. Il apparaît aussi quand on obéit à une règle que personne n'a revue depuis des années.",
    love: "Peut indiquer un lien qui a besoin d'accords clairs plus que de grandes déclarations. Invite à nommer ce que chacun attend.",
    work: 'Favorise planifier, définir les rôles et poser des limites à ce que tu acceptes. Si quelque chose paraît chaotique, la réponse est structurelle plutôt que motivationnelle.',
    growth: 'Regarde lesquelles de tes règles tu as héritées sans jamais les examiner. Certaines servent encore ; d’autres ne font que peser.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Bélier.'
  },
  M05: {
    keywords: ['Tradition', 'Enseignement', 'Appartenance'],
    energy: 'Un savoir qui vient de ceux qui ont marché avant.',
    advice: "Avant d'inventer le chemin, demande si quelqu'un l'a déjà tracé.",
    light: ['Apprentissage partagé', "Sentiment d'appartenance", 'Guidance fondée'],
    shadow: ['Répéter sans questionner', 'Dogme', 'Peur de sortir du groupe'],
    upright: "Le Pape parle de ce qui se transmet : un métier, une foi, une manière de faire. Dans un tirage, il marque souvent un moment pour apprendre d'une source établie, ou pour reconnaître la valeur de ce qu'une communauté sait déjà.",
    reversed: "À l'envers, il peut marquer le point où l'hérité cesse de convenir. Il peut montrer une révolte pour la révolte, ou une tradition maintenue par inertie plus que par conviction.",
    love: "Peut parler d'un lien qui va vers le formel ou le partagé. Invite à regarder quel modèle familial tu répètes sans le voir.",
    work: "Favorise se former, accompagner et travailler dans un cadre établi. Si tu te sens bloqué, une voix expérimentée aidera sans doute plus qu'un essai solitaire de plus.",
    growth: "Demande-toi quelle de tes croyances tu n'as jamais mise à l'épreuve. L'examiner ne veut pas dire la perdre.",
    yesNo: 'neutral',
    astrology: 'Symboliquement lié au Taureau.'
  },
  M06: {
    keywords: ['Choix', 'Union', 'Valeurs'],
    energy: 'Le moment où deux chemins ne peuvent pas être pris ensemble.',
    advice: 'Choisis depuis ce que tu values, pas depuis ce que tu crains de perdre.',
    light: ['Connexion sincère', 'Décision alignée', 'Honnêteté sur le désir'],
    shadow: ['Indécision sans fin', 'Choisir pour plaire', "Idéaliser l'option écartée"],
    upright: "L'Amoureux parle moins de romance que de choix. Il parle du point où il faut dire oui à une chose et, ce faisant, non à une autre. En lecture, il demande souvent ce que tu values vraiment, une fois les apparences mises de côté.",
    reversed: "À l'envers, il peut montrer une décision repoussée jusqu'à ce que les circonstances la prennent pour toi, ou une union nouée sans honnêteté sur ce que chacun veut. Il apparaît aussi quand valeurs et actes se sont éloignés.",
    love: "Peut indiquer un lien à un moment qui demande d'être nommé à voix haute. Invite à dire ce que tu veux sans l'adoucir jusqu'à le faire disparaître.",
    work: "Marque souvent un choix entre deux directions, ou une association qui a besoin de termes explicites. Cela vaut la peine d'écrire ce que chaque option coûte vraiment.",
    growth: 'Regarde où tu dis oui avec la bouche et non avec le corps. Cet écart est le message.',
    yesNo: 'depends',
    astrology: 'Symboliquement lié aux Gémeaux.'
  },
  M07: {
    keywords: ['Direction', 'Volonté', 'Avancée'],
    energy: 'Un mouvement en avant tenu par un acte de volonté.',
    advice: "Tire les rênes dans une seule direction ; deux à la fois s'annulent.",
    light: ['Détermination', 'Maîtrise de soi', 'Élan soutenu'],
    shadow: ['Forcer le rythme', 'Avancer sans regarder de côté', 'Gagner à tout prix'],
    upright: "Le Chariot parle d'un mouvement qui ne se fait pas tout seul : quelqu'un conduit. Dans un tirage, il marque souvent une étape où l'effort paie, tant que la direction reste unique. C'est la carte de tenir des forces opposées assez longtemps pour arriver.",
    reversed: "À l'envers, il peut montrer une énergie éparpillée sur trop de fronts, ou une poussée devenue pression. Il apparaît aussi quand tu vas vite dans une direction que personne n'a réexaminée.",
    love: "Peut parler d'un lien qui a besoin d'une direction commune plus que d'intensité. Invite à vérifier si vous voulez la même chose.",
    work: "Favorise pousser un projet et le défendre. Si l'avancée s'est arrêtée, la cause est plus souvent l'attention divisée que le manque de capacité.",
    growth: 'Demande-toi ce que tu conduis par conviction et ce que tu conduis par élan. Ce ne sont pas les mêmes carburants.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Cancer.'
  },
  M08: {
    keywords: ['Force', 'Patience', 'Retenue'],
    energy: "La force tranquille qui persuade au lieu d'imposer.",
    advice: 'Approche avec douceur ce qui te fait peur ; forcer ne ferait que le durcir.',
    light: ['Courage serein', 'Compassion envers soi', 'Maîtrise de soi'],
    shadow: ['Ravaler ce qui doit se dire', 'Confondre patience et résignation', 'Nier la colère'],
    upright: "La Force parle d'un pouvoir qui n'a pas besoin d'élever la voix. En lecture, elle indique souvent une situation qui cédera à la constance plutôt qu'à la pression. C'est la carte d'apprivoiser le sauvage en restant avec lui, non en le vainquant.",
    reversed: "À l'envers, elle peut montrer une patience à bout, ou sa contrefaçon : endurer ce qu'il aurait fallu nommer depuis longtemps. Elle apparaît aussi quand l'effort de tout tenir commence à coûter plus qu'il ne rapporte.",
    love: "Peut indiquer un lien qui grandit par la tendresse et le temps. Invite à regarder ce que tu tolères et appelles acceptation.",
    work: 'Favorise un effort soutenu et des conversations difficiles menées au calme. Si quelque chose résiste, insister plus fort n’aidera sans doute pas.',
    growth: 'Regarde quelle part de toi tu traites en ennemie. Elle veut souvent seulement être entendue.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée au Lion.'
  },
  M09: {
    keywords: ['Recherche', 'Solitude', 'Discernement'],
    energy: 'Se retirer pour y voir clair.',
    advice: "Offre-toi le silence dont tu as besoin avant de demander à quiconque.",
    light: ['Introspection honnête', 'Sagesse acquise', 'Solitude choisie'],
    shadow: ['Isolement comme fuite', 'Ruminer sans décider', "Refuser l'aide"],
    upright: "L'Ermite parle du pas en arrière qui permet de voir l'ensemble. Dans un tirage, il marque souvent un temps pour regarder au-dedans plutôt qu'au-dehors, et pour se fier à une réponse plus lente. C'est la carte de la lumière que tu portes, non de celle qu'on te donne.",
    reversed: "À l'envers, il peut montrer une solitude qui a cessé d'être utile et est devenue une cachette. Il apparaît aussi quand la recherche ne finit jamais parce que décider semble plus risqué que continuer à chercher.",
    love: "Peut parler d'un besoin d'espace qui n'est pas un rejet. Invite à dire que tu as besoin de temps plutôt qu'à le prendre sans rien dire.",
    work: "Favorise l'étude, la révision et le travail indépendant. Bon moment pour examiner un processus que personne n'a questionné depuis longtemps.",
    growth: "Demande-toi ce que tu comprendrais si tu cessais de remplir chaque silence.",
    yesNo: 'depends',
    astrology: 'Symboliquement lié à la Vierge.'
  },
  M10: {
    keywords: ['Cycle', 'Tour', 'Moment'],
    energy: "Quelque chose bouge tout seul et demande à être lu plutôt que poussé.",
    advice: 'Regarde quelle part dépend de toi et quelle part tourne simplement.',
    light: ['Moment favorable', 'Changement qui débloque', 'Perspective sur le cycle'],
    shadow: ['Attendre que la chance travaille', 'Résister au tour', 'Accuser les circonstances'],
    upright: "La Roue de Fortune parle du mouvement qui ne demande pas la permission. En lecture, elle indique souvent un changement déjà en cours, où la bonne question est comment tu t'y places, non comment tu l'arrêtes.",
    reversed: "À l'envers, elle peut montrer l'attachement à une phase terminée, ou l'impression de tourner sans avancer. Elle apparaît aussi quand tout est laissé au hasard et rien au choix.",
    love: "Peut indiquer un lien qui entre dans une autre phase. Invite à regarder ce qui a changé, pas ce dont tu te souviens.",
    work: "Favorise s'adapter à un changement plutôt que le combattre. Si un cycle se ferme, le geste utile est de préparer le suivant.",
    growth: 'Regarde quel schéma de ta vie est revenu. Le reconnaître fait la moitié du chemin.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée à Jupiter.'
  },
  M11: {
    keywords: ['Équilibre', 'Vérité', 'Conséquence'],
    energy: "Ce qui a été mis en route revient avec tout son poids.",
    advice: 'Regarde les faits avant de chercher un coupable.',
    light: ['Honnêteté envers soi', 'Décision juste', 'Responsabilité assumée'],
    shadow: ['Jugement rigide', 'Accuser pour ne pas regarder', 'Peser sans décider'],
    upright: "La Justice parle de cause et d'effet sans drame. Dans un tirage, elle indique souvent une affaire qui se réglera selon ce qui est vrai, non selon ce qui arrangerait. C'est la carte des comptes qui s'équilibrent.",
    reversed: "À l'envers, elle peut montrer une décision prise sur une information partielle, ou un déséquilibre toléré si longtemps qu'il paraît normal. Elle apparaît aussi quand on exige l'honnêteté des autres et pas de soi.",
    love: "Peut parler d'un lien qui a besoin d'égaliser ses termes. Invite à regarder ce que chacun donne et reçoit.",
    work: 'Favorise contrats, révisions et accords clairs. Bon moment pour vérifier ce que tu as signé et si cela tient encore.',
    growth: 'Demande-toi ce que tu sais déjà et as choisi de ne pas regarder en face.',
    yesNo: 'depends',
    astrology: 'Symboliquement liée à la Balance.'
  },
  M12: {
    keywords: ['Pause', 'Perspective', 'Lâcher-prise'],
    energy: "Un arrêt qui n'est pas une défaite mais un changement d'angle.",
    advice: "Cesse de pousser et regarde la même chose depuis l'autre côté.",
    light: ['Pause utile', 'Lâcher le contrôle', 'Point de vue neuf'],
    shadow: ['Attendre comme prétexte', "Sacrifice que personne n'a demandé", "S'habituer à être bloqué"],
    upright: "Le Pendu parle du moment où avancer n'est plus la réponse. En lecture, il marque souvent une suspension qui permet de comprendre autrement. C'est la carte de ce qui se gagne en lâchant plutôt qu'en serrant.",
    reversed: "À l'envers, il peut montrer une pause devenue paralysie, ou un sacrifice consenti sans que personne l'ait demandé. Il apparaît aussi quand attendre est plus confortable que décider.",
    love: "Peut indiquer un lien en phase suspendue. Invite à regarder si tu attends quelque chose de réel ou d'imaginé.",
    work: 'Favorise revoir une approche plutôt que travailler plus fort. Si un projet cale, le blocage est sans doute dans la prémisse.',
    growth: 'Demande-toi ce que tu verrais si tu cessais de défendre ta version.',
    yesNo: 'depends',
    astrology: 'Symboliquement lié à Neptune.'
  },
  M13: {
    keywords: ['Fin', 'Transformation', 'Seuil'],
    energy: "Quelque chose s'achève pour qu'autre chose ait de la place.",
    advice: "Lâche ce qui est déjà fini ; le porter ne le conserve pas.",
    light: ['Clôture nécessaire', 'Renouveau profond', 'Se délester de ce qui pesait'],
    shadow: ['S’accrocher au passé', 'Craindre tout changement', 'Finir brutalement pour éviter le deuil'],
    upright: "La Mort parle rarement d'une fin littérale. Elle marque un seuil : une étape qui se ferme et ne se rouvrira pas. Dans un tirage, elle indique souvent une transformation déjà commencée, où résister coûte plus qu'accepter.",
    reversed: "À l'envers, elle peut montrer un changement refusé, maintenu à grands frais. Elle apparaît aussi quand une fin est précipitée pour sauter ce qu'il fait mal de sentir.",
    love: "Peut parler d'un lien qui n'est plus ce qu'il était. Invite à regarder ce qui est là, pas ce qui y était.",
    work: 'Favorise fermer un cycle, quitter ce qui est fini ou transformer une manière de travailler. Ce qui s’achève ici fait place à la suite.',
    growth: 'Regarde quelle part de ton identité tu défends par peur du vide.',
    yesNo: 'no',
    astrology: 'Symboliquement liée au Scorpion.'
  },
  M14: {
    keywords: ['Mesure', 'Mélange', 'Juste milieu'],
    energy: "La patience de combiner deux choses jusqu'à ce qu'elles fonctionnent ensemble.",
    advice: "Cherche la proportion, pas l'extrême.",
    light: ['Équilibre trouvé', 'Ajustement patient', 'Sérénité dans le processus'],
    shadow: ['Tiédeur sans fin', 'Éviter le conflit en le diluant', "Ajuster sans jamais s'engager"],
    upright: "Tempérance parle de ce qui s'obtient en mélangeant bien plutôt qu'en tranchant fort. En lecture, elle indique souvent une affaire qui se réglera par ajustement graduel. C'est la carte de la juste dose.",
    reversed: "À l'envers, elle peut montrer un déséquilibre maintenu, ou une modération qui est en fait de l'évitement. Elle apparaît aussi quand on choisit le milieu pour ne pas déranger et non parce qu'il est juste.",
    love: "Peut indiquer un lien qui a besoin de rythme plus que d'intensité. Invite à regarder ce que chacun peut tenir vraiment.",
    work: 'Favorise la négociation, le processus graduel et un rythme soutenable. Si quelque chose t’épuise, le problème est la dose plutôt que la direction.',
    growth: 'Demande-toi où tu oscilles entre tout et rien, et à quoi ressemblerait le milieu.',
    yesNo: 'likely_yes',
    astrology: 'Symboliquement liée au Sagittaire.'
  },
  M15: {
    keywords: ['Attachement', 'Désir', 'Chaîne'],
    energy: "Ce qui te retient et s'appelle nécessité.",
    advice: "Regarde la chaîne de près : souvent elle n'est pas fermée.",
    light: ['Voir le lien clairement', 'Assumer son désir', 'Humour envers sa propre ombre'],
    shadow: ['Dépendance', 'Justifier ce qui te fait mal', 'Confondre intensité et amour'],
    upright: "Le Diable parle de ce qui lie sans s'imposer. Dans un tirage, il indique souvent une habitude, un lien ou une croyance qui tiennent parce que les lâcher paraît plus dur que les garder. C'est la carte de la chaîne qu'on voit dès qu'on décide de regarder.",
    reversed: "À l'envers, il marque souvent le début de la libération : le moment où tu nommes ce qui te retenait. Il peut aussi montrer un attachement défendu d'autant plus fort qu'il est près d'être vu.",
    love: "Peut indiquer un lien où désir et dépendance se sont emmêlés. Invite à séparer ce que tu veux de ce que tu crains de perdre.",
    work: 'Surveille les situations tolérées par sécurité. Cela vaut la peine de regarder ce que l’arrangement te coûte vraiment.',
    growth: 'Regarde ce que tu appelles impossible à changer. Cette phrase fait souvent partie de la chaîne.',
    yesNo: 'no',
    astrology: 'Symboliquement lié au Capricorne.'
  },
  M16: {
    keywords: ['Rupture', 'Révélation', 'Effondrement'],
    energy: "Ce qui reposait sur une prémisse fausse cède d'un coup.",
    advice: 'Ne rebâtis pas la même chose sur le même terrain.',
    light: ['Vérité qui libère', "Libération d'une structure fausse", 'Clarté après le choc'],
    shadow: ['Peur que tout tombe', 'Reconstruire la même erreur', 'Détruire pour ne pas réparer'],
    upright: "La Maison Dieu parle de l'effondrement soudain de ce qui ne tenait pas. En lecture, elle indique souvent une révélation qui arrive sans prévenir et change le tableau. C'est inconfortable, mais cela retire d'ordinaire plus de poids que cela n'en ajoute.",
    reversed: "À l'envers, elle peut montrer un effondrement repoussé à un coût croissant, ou une crise traversée sans apprendre ce qu'elle venait montrer.",
    love: 'Peut indiquer une vérité qui change la façon de voir le lien. Invite à regarder ce que le silence soutenait.',
    work: 'Moment pour revoir les fondations plutôt que les détails. Si quelque chose casse, demande sur quoi cela reposait.',
    growth: "Demande-toi laquelle de tes certitudes ne survivrait pas à une question honnête.",
    yesNo: 'no',
    astrology: 'Symboliquement liée à Mars.'
  },
  M17: {
    keywords: ['Espérance', 'Calme', 'Orientation'],
    energy: "Le calme qui revient une fois la tempête passée.",
    advice: "Fie-toi à la petite lumière ; elle n'a pas besoin de tout éclairer.",
    light: ['Foi renouvelée', 'Sérénité', 'Direction claire'],
    shadow: ['Attendre sans agir', 'Idéaliser le résultat', "Se servir de l'espoir pour éviter le présent"],
    upright: "L'Étoile parle de ce qui se restaure lentement après un passage dur. Dans un tirage, elle marque souvent une période de calme et d'orientation, où le chemin n'est pas encore évident mais ne fait plus peur.",
    reversed: "À l'envers, elle peut montrer le découragement, ou un espoir déposé là où il ne peut pas tenir. Elle apparaît aussi quand attendre remplace le petit pas qui aiderait vraiment.",
    love: "Peut indiquer un lien qui se répare avec le temps et l'honnêteté. Invite à regarder ce qui s'est déjà amélioré, pas seulement ce qui manque.",
    work: 'Favorise les projets longs et les reprises patientes. Bon moment pour poser une direction sans exiger de résultats immédiats.',
    growth: 'Regarde ce qui te soutient quand rien ne va. Cela mérite d’être nommé.',
    yesNo: 'yes',
    astrology: 'Symboliquement liée au Verseau.'
  },
  M18: {
    keywords: ['Incertitude', 'Imagination', 'Ce qui est caché'],
    energy: "Ce qu'on ne voit qu'à moitié et que l'esprit complète tout seul.",
    advice: 'Sépare ce que tu sais de ce que tu supposes.',
    light: ["Accès à l'intuitif", 'Imagination riche', "Reconnaître ce qui n'est pas clair"],
    shadow: ['Peur anticipée', 'Se mentir à soi-même', 'Décider sans voir'],
    upright: "La Lune parle du territoire où le contour n'est pas net. En lecture, elle indique souvent une situation où il manque de l'information, et où l'imagination comble les vides plus vite que les faits. Elle demande de la prudence, pas de l'alarme.",
    reversed: "À l'envers, elle peut marquer le moment où la confusion se dissipe, ou l'inverse : une illusion défendue parce que regarder en face coûterait quelque chose.",
    love: 'Peut indiquer un lien où trop de choses restent non dites. Invite à demander plutôt qu’à interpréter.',
    work: "Pas le meilleur moment pour des décisions irréversibles. Mieux vaut réunir ce qui manque avant de s'engager.",
    growth: "Demande-toi quelle peur tu n'as jamais confrontée au réel.",
    yesNo: 'likely_no',
    astrology: 'Symboliquement liée aux Poissons.'
  },
  M19: {
    keywords: ['Clarté', 'Vitalité', 'Reconnaissance'],
    energy: "Tout est visible et il n'y a rien à cacher.",
    advice: "Laisse-toi voir tel que tu es ; cela coûte moins que l'inverse.",
    light: ['Joie simple', 'Clarté sans ombre', 'Confiance méritée'],
    shadow: ['Optimisme aveuglant', "Besoin d'être admiré", 'Ignorer ce qui ne brille pas'],
    upright: "Le Soleil parle de ce qui se montre sans détour. Dans un tirage, il marque souvent une période de clarté, d'énergie et de choses qui fonctionnent sans avoir à être forcées. C'est la carte du visible et du bien éclairé.",
    reversed: "À l'envers, il peut montrer une lumière ternie par la fatigue ou le doute, ou un éclat entretenu pour les autres à un coût privé. Il apparaît aussi quand on ne s'autorise pas à savourer une bonne nouvelle.",
    love: 'Peut indiquer un lien qui va bien et n’a pas besoin d’être compliqué. Invite à profiter de ce qui est là.',
    work: 'Favorise la visibilité, la reconnaissance et les projets qui aboutissent. Bon moment pour montrer ce que tu as fait.',
    growth: "Regarde ce que tu ferais si tu n'avais besoin de l'approbation de personne.",
    yesNo: 'yes',
    astrology: 'Symboliquement lié au Soleil.'
  },
  M20: {
    keywords: ['Bilan', 'Appel', 'Éveil'],
    energy: 'Quelque chose du passé revient en demandant à être réglé.',
    advice: 'Regarde en arrière une fois, honnêtement, puis referme.',
    light: ['Révision lucide', 'Pardon qui libère', 'Répondre à un appel réel'],
    shadow: ['Se juger sans pitié', 'Rouvrir ce qui était réglé', "Ignorer l'évidence"],
    upright: "Le Jugement parle du moment où l'ensemble se voit d'un coup. En lecture, il indique souvent une révision qui change la façon de comprendre une étape, et une décision qui en découle. C'est la carte de ce qui s'éveille une fois enfin nommé.",
    reversed: "À l'envers, il peut montrer une révision devenue autopunition, ou un appel entendu et mis de côté. Il apparaît aussi quand on revient si souvent au passé que rien de neuf ne se décide.",
    love: 'Peut indiquer quelque chose en suspens qui a besoin d’être dit. Invite à le dire une fois et clairement.',
    work: 'Favorise évaluer une étape et décider ce qui continue. Bon moment pour les bilans plutôt que pour les débuts.',
    growth: "Demande-toi ce que tu te pardonnerais en le regardant sans le verdict par-dessus.",
    yesNo: 'likely_yes',
    astrology: 'Symboliquement lié à Pluton.'
  },
  M21: {
    keywords: ['Achèvement', 'Intégration', 'Ensemble'],
    energy: 'Un cycle se referme avec chaque chose à sa place.',
    advice: 'Reconnais ce que tu as terminé avant de courir vers la suite.',
    light: ['Cycle accompli', "Sentiment d'appartenance", 'Intégration de ce qui a été appris'],
    shadow: ["S'installer parce que cela a marché une fois", 'Craindre le prochain début', 'Fermer sans reconnaître'],
    upright: "Le Monde parle du point où les pièces s'emboîtent. Dans un tirage, il marque souvent un achèvement gagné plutôt qu'accordé, et le calme qui l'accompagne. C'est la carte de ce qui est assez entier pour être lâché.",
    reversed: "À l'envers, il peut montrer une clôture presque atteinte et repoussée, ou une fin déclarée avant d'être réelle. Il apparaît aussi quand arriver est plus difficile que voyager.",
    love: 'Peut indiquer un lien parvenu à maturité. Invite à regarder le chemin parcouru plutôt que ce qui manque.',
    work: 'Favorise livrer, clore et consolider. Bon moment pour reconnaître le travail avant d’ouvrir le front suivant.',
    growth: 'Regarde ce que tu as terminé et ne t’es jamais permis de célébrer.',
    yesNo: 'yes',
    astrology: 'Symboliquement lié à Saturne.'
  },
  B01: {
    keywords: ['Étincelle', 'Élan', 'Initiative'],
    energy: "La première étincelle d'une idée qui veut devenir acte.",
    advice: "Fais-en quelque chose de petit aujourd'hui, avant que l'enthousiasme ne retombe.",
    light: ['Énergie créatrice', 'Enthousiasme sincère', 'Départ net'],
    shadow: ['Élan sans suite', 'Tout commencer à la fois', "Excitation qui s'épuise"],
    upright: "L'As de Bâtons parle du moment où une idée apparaît avec de la chaleur derrière. En lecture, il marque souvent une occasion de commencer, où l'énergie est là et la forme pas encore fixée.",
    reversed: "À l'envers, il peut montrer un élan qui n'a pas pris, ou la platitude qui suit une idée que personne n'a mise en marche. Il apparaît aussi quand l'énergie est trop dispersée pour prendre quelque part.",
    love: 'Peut indiquer une attraction dans sa phase la plus initiale et la moins définie. Invite à la laisser advenir sans l’étiqueter aussitôt.',
    work: 'Favorise lancer quelque chose, proposer une idée ou relancer un projet. Bon moment pour une première version plutôt que pour une parfaite.',
    growth: "Demande-toi ce qui t'enthousiasme et à quoi tu n'as pas fait de place.",
    yesNo: 'yes',
    astrology: 'Le feu dans sa forme la plus pure.'
  },
  B02: {
    keywords: ['Planification', 'Horizon', 'Décision'],
    energy: "La pause entre avoir l'idée et choisir où l'emmener.",
    advice: 'Choisis une direction ; en tenir deux te laisse sur place.',
    light: ["Vision d'avenir", 'Choix délibéré', 'Préparation avant de bouger'],
    shadow: ['Planifier pour ne pas agir', 'Peur de quitter le connu', 'Comparer les options sans fin'],
    upright: "Le Deux de Bâtons parle de se tenir la carte à la main. Dans un tirage, il indique souvent un moment de choisir l'échelle : rester avec le sûr ou tendre vers plus grand.",
    reversed: "À l'envers, il peut montrer un plan qui ne quitte jamais le papier, ou une décision confiée aux circonstances. Il apparaît aussi quand on regarde l'horizon si longtemps que le présent reste sans soin.",
    love: 'Peut indiquer un lien à un point de décision sur sa direction. Invite à dire ce que tu en veux vraiment.',
    work: 'Favorise la stratégie et l’évaluation d’une expansion réelle. Bon moment pour définir l’étape suivante.',
    growth: "Regarde ce que tu tenterais si le résultat n'était garanti dans aucun sens.",
    yesNo: 'depends',
    astrology: 'Mars en Bélier.'
  },
  B03: {
    keywords: ['Expansion', 'Attente', 'Prévoyance'],
    energy: "Le premier geste est fait et on regarde l'horizon.",
    advice: 'Prépare la suite pendant que le pas actuel voyage encore.',
    light: ['Vue longue', 'Patience avec un but', 'Croissance en cours'],
    shadow: ['Attendre passivement', "Perdre l'intérêt avant le résultat", "Attendre plus que ce qui a été semé"],
    upright: "Le Trois de Bâtons parle du moment qui suit l'engagement, quand le résultat n'est pas encore là. En lecture, il indique souvent un projet déjà lancé qui a besoin de recul plus que de poussée.",
    reversed: "À l'envers, il peut montrer de l'impatience avec un processus qui prend simplement du temps, ou des plans devenus plus grands que les moyens qui les portent.",
    love: 'Peut indiquer un lien qui a besoin d’espace pour se développer. Invite à regarder plus loin que l’immédiat.',
    work: 'Favorise l’expansion, la collaboration et penser au-delà de l’échelle actuelle. Bon moment pour préparer la phase suivante.',
    growth: "Demande-toi ce que tu as planté et à quoi tu n'as pas laissé le temps de pousser.",
    yesNo: 'likely_yes',
    astrology: 'Soleil en Bélier.'
  },
  B04: {
    keywords: ['Célébration', 'Foyer', 'Stabilité'],
    energy: 'Une étape assez complète pour être savourée.',
    advice: "Arrête-toi et marque-le ; tout n'a pas à mener ailleurs.",
    light: ['Joie partagée', "Sentiment d'appartenance", 'Base solide'],
    shadow: ["Célébrer ce qui n'est pas fini", "S'installer trop tôt", 'Sauver les apparences'],
    upright: "Le Quatre de Bâtons parle du sol qui tient ferme. Dans un tirage, il marque souvent un moment de stabilité, d'appartenance, ou quelque chose qui mérite d'être reconnu ensemble.",
    reversed: "À l'envers, il peut montrer une stabilité qui semble empruntée, ou une célébration qui masque ce qui n'a pas été réglé.",
    love: 'Peut indiquer un lien qui entre dans une phase posée. Invite à en profiter sans courir vers l’étape suivante.',
    work: 'Favorise consolider, bien clore une étape et reconnaître une équipe. Bon moment pour la gratitude plutôt que pour la pression.',
    growth: 'Regarde où tu te sens chez toi, et ce qui rend cela possible.',
    yesNo: 'yes',
    astrology: 'Vénus en Bélier.'
  },
  B05: {
    keywords: ['Friction', 'Compétition', 'Bruit'],
    energy: 'Plusieurs forces tirent en même temps sans que personne mène.',
    advice: 'Ralentis la discussion et découvre ce qui se dispute vraiment.',
    light: ['Débat sain', 'Énergie qui aiguise', 'Différences mises sur la table'],
    shadow: ['Conflit pour le conflit', 'Friction qui épuise', 'Confondre bruit et progrès'],
    upright: "Le Cinq de Bâtons parle d'énergies qui s'entrechoquent sans s'être encore organisées. En lecture, il indique souvent un désaccord ou une compétition plus fatigante que dangereuse.",
    reversed: "À l'envers, il peut montrer un conflit évité jusqu'à passer sous terre, ou une querelle maintenue vivante parce qu'y mettre fin voudrait dire céder quelque chose.",
    love: 'Peut indiquer des frictions sur de petites choses qui en représentent une plus grande. Invite à nommer le vrai sujet.',
    work: 'Surveille les équipes qui tirent dans des directions différentes. Cela vaut la peine d’accorder l’objectif avant de discuter de la méthode.',
    growth: "Demande-toi ce que tu défends le plus fort, et pourquoi cela compte tant.",
    yesNo: 'likely_no',
    astrology: 'Saturne en Lion.'
  },
  B06: {
    keywords: ['Reconnaissance', 'Succès', 'Visibilité'],
    energy: 'Un effort qui se voit enfin et se reconnaît.',
    advice: "Accepte la reconnaissance sans avoir besoin de la minimiser.",
    light: ['Succès mérité', 'Confiance fondée', 'Leadership qui entraîne'],
    shadow: ['Avoir besoin des applaudissements', 'Un succès qui isole', 'Croire sa propre publicité'],
    upright: "Le Six de Bâtons parle du moment où le travail devient visible. Dans un tirage, il marque souvent une reconnaissance, un objectif atteint ou une place gagnée par ce qui a été fait réellement.",
    reversed: "À l'envers, il peut montrer une reconnaissance qui n'arrive pas, ou qui arrive et ne satisfait pas. Il apparaît aussi quand l'image compte plus que le fond.",
    love: 'Peut indiquer un lien qui va bien et qui se voit ainsi. Invite à partager la bonne nouvelle plutôt qu’à la minimiser.',
    work: 'Favorise présenter des résultats, postuler ou mener une étape. Bon moment pour être visible.',
    growth: 'Regarde si tu peux recevoir un compliment sans l’esquiver.',
    yesNo: 'yes',
    astrology: 'Jupiter en Lion.'
  },
  B07: {
    keywords: ['Défense', 'Position', 'Persistance'],
    energy: 'Tenir le terrain quand tout pousse en sens inverse.',
    advice: "Vérifie que la position vaut l'effort avant de creuser davantage.",
    light: ['Courage sous pression', 'Conviction tenue', 'Terrain avantageux'],
    shadow: ['Défendre par orgueil', 'Épuisement à résister', 'Voir des ennemis partout'],
    upright: "Le Sept de Bâtons parle de tenir bon face à la pression. En lecture, il indique souvent une position à défendre, et l'énergie que cela coûte.",
    reversed: "À l'envers, il peut montrer une défense abandonnée trop tôt, ou tenue bien après que la raison a disparu.",
    love: 'Peut indiquer un lien qui a besoin de limites dites clairement. Invite à dire non sans t’en excuser.',
    work: 'Favorise défendre un critère ou un projet sous examen. Cela vaut la peine de choisir quelles batailles sont vraiment les tiennes.',
    growth: "Demande-toi ce que tu défends alors que personne ne l'attaque.",
    yesNo: 'depends',
    astrology: 'Mars en Lion.'
  },
  B08: {
    keywords: ['Vitesse', 'Nouvelles', 'Mouvement'],
    energy: "Tout s'accélère en même temps et arrive ensemble.",
    advice: "Prends le rythme, mais décide d'abord où tu vas.",
    light: ['Progrès rapide', 'Nouvelles qui débloquent', 'Action au bon moment'],
    shadow: ['Courir sans direction', 'Réagir au lieu de choisir', 'Perdre le détail dans la hâte'],
    upright: "Le Huit de Bâtons parle de choses en vol. Dans un tirage, il marque souvent une période de vitesse : messages, mouvement, affaires qui se règlent plus vite que prévu.",
    reversed: "À l'envers, il peut montrer des retards et des messages qui n'arrivent pas, ou de la vitesse appliquée dans la mauvaise direction.",
    love: 'Peut indiquer un lien qui avance vite. Invite à vérifier que le rythme vous convient à tous les deux.',
    work: 'Favorise la communication, les lancements et tout ce qui dépend du moment. Bon moment pour envoyer ce qui dort dans les brouillons.',
    growth: "Regarde ce que tu ferais aujourd'hui si tu cessais d'attendre un meilleur moment.",
    yesNo: 'yes',
    astrology: 'Mercure en Sagittaire.'
  },
  B09: {
    keywords: ['Résistance', 'Fatigue', 'Garde'],
    energy: 'Fatigué, encore debout, et sans savoir s’il faut continuer.',
    advice: "Repose-toi avant de décider ; l'épuisement est mauvais conseiller.",
    light: ['Résilience éprouvée', "Apprendre de l'expérience", 'Garde qui protège'],
    shadow: ['Se méfier de tout', 'Continuer par entêtement', 'De vieilles blessures qui mènent le présent'],
    upright: "Le Neuf de Bâtons parle du dernier tronçon, quand les réserves sont basses. En lecture, il indique souvent quelque chose de presque fini qui tient à la seule volonté.",
    reversed: "À l'envers, il peut montrer une garde si haute que rien n'entre, ou abandonner juste avant la fin.",
    love: 'Peut indiquer une prudence née d’expériences passées. Invite à vérifier si la garde correspond encore au présent.',
    work: 'Bon moment pour finir plutôt que pour commencer. Cela vaut la peine de demander ce qui a vraiment besoin de ton effort maintenant.',
    growth: "Demande-toi de quoi tu te protèges alors que c'est déjà passé.",
    yesNo: 'depends',
    astrology: 'Lune en Sagittaire.'
  },
  B10: {
    keywords: ['Surcharge', 'Fardeau', 'Excès'],
    energy: 'Porter plus que ce qui tient dans deux mains.',
    advice: "Pose quelque chose ; tout ce qui est sur la liste n'est pas à toi.",
    light: ['Responsabilité assumée', 'Effort proche de la fin', 'Conscience de la limite'],
    shadow: ["Prendre ce qui ne t'appartient pas", "Ne pas demander d'aide", 'Confondre valeur et charge de travail'],
    upright: "Le Dix de Bâtons parle du poids accumulé en chemin. Dans un tirage, il indique souvent une surcharge : un engagement devenu plus grand que prévu.",
    reversed: "À l'envers, il peut marquer le moment de poser ce qui n'était pas à toi, ou l'inverse : continuer jusqu'à ce que quelque chose casse.",
    love: 'Peut indiquer un lien où un côté porte l’essentiel du poids. Invite à regarder comment la charge se répartit.',
    work: 'Surveille les tâches accumulées et les responsabilités non nommées. Cela vaut la peine de déléguer ou de couper.',
    growth: 'Regarde ce que tu portes parce que tu crois que personne d’autre ne le ferait.',
    yesNo: 'likely_no',
    astrology: 'Saturne en Sagittaire.'
  },
  B11: {
    keywords: ['Curiosité', 'Message', 'Enthousiasme'],
    energy: 'Quelqu’un qui veut essayer avant de savoir comment.',
    advice: "Suis la curiosité ; elle n'a pas encore à se justifier.",
    light: ['Enthousiasme frais', "Envie d'apprendre", 'Bonnes nouvelles'],
    shadow: ['Agitation sans suite', 'Impatience', "Promettre plus que ce que l'on sait"],
    upright: "Le Valet de Bâtons parle d'un début mû par l'intérêt plutôt que par le plan. En lecture, il marque souvent des nouvelles, une invitation ou l'envie d'explorer quelque chose de neuf.",
    reversed: "À l'envers, il peut montrer un enthousiasme qui retombe vite, ou une idée plus commentée qu'essayée.",
    love: 'Peut indiquer quelque chose qui commence avec légèreté et curiosité. Invite à en profiter sans y coller d’étiquette.',
    work: 'Favorise apprendre, essayer et demander. Bon moment pour dire que tu ne sais pas.',
    growth: "Demande-toi ce qui t'intrigue et que tu as écarté comme inutile.",
    yesNo: 'likely_yes',
    astrology: 'La terre dans le feu.'
  },
  B12: {
    keywords: ['Action', 'Audace', 'Départ'],
    energy: 'La décision de partir, prise plus par le corps que par la tête.',
    advice: 'Bouge, mais sache ce que tu laisses derrière.',
    light: ["Courage d'agir", 'Aventure', 'Élan décidé'],
    shadow: ['Laisser des choses à moitié', 'Hâte imprudente', 'Fuir au lieu de choisir'],
    upright: "Le Cavalier de Bâtons parle d'une énergie qui ne tient pas en place. Dans un tirage, il marque souvent un départ, un changement de décor, ou une action prise avec conviction et peu de prudence.",
    reversed: "À l'envers, il peut montrer un élan qui se disperse, ou un départ qui est en réalité une fuite.",
    love: 'Peut indiquer une intensité qui arrive vite. Invite à voir si elle reste aussi.',
    work: 'Favorise les mouvements audacieux et les changements de cap. Cela vaut la peine de laisser ton travail dans un état qu’un autre pourrait reprendre.',
    growth: 'Regarde ce que tu ferais si tu cessais de demander la permission.',
    yesNo: 'yes',
    astrology: 'Le feu dans le feu.'
  },
  B13: {
    keywords: ['Magnétisme', 'Confiance', 'Chaleur'],
    energy: "Une présence qui éclaire ce qu'elle approche.",
    advice: 'Sers-toi de ta chaleur pour ouvrir des portes, pas pour remplir la pièce.',
    light: ['Charisme naturel', 'Confiance qui inspire', "Générosité d'âme"],
    shadow: ["Avoir besoin d'être au centre", 'Impatience avec ceux qui vont plus lentement', 'Chaleur qui consume'],
    upright: "La Reine de Bâtons parle d'une assurance qui n'a pas besoin d'être défendue. En lecture, elle indique souvent quelqu'un qui mène par sa présence, ou un moment pour te montrer tel que tu es.",
    reversed: "À l'envers, elle peut montrer une confiance devenue démonstration, ou une lumière ternie par comparaison avec d'autres.",
    love: 'Peut indiquer un lien bâti sur l’admiration et la chaleur. Invite à être généreux sans t’y dissoudre.',
    work: 'Favorise mener, motiver et représenter quelque chose. Bon moment pour prendre un rôle visible.',
    growth: "Demande-toi où tu te fais petit pour que les autres soient à l'aise.",
    yesNo: 'yes',
    astrology: "L'eau dans le feu."
  },
  B14: {
    keywords: ['Vision', 'Leadership', 'Élan'],
    energy: "Quelqu'un qui voit où cela mène et donne aux autres l'envie d'y aller.",
    advice: 'Dis la direction à voix haute ; personne ne peut suivre ce qui reste dans ta tête.',
    light: ['Vision claire', 'Leadership qui inspire', 'Décisions courageuses'],
    shadow: ['Imposer la vision', 'Impatience avec le détail', 'Confondre conviction et certitude'],
    upright: "Le Roi de Bâtons parle d'un feu mûr : une énergie qui a appris la direction. Dans un tirage, il marque souvent la capacité de porter un projet et d'y entraîner les autres.",
    reversed: "À l'envers, il peut montrer une autorité devenue autoritarisme, ou une vision à laquelle personne n'a été convié.",
    love: 'Peut indiquer un lien où un côté donne le rythme. Invite à vérifier que la direction est partagée.',
    work: 'Favorise prendre la barre, décider et défendre une direction. Bon moment pour la décision difficile.',
    growth: 'Regarde ce que tu bâtirais si tu faisais confiance à ton propre jugement.',
    yesNo: 'yes',
    astrology: "L'air dans le feu."
  },
  C01: {
    keywords: ['Ouverture', 'Sentiment', 'Offrande'],
    energy: "Quelque chose commence à se sentir avant de pouvoir s'expliquer.",
    advice: 'Autorise-toi à le ressentir sans décider encore ce que cela veut dire.',
    light: ['Ouverture émotionnelle', 'Affection nouvelle', 'Réceptivité sincère'],
    shadow: ["Se fermer d'avance", 'Déborder sans direction', 'Confondre intensité et profondeur'],
    upright: "L'As de Coupes parle du moment où le cœur s'ouvre. En lecture, il marque souvent le début de quelque chose qui se sent : un lien, une réconciliation, ou le retour de l'émotion après une période engourdie.",
    reversed: "À l'envers, il peut montrer une émotion bloquée, ou offerte là où elle ne peut pas être reçue. Il apparaît aussi quand on réprime ce que l'on ressent parce que cela tombe mal.",
    love: 'Peut indiquer un début avec un vrai poids émotionnel. Invite à recevoir autant que tu donnes.',
    work: 'Favorise tout ce qui est créatif ou relationnel. Bon moment pour travailler avec les gens plutôt qu’autour d’eux.',
    growth: "Demande-toi ce que tu ressens et ne t'es pas permis de nommer.",
    yesNo: 'yes',
    astrology: "L'eau dans sa forme la plus pure."
  },
  C02: {
    keywords: ['Lien', 'Réciprocité', 'Rencontre'],
    energy: 'Deux personnes qui se choisissent en même temps.',
    advice: 'Regarde si ce que tu donnes est aussi ce que tu reçois.',
    light: ['Attirance mutuelle', 'Lien équilibré', 'Compréhension'],
    shadow: ["Idéaliser l'autre", 'Fusionner sans séparation', 'Donner pour être choisi'],
    upright: "Le Deux de Coupes parle d'une connexion entre égaux. Dans un tirage, il marque souvent une rencontre, un accord, ou un lien où les deux côtés sont présents.",
    reversed: "À l'envers, il peut montrer un déséquilibre, ou un lien tenu par un seul. Il apparaît aussi quand on confond proximité et se perdre.",
    love: 'Peut indiquer un lien de vraie réciprocité. Invite à rester toi-même dedans.',
    work: 'Favorise les associations et les collaborations. Bon moment pour convenir des termes avec quelqu’un.',
    growth: 'Regarde ce que tu offres librement et ce que tu offres en attendant quelque chose.',
    yesNo: 'yes',
    astrology: 'Vénus en Cancer.'
  },
  C03: {
    keywords: ['Amitié', 'Célébration', 'Communauté'],
    energy: "Une joie qui grandit parce qu'elle se partage.",
    advice: 'Dis-le à quelqu’un ; garder la bonne nouvelle ne la multiplie pas.',
    light: ['Compagnie chaleureuse', 'Bonheur partagé', 'Soutien sincère'],
    shadow: ["Une compagnie qui évite l'intimité", 'Célébrer pour ne pas sentir', 'Se perdre dans le groupe'],
    upright: "Le Trois de Coupes parle du plaisir d'appartenir. En lecture, il marque souvent l'amitié, la célébration, ou le soulagement de ne pas être seul avec quelque chose.",
    reversed: "À l'envers, il peut montrer un groupe qui ne nourrit plus, ou une vie sociale qui remplit le temps sans remplir autre chose.",
    love: 'Peut indiquer un lien qui naît dans une compagnie partagée. Invite à garder vivantes les amitiés autour.',
    work: 'Favorise le travail d’équipe et la reconnaissance collective. Bon moment pour célébrer avec ceux qui y ont pris part.',
    growth: 'Demande-toi avec qui tu peux être entièrement toi-même.',
    yesNo: 'yes',
    astrology: 'Mercure en Cancer.'
  },
  C04: {
    keywords: ['Apathie', 'Saturation', 'Offre non vue'],
    energy: "On offre quelque chose et il n'y a pas d'appétit pour cela.",
    advice: "Regarde à nouveau ce qui est devant toi avant de l'écarter.",
    light: ['Réexamen honnête', 'Reconnaître ce qui ne comble pas', 'Pause nécessaire'],
    shadow: ['Ennui qui referme tout', 'Ignorer ce qui est disponible', 'Attendre quelque chose de mieux'],
    upright: "Le Quatre de Coupes parle de saturation émotionnelle. Dans un tirage, il indique souvent une période plate où rien n'attire, y compris ce qui devrait objectivement attirer.",
    reversed: "À l'envers, il marque souvent le retour de l'intérêt, ou la décision d'accepter ce qu'on ignorait.",
    love: 'Peut indiquer un lien devenu routine. Invite à regarder si le problème est le lien ou la fatigue.',
    work: 'Surveille les occasions écartées sans examen. Cela vaut la peine de revoir ce que tu as refusé.',
    growth: 'Regarde ce que tu as déjà et que tu as cessé de voir.',
    yesNo: 'likely_no',
    astrology: 'Lune en Cancer.'
  },
  C05: {
    keywords: ['Perte', 'Deuil', 'Ce qui reste'],
    energy: "Regarder ce qui s'est renversé et pas encore ce qui tient debout.",
    advice: 'Fais ton deuil pour de vrai, puis retourne-toi : il reste quelque chose.',
    light: ['Deuil autorisé', 'Acceptation honnête', 'Voir ce qui a survécu'],
    shadow: ['Rester dans la perte', 'Idéaliser ce qui est perdu', 'Refuser la consolation'],
    upright: "Le Cinq de Coupes parle du poids de ce qui n'a pas abouti. En lecture, il indique souvent une déception ou un deuil qui occupe tout le champ de vision.",
    reversed: "À l'envers, il marque souvent le début de la reprise, ou le moment où l'attention se déplace vers ce qui reste.",
    love: 'Peut indiquer une blessure encore ouverte. Invite à laisser la tristesse sans la laisser écrire l’avenir.',
    work: 'Surveille le découragement après un échec. Cela vaut la peine de nommer ce qui a été appris avant de continuer.',
    growth: 'Demande-toi ce que tu as encore et que tu as cessé de compter.',
    yesNo: 'no',
    astrology: 'Mars en Scorpion.'
  },
  C06: {
    keywords: ['Mémoire', 'Innocence', 'Passé'],
    energy: "Quelque chose d'avant revient avec sa chaleur intacte.",
    advice: 'Prends le bon du souvenir sans y retourner vivre.',
    light: ['Nostalgie douce', 'Reconnexion', 'Simplicité retrouvée'],
    shadow: ['Vivre au passé', 'Idéaliser ce qui a été', 'Refuser le présent'],
    upright: "Le Six de Coupes parle de ce qui subsiste d'avant. Dans un tirage, il marque souvent un retour : une personne, un lieu, ou une manière de sentir qui appartenaient à un autre temps.",
    reversed: "À l'envers, il peut montrer un passé qui ne lâche pas, ou une nostalgie qui rend le présent invivable.",
    love: 'Peut indiquer une réapparition, ou un lien avec beaucoup d’histoire commune. Invite à voir la personne d’aujourd’hui, pas celle d’avant.',
    work: 'Favorise renouer avec d’anciens contacts ou relancer un projet mis de côté.',
    growth: 'Regarde ce que tu aimais avant de décider que c’était enfantin.',
    yesNo: 'likely_yes',
    astrology: 'Soleil en Scorpion.'
  },
  C07: {
    keywords: ['Options', 'Fantaisie', 'Confusion'],
    energy: "Trop de possibilités et aucune éprouvée.",
    advice: 'Écarte-en deux avant d’en choisir une ; la liste est le problème.',
    light: ['Imagination riche', 'Largeur de vue', 'Possibilité créative'],
    shadow: ['Ne rien choisir', 'Confondre souhait et plan', "Se laisser séduire par l'irréel"],
    upright: "Le Sept de Coupes parle du moment où les options se multiplient plus vite qu'on ne peut les examiner. En lecture, il indique souvent une confusion née d'abondance et non de manque.",
    reversed: "À l'envers, il marque souvent l'arrivée de la clarté, ou la décision d'essayer une option au lieu d'en imaginer sept.",
    love: 'Peut indiquer une idéalisation. Invite à regarder la personne plutôt que la version que tu as construite.',
    work: "Pas un bon moment pour des choix irréversibles. Mieux vaut rendre une option concrète et voir ce qui se passe.",
    growth: "Demande-toi lesquels de tes projets n'existent que sous forme de conversations.",
    yesNo: 'depends',
    astrology: 'Vénus en Scorpion.'
  },
  C08: {
    keywords: ['Départ', 'Recherche', 'Lâcher-prise'],
    energy: "Quitter quelque chose qui marche, parce que cela ne veut plus rien dire.",
    advice: 'Pars, mais dis pourquoi ; partir sans le nommer répète le schéma.',
    light: ['Départ honnête', 'Quête de sens', 'Courage de partir'],
    shadow: ['Partir avant de comprendre', 'Errer par habitude', 'Abandonner sans clore'],
    upright: "Le Huit de Coupes parle du choix de s'éloigner de ce qui n'est pas mauvais, seulement terminé. Dans un tirage, il marque souvent un départ mû par le sens plutôt que par le conflit.",
    reversed: "À l'envers, il peut montrer rester par culpabilité, ou partir encore et encore sans jamais arriver.",
    love: 'Peut indiquer un lien arrivé au bout de son parcours émotionnel. Invite à le dire plutôt qu’à le laisser s’éteindre.',
    work: 'Surveille un rôle qui ne convient plus. Cela vaut la peine de préparer la sortie plutôt que de l’improviser.',
    growth: 'Regarde ce que tu gardes par loyauté envers celui que tu étais.',
    yesNo: 'likely_no',
    astrology: 'Saturne en Poissons.'
  },
  C09: {
    keywords: ['Satisfaction', 'Souhait', 'Plaisir'],
    energy: 'Quelque chose de désiré arrive et peut se savourer sans culpabilité.',
    advice: "Autorise-toi à l'avoir ; tu ne dois aucune explication.",
    light: ['Contentement', 'Souhait exaucé', 'Bien-être qui se sent'],
    shadow: ['Confort qui arrête la croissance', 'Plaisir qui recouvre autre chose', 'Vouloir plus de la même chose'],
    upright: "Le Neuf de Coupes parle d'une satisfaction qui a vraiment pris. En lecture, il marque souvent un bon moment, un souhait comblé, ou simplement être bien avec ce qui est.",
    reversed: "À l'envers, il peut montrer avoir obtenu ce qu'on demandait et se sentir quand même vide, ou un plaisir servant à éviter autre chose.",
    love: 'Peut indiquer un lien qui apporte un vrai réconfort. Invite à en profiter sans attendre le piège.',
    work: 'Favorise savourer un résultat et le consolider. Bon moment pour reconnaître ce qui a bien marché.',
    growth: 'Demande-toi ce que tu veux vraiment, séparé de ce que tu devrais vouloir.',
    yesNo: 'yes',
    astrology: 'Jupiter en Poissons.'
  },
  C10: {
    keywords: ['Harmonie', 'Famille', 'Plénitude'],
    energy: "Un bien-être émotionnel qui inclut d'autres personnes.",
    advice: 'Prends soin de ce qui marche déjà ; cela ne se maintient pas tout seul.',
    light: ['Bonheur partagé', 'Liens qui tiennent', 'Paix émotionnelle'],
    shadow: ["Idéaliser l'image", "Maintenir l'harmonie par le silence", 'Craindre de la déranger'],
    upright: "Le Dix de Coupes parle d'une plénitude vécue avec d'autres. Dans un tirage, il marque souvent une étape de stabilité émotionnelle où les liens importants sont en ordre.",
    reversed: "À l'envers, il peut montrer une harmonie tenue en surface, ou l'écart entre l'image et la réalité.",
    love: 'Peut indiquer un lien à une étape posée et généreuse. Invite à continuer de dire ce qui va sans dire.',
    work: 'Favorise les environnements où les gens travaillent bien ensemble. Bon moment pour soigner l’ambiance.',
    growth: "Regarde qui tu appellerais s'il t'arrivait quelque chose de bien maintenant.",
    yesNo: 'yes',
    astrology: 'Mars en Poissons.'
  },
  C11: {
    keywords: ['Sensibilité', 'Intuition', 'Message'],
    energy: "Quelque chose de ressenti arrive avant de pouvoir s'expliquer.",
    advice: "Fais attention à l'impression ; tu n'as pas encore à agir.",
    light: ['Intuition fine', 'Ouverture émotionnelle', 'Créativité qui affleure'],
    shadow: ['Sensibilité excessive', 'Tout prendre personnellement', 'Sentir sans agir'],
    upright: "Le Valet de Coupes parle des débuts du sentiment et de l'intuition. En lecture, il marque souvent un message, une invitation, ou une intuition qui mérite d'être écoutée.",
    reversed: "À l'envers, il peut montrer une émotion qui submerge, ou une intuition écartée faute de pouvoir se justifier.",
    love: 'Peut indiquer quelque chose qui commence avec tendresse et sans défenses. Invite à laisser cela être doux.',
    work: 'Favorise le travail créatif et l’écoute des gens. Bon moment pour l’idée qui arrive de côté.',
    growth: 'Demande-toi ce que tu as pressenti et t’es convaincu d’écarter.',
    yesNo: 'likely_yes',
    astrology: "La terre dans l'eau."
  },
  C12: {
    keywords: ['Offre', 'Romantisme', 'Idéalisme'],
    energy: "Quelqu'un s'approche avec une proposition qui vient du cœur.",
    advice: "Accueille le geste et regarde ce qu'il y a derrière, en même temps.",
    light: ['Offre sincère', 'Romantisme', 'Suivre ce que l’on ressent'],
    shadow: ['Promettre plus que ce qui tient', 'Idéaliser', "Un sentiment qui évite l'engagement"],
    upright: "Le Cavalier de Coupes parle d'un mouvement mû par le sentiment. Dans un tirage, il marque souvent une offre, une déclaration, ou un pas fait parce qu'il semblait juste.",
    reversed: "À l'envers, il peut montrer du charme sans fond, ou un sentiment qui s'évapore dès qu'il doit devenir pratique.",
    love: 'Peut indiquer quelqu’un qui s’approche avec une intention sincère. Invite à regarder les actes à côté des mots.',
    work: 'Favorise présenter une idée à laquelle tu crois. Cela vaut la peine de l’ancrer dans quelque chose de concret.',
    growth: 'Regarde ce que tu offrirais si tu ne craignais pas un refus.',
    yesNo: 'likely_yes',
    astrology: "Le feu dans l'eau."
  },
  C13: {
    keywords: ['Empathie', 'Profondeur', 'Attention'],
    energy: "Quelqu'un qui comprend ce qui n'est pas dit.",
    advice: "Prends soin des autres sans t'y dissoudre.",
    light: ['Empathie profonde', 'Intelligence émotionnelle', 'Présence qui apaise'],
    shadow: ["Absorber ce qui n'est pas à toi", "Soigner pour être nécessaire", 'Oublier ses propres besoins'],
    upright: "La Reine de Coupes parle de maturité émotionnelle : sentir profondément et rester stable. En lecture, elle indique souvent quelqu'un qui soutient, ou un moment pour écouter plus que pour résoudre.",
    reversed: "À l'envers, elle peut montrer une émotion qui déborde sur les autres, ou un soin donné jusqu'à ce qu'il ne reste rien pour soi.",
    love: 'Peut indiquer un lien d’une réelle profondeur émotionnelle. Invite à garder ton centre dedans.',
    work: 'Favorise accompagner, prendre soin et arbitrer. Bon moment pour regarder comment vont les gens, pas seulement ce qu’ils livrent.',
    growth: 'Demande-toi quelle part de ton énergie va vers toi. Si la réponse pique, c’est là qu’est le travail.',
    yesNo: 'yes',
    astrology: "L'eau dans l'eau."
  },
  C14: {
    keywords: ['Sérénité', 'Maîtrise', 'Équilibre'],
    energy: 'Sentir profondément et choisir quand même avec calme.',
    advice: "Ressens-le entièrement, puis décide depuis le calme et non depuis la vague.",
    light: ['Équilibre émotionnel', 'Sagesse qui apaise', 'Sang-froid sous pression'],
    shadow: ['Un calme qui cache la distance', 'Réprimer pour rester stable', 'Conseiller au lieu de sentir'],
    upright: "Le Roi de Coupes parle d'une eau mûre : une émotion qui a appris le gouvernement. Dans un tirage, il marque souvent la capacité de mener une affaire délicate sans se laisser emporter.",
    reversed: "À l'envers, il peut montrer une sérénité utilisée comme mur, ou un sentiment contrôlé si serré qu'il cesse d'être senti.",
    love: 'Peut indiquer un lien où quelqu’un tient le calme. Invite à partager ce que tu ressens, pas seulement ce que tu as déjà résolu.',
    work: 'Favorise gérer les conflits et les conversations difficiles. Bon moment pour être la voix tranquille.',
    growth: 'Regarde ce que tu ressens et administres au lieu de le vivre.',
    yesNo: 'yes',
    astrology: "L'air dans l'eau."
  },
  E01: {
    keywords: ['Clarté', 'Vérité', 'Décision'],
    energy: 'Une idée tranche et le tableau devient net.',
    advice: "Dis-le clairement ; l'ambiguïté coûte plus cher que la vérité.",
    light: ['Clarté mentale', 'Vérité dite', 'Décision prise nettement'],
    shadow: ['Vérité utilisée pour blesser', 'Logique froide', 'Décider sans peser'],
    upright: "L'As d'Épées parle du moment où la compréhension arrive. En lecture, il marque souvent une clarté, une décision qui devient évidente, ou une vérité qui change les termes.",
    reversed: "À l'envers, il peut montrer de la confusion, ou une clarté utilisée comme arme. Il apparaît aussi quand la vérité est sue et tue.",
    love: 'Peut indiquer une conversation à avoir. Invite à être honnête et bienveillant à la fois.',
    work: 'Favorise l’analyse, les décisions et la communication claire. Bon moment pour définir le problème avec précision.',
    growth: 'Demande-toi ce que tu sais et fais semblant d’ignorer.',
    yesNo: 'yes',
    astrology: "L'air dans sa forme la plus pure."
  },
  E02: {
    keywords: ['Impasse', 'Évitement', 'Équilibre tenu'],
    energy: 'Ne pas regarder, pour ne pas avoir à choisir.',
    advice: "Enlève le bandeau ; l'information est déjà là.",
    light: ['Pause nécessaire avant de décider', 'Trêve', 'Peser avec soin'],
    shadow: ['Refuser de voir', 'Indécision qui coûte', 'Garder la paix par le silence'],
    upright: "Le Deux d'Épées parle d'une impasse tenue exprès. Dans un tirage, il indique souvent une décision repoussée parce que les deux options ont un coût.",
    reversed: "À l'envers, il marque souvent le moment où le bandeau tombe, ou une impasse qui se rompt avec plus de bruit que nécessaire.",
    love: 'Peut indiquer quelque chose que les deux côtés évitent. Invite à le nommer en premier.',
    work: 'Surveille les décisions retardées jusqu’à ce qu’elles se prennent seules. Cela vaut la peine de fixer une date.',
    growth: 'Regarde ce que tu devrais accepter si tu regardais cela en face.',
    yesNo: 'depends',
    astrology: 'Lune en Balance.'
  },
  E03: {
    keywords: ['Blessure', 'Peine', 'Vérité qui fait mal'],
    energy: "On dit quelque chose de vrai et cela fait exactement aussi mal que prévu.",
    advice: 'Laisse la douleur traverser ; l’expliquer pour l’éviter ne fait que la retarder.',
    light: ['Clarté après la douleur', 'Chagrin nommé', 'Honnêteté même quand elle coûte'],
    shadow: ['Repasser la blessure', 'Accuser pour ne pas pleurer', 'Fermer le cœur ensuite'],
    upright: "Le Trois d'Épées parle de la peine qui vient avec le fait de savoir. En lecture, il marque souvent une déception ou une vérité qui change quelque chose, et le temps qu'il lui faut pour être sentie.",
    reversed: "À l'envers, il marque souvent le début de la guérison, ou l'inverse : une blessure tenue ouverte parce que la refermer voudrait dire avancer.",
    love: 'Peut indiquer une douleur qui doit être dite. Invite à la dire une fois, entièrement, plutôt qu’en morceaux.',
    work: 'Surveille un revers pris personnellement. Cela vaut la peine de séparer le résultat de ta valeur.',
    growth: 'Demande-toi ce que tu ne t’es pas permis de pleurer.',
    yesNo: 'no',
    astrology: 'Saturne en Balance.'
  },
  E04: {
    keywords: ['Repos', 'Récupération', 'Retrait'],
    energy: 'S’arrêter parce que continuer casserait quelque chose.',
    advice: 'Repose-toi vraiment ; une demi-pause ne répare rien.',
    light: ['Récupération réelle', 'Silence qui restaure', 'Reconnaître la limite'],
    shadow: ['Se retirer sans terme', 'Un repos devenu évitement', 'Mal se reposer par culpabilité'],
    upright: "Le Quatre d'Épées parle du retrait nécessaire. Dans un tirage, il indique souvent un moment de récupération plutôt que d'effort, où faire moins est ce qui aide.",
    reversed: "À l'envers, il peut montrer un épuisement ignoré, ou un repos si long que revenir devient difficile.",
    love: 'Peut indiquer un lien qui a besoin de silence plus que de conversation. Invite à permettre la pause sans y lire quoi que ce soit.',
    work: 'Bon moment pour s’arrêter plutôt que pour pousser. Cela vaut la peine de prendre du recul avant de décider quoi que ce soit.',
    growth: "Regarde ce que tu comprendrais si tu n'étais pas fatigué.",
    yesNo: 'depends',
    astrology: 'Jupiter en Balance.'
  },
  E05: {
    keywords: ['Gagner mal', 'Conflit', 'Coût'],
    energy: "On gagne la discussion et on perd autre chose.",
    advice: 'Demande-toi ce que gagner cela t’achète vraiment.',
    light: ['Reconnaître le coût réel', 'Défendre ce qui compte', 'Terminer une dispute honnêtement'],
    shadow: ['Gagner à tout prix', 'Humilier', "Avoir raison au lieu d'aller bien"],
    upright: "Le Cinq d'Épées parle de victoires qui laissent des dégâts. En lecture, il indique souvent un conflit où le coût dépasse le prix.",
    reversed: "À l'envers, il peut marquer l'envie de réparer, ou un conflit qui redémarre parce que personne n'a cédé quoi que ce soit.",
    love: 'Peut indiquer des disputes où le but est de gagner. Invite à regarder ce que tu veux vraiment de la conversation.',
    work: 'Surveille la compétition qui abîme l’ambiance. Cela vaut la peine de choisir ce qui mérite une discussion.',
    growth: "Demande-toi quand avoir raison t'a fait te sentir mieux pour la dernière fois.",
    yesNo: 'no',
    astrology: 'Vénus en Verseau.'
  },
  E06: {
    keywords: ['Traversée', 'Transition', 'Eaux calmes'],
    energy: 'Laisser la difficulté derrière, en en portant encore une part.',
    advice: 'Avance sans faire comme si rien ne s’était passé.',
    light: ['Transition vers le mieux', 'Aide acceptée', 'Distance gagnée'],
    shadow: ['Fuir sans résoudre', 'Emporter tout le passé', 'Bouger sans direction'],
    upright: "Le Six d'Épées parle du passage d'un état à un autre. Dans un tirage, il marque souvent un éloignement de quelque chose de dur, graduel plutôt que soudain.",
    reversed: "À l'envers, il peut montrer un départ impossible, ou un changement de lieu qui ne change rien d'autre.",
    love: 'Peut indiquer un lien qui sort d’une mauvaise passe. Invite à nommer ce que tu emportes.',
    work: 'Favorise un changement de rôle ou d’environnement. Bon moment pour bien clore avant de commencer.',
    growth: 'Regarde ce que tu laisserais derrière si tu pouvais choisir.',
    yesNo: 'likely_yes',
    astrology: 'Mercure en Verseau.'
  },
  E07: {
    keywords: ['Stratégie', 'Dissimulation', 'Ruse'],
    energy: "Obtenir quelque chose sans le dire à voix haute.",
    advice: "Vérifie si la discrétion est stratégie ou esquive.",
    light: ['Stratégie utile', 'Discrétion opportune', 'Choisir ses batailles'],
    shadow: ['Agir dans le dos', 'Se mentir', 'Éviter la voie directe'],
    upright: "Le Sept d'Épées parle de la voie indirecte. En lecture, il indique souvent une situation traitée par manœuvre plutôt que par confrontation, pour le meilleur ou pour le pire.",
    reversed: "À l'envers, il peut marquer quelque chose qui vient au jour, ou la décision d'être franc après une période d'évitement.",
    love: 'Peut indiquer quelque chose que l’on retient. Invite à regarder ce que le silence protège.',
    work: 'Surveille l’information qui n’est pas partagée. Cela vaut la peine de demander directement plutôt que de déduire.',
    growth: 'Demande-toi ce que tu te dis et que tu ne dirais pas à voix haute.',
    yesNo: 'likely_no',
    astrology: 'Lune en Verseau.'
  },
  E08: {
    keywords: ['Restriction', 'Blocage', 'Croyance'],
    energy: "Se sentir pris par quelque chose qui est en partie une pensée.",
    advice: "Fais la liste de ce qui t'arrête vraiment ; une partie n'y survivra pas.",
    light: ['Voir la limite réelle', 'Distinguer la peur du fait', 'Premier pas vers la sortie'],
    shadow: ["Croire qu'il n'y a pas d'issue", 'Attendre d’être secouru', 'Confondre difficile et impossible'],
    upright: "Le Huit d'Épées parle d'un enfermement fait autant de croyance que de circonstance. En lecture, il indique souvent un blocage où la restriction est réelle mais plus petite qu'elle n'en a l'air.",
    reversed: "À l'envers, il marque souvent le moment où la sortie devient visible, ou une évasion tentée avant d'avoir compris la situation.",
    love: 'Peut indiquer un lien qui semble inéluctable. Invite à séparer ce qui te lie de ce que tu crains.',
    work: 'Surveille une situation décrite comme sans alternative. Cela vaut la peine de mettre cela à l’épreuve.',
    growth: "Regarde laquelle de tes limites tu n'as jamais essayé de franchir.",
    yesNo: 'no',
    astrology: 'Jupiter en Gémeaux.'
  },
  E09: {
    keywords: ['Angoisse', 'Nuit', 'Anticipation'],
    energy: "L'esprit répétant ce qui n'est pas arrivé.",
    advice: 'Écris la peur ; sur le papier elle est d’ordinaire plus petite.',
    light: ['Nommer la peur', "Demander de l'aide", 'Distinguer pensée et fait'],
    shadow: ['Insomnie mentale', 'Anticiper le désastre', 'Souffrir par avance'],
    upright: "Le Neuf d'Épées parle de l'inquiétude qui grandit la nuit. Dans un tirage, il indique souvent une angoisse devenue plus grande que la situation qui la cause.",
    reversed: "À l'envers, il peut marquer le soulagement qui arrive, ou le moment où la peur est enfin dite à quelqu'un.",
    love: 'Peut indiquer une inquiétude qui n’a pas été partagée. Invite à la dire plutôt qu’à la gérer seul.',
    work: 'Surveille la pression portée en privé. Cela vaut la peine de comparer l’échéance à la panique.',
    growth: "Demande-toi combien des peurs de l'an dernier se sont réalisées.",
    yesNo: 'no',
    astrology: 'Mars en Gémeaux.'
  },
  E10: {
    keywords: ['Fin', 'Fond', 'Libération'],
    energy: "Le pire est arrivé et il n'y a plus rien à en craindre.",
    advice: "C'est terminé ; cesse de repasser comment cela s'est passé.",
    light: ['Fin définitive', 'Soulagement après la chute', 'Liberté de recommencer'],
    shadow: ['Dramatiser la fin', 'Rester dans le rôle de victime', 'Croire que rien ne peut suivre'],
    upright: "Le Dix d'Épées parle de la fin d'un cycle qui ne pouvait pas continuer. Dans un tirage, il marque souvent une clôture dure, et le calme paradoxal qui vient une fois qu'elle a eu lieu.",
    reversed: "À l'envers, il marque souvent le début de la reprise, ou une fin refusée bien après son arrivée.",
    love: 'Peut indiquer quelque chose de terminé. Invite à l’accepter plutôt qu’à négocier avec.',
    work: 'Surveille un projet ou un rôle épuisé. Cela vaut la peine de le clore proprement.',
    growth: 'Regarde ce que tu peux bâtir maintenant que cela ne tient plus debout.',
    yesNo: 'no',
    astrology: 'Soleil en Gémeaux.'
  },
  E11: {
    keywords: ['Vigilance', 'Curiosité', 'Attention'],
    energy: "Quelqu'un qui remarque ce que les autres sautent.",
    advice: "Pose la question ; tu n'as pas à en connaître déjà la réponse.",
    light: ['Observation aiguisée', 'Curiosité honnête', 'Apprentissage rapide'],
    shadow: ['Soupçonner de tout', "Parler plus qu'écouter", 'Analyser pour ne pas sentir'],
    upright: "Le Valet d'Épées parle de l'esprit à son point le plus éveillé. En lecture, il marque souvent des nouvelles, une question qui mérite d'être posée, ou le début d'un apprentissage exigeant.",
    reversed: "À l'envers, il peut montrer une attention dispersée, ou une acuité utilisée pour critiquer plutôt que pour comprendre.",
    love: 'Peut indiquer un lien qui commence dans la conversation. Invite à écouter autant que tu observes.',
    work: 'Favorise enquêter, vérifier et poser des questions inconfortables. Bon moment pour contrôler les hypothèses.',
    growth: 'Demande-toi ce que tu as tranché sans preuve.',
    yesNo: 'depends',
    astrology: "La terre dans l'air."
  },
  E12: {
    keywords: ['Charge', 'Urgence', 'Franchise'],
    energy: 'Y aller tout droit, vite, sans regarder de côté.',
    advice: 'Ralentis d’un demi-pas ; la direction est bonne, le rythme peut-être pas.',
    light: ['Action décidée', 'Franchise', 'Courage de confronter'],
    shadow: ['Agir sans écouter', 'Agressivité', 'Décider sur une information incomplète'],
    upright: "Le Cavalier d'Épées parle de l'esprit lancé. Dans un tirage, il marque souvent une décision rapide, une confrontation directe, ou l'envie de régler cela maintenant.",
    reversed: "À l'envers, il peut montrer une hâte qui abîme, ou une charge qui perd son élan à mi-chemin.",
    love: 'Peut indiquer une conversation menée trop rudement. Invite à être honnête sans être tranchant.',
    work: 'Favorise débloquer ce qui traîne. Cela vaut la peine de vérifier les faits avant de se lancer.',
    growth: 'Regarde ce que tu dirais si tu respirais d’abord.',
    yesNo: 'likely_yes',
    astrology: "Le feu dans l'air."
  },
  E13: {
    keywords: ['Lucidité', 'Indépendance', 'Honnêteté'],
    energy: "Voir clair, y compris ce qui est inconfortable.",
    advice: 'Dis la vérité simplement ; trop l’adoucir l’efface.',
    light: ['Jugement clair', 'Indépendance honnête', 'Expérience devenue clarté'],
    shadow: ['Froideur', 'Vérité qui coupe', "S'isoler par autosuffisance"],
    upright: "La Reine d'Épées parle d'une clarté gagnée par l'expérience. En lecture, elle indique souvent quelqu'un qui voit les choses telles qu'elles sont, ou un moment pour l'honnêteté avant le confort.",
    reversed: "À l'envers, elle peut montrer une clarté durcie en distance, ou une vérité utilisée pour tenir les gens à l'écart.",
    love: 'Peut indiquer un lien qui a besoin de mots clairs. Invite à être net et chaleureux à la fois.',
    work: 'Favorise évaluer honnêtement et poser des critères. Bon moment pour l’appréciation directe.',
    growth: 'Demande-toi ce que tu protèges en restant autosuffisant.',
    yesNo: 'depends',
    astrology: "L'eau dans l'air."
  },
  E14: {
    keywords: ['Jugement', 'Principe', 'Autorité'],
    energy: "Décider par critère et non par humeur.",
    advice: "Énonce le critère avant de l'appliquer.",
    light: ['Bon jugement', 'Clarté éthique', 'Autorité méritée'],
    shadow: ['Rigidité', 'Juger sans contexte', 'Raison sans chaleur'],
    upright: "Le Roi d'Épées parle d'un air mûr : une pensée qui a appris la responsabilité. Dans un tirage, il marque souvent la capacité de trancher avec justice une affaire difficile.",
    reversed: "À l'envers, il peut montrer une autorité utilisée pour clore la conversation, ou une logique détachée de ses conséquences.",
    love: 'Peut indiquer un lien qui a besoin de termes clairs. Invite à laisser de la place à ce qui ne s’argumente pas.',
    work: 'Favorise les décisions, les critères et les appels difficiles. Bon moment pour écrire la règle.',
    growth: 'Regarde où tu te sers de la raison pour ne pas sentir.',
    yesNo: 'depends',
    astrology: "L'air dans l'air."
  },
  O01: {
    keywords: ['Occasion', 'Graine', 'Terrain'],
    energy: "On offre quelque chose de concret et on peut bâtir dessus.",
    advice: 'Prends-la et donne-lui une forme ; le potentiel seul ne pousse pas.',
    light: ['Occasion réelle', 'Base solide', 'Début tangible'],
    shadow: ['La laisser passer', 'Vouloir la certitude d’abord', "Confondre l'offre et le résultat"],
    upright: "L'As de Deniers parle d'un début avec de la terre ferme dessous. En lecture, il marque souvent une occasion concrète : travail, argent, un lieu, une ressource.",
    reversed: "À l'envers, il peut montrer une chance non saisie, ou un plan sans aucune fondation.",
    love: 'Peut indiquer un lien qui commence sur un terrain solide. Invite à préférer le quotidien au spectaculaire.',
    work: 'Favorise un nouveau rôle, un contrat ou un investissement. Bon moment pour accepter puis organiser.',
    growth: "Demande-toi ce que tu as sous la main et n'as pas utilisé.",
    yesNo: 'yes',
    astrology: 'La terre dans sa forme la plus pure.'
  },
  O02: {
    keywords: ['Jonglage', 'Adaptation', 'Priorités'],
    energy: 'Tenir plusieurs choses en l’air et y arriver tout juste.',
    advice: 'Décide ce qui peut tomber ; quelque chose doit tomber.',
    light: ['Souplesse', 'Mener plusieurs fronts', 'Bien s’adapter'],
    shadow: ['En prendre trop', 'Improviser toujours', 'Repousser le choix'],
    upright: "Le Deux de Deniers parle d'un équilibre tenu en mouvement. Dans un tirage, il indique souvent une période de jonglage avec les engagements : tenable, mais pas indéfiniment.",
    reversed: "À l'envers, il peut montrer l'équilibre qui cède, ou le jonglage utilisé pour ne pas décider.",
    love: 'Peut indiquer un lien coincé entre d’autres exigences. Invite à lui donner du vrai temps, pas le temps qui reste.',
    work: 'Surveille les tâches trop parallèles. Cela vaut la peine de classer par importance et non par urgence.',
    growth: 'Regarde ce que tu tiens en l’air seulement parce que le lâcher ressemblerait à un échec.',
    yesNo: 'depends',
    astrology: 'Jupiter en Capricorne.'
  },
  O03: {
    keywords: ['Métier', 'Collaboration', 'Savoir-faire'],
    energy: "Bien faire quelque chose, avec d'autres, et que cela se reconnaisse.",
    advice: 'Dis ce dont tu as besoin des autres ; personne ne devine bien.',
    light: ['Compétence reconnue', 'Travail d’équipe efficace', 'Apprendre en faisant'],
    shadow: ['Travailler seul par orgueil', 'Perfectionnisme qui bloque', 'Ne pas réclamer ce qui t’est dû'],
    upright: "Le Trois de Deniers parle d'un travail qui tient parce que plusieurs personnes connaissent leur part. En lecture, il marque souvent un projet qui avance bien et un savoir-faire reconnu.",
    reversed: "À l'envers, il peut montrer des rôles flous, ou un effort qui n'est pas reconnu.",
    love: 'Peut indiquer un lien qui se construit plutôt qu’il ne se trouve. Invite à regarder ce que chacun y apporte.',
    work: 'Favorise la collaboration, l’apprentissage et le travail technique. Bon moment pour demander un retour.',
    growth: 'Demande-toi ce que tu fais bien et dis rarement à voix haute.',
    yesNo: 'yes',
    astrology: 'Mars en Capricorne.'
  },
  O04: {
    keywords: ['Retenir', 'Sécurité', 'Contrôle'],
    energy: 'Serrer fort ce que l’on craint de perdre.',
    advice: 'Ouvre un peu la main ; rien ne circule dans un poing fermé.',
    light: ['Prudence', 'Épargne avec un but', 'Protéger ce qui compte'],
    shadow: ['Accumuler par peur', 'Rigidité', 'Confondre sécurité et contrôle'],
    upright: "Le Quatre de Deniers parle de retenir. Dans un tirage, il indique souvent une prudence avec les ressources, le temps ou l'affection, utile jusqu'au point où elle arrête le mouvement.",
    reversed: "À l'envers, il peut marquer la décision de laisser circuler quelque chose, ou une prise si serrée qu'elle coûte plus qu'elle n'épargne.",
    love: 'Peut indiquer un lien retenu plus que vécu. Invite à donner sans tenir les comptes.',
    work: 'Surveille la prudence excessive. Cela vaut la peine de distinguer prudence et paralysie.',
    growth: 'Regarde ce que tu retiens par peur et non par valeur.',
    yesNo: 'likely_no',
    astrology: 'Soleil en Capricorne.'
  },
  O05: {
    keywords: ['Manque', 'Exclusion', 'Aide proche'],
    energy: "Traverser une période dure sans demander d'aide.",
    advice: "Frappe à la porte ; elle est plus proche qu'elle n'en a l'air.",
    light: ['Reconnaître le besoin', 'Demander du soutien', 'Solidarité trouvée'],
    shadow: ['Endurer seul', 'Honte de la situation', "Ne pas voir l'aide disponible"],
    upright: "Le Cinq de Deniers parle d'une difficulté matérielle ou émotionnelle traversée dans l'isolement. En lecture, il indique souvent une passe dure où le soutien existe mais n'a pas été demandé.",
    reversed: "À l'envers, il marque souvent le début de la reprise, ou une aide enfin acceptée.",
    love: 'Peut indiquer le fait de se sentir seul à l’intérieur d’un lien. Invite à le dire clairement.',
    work: 'Surveille l’insécurité autour des ressources. Cela vaut la peine de demander plutôt que de supposer la réponse.',
    growth: 'Demande-toi qui tu appellerais si tu t’en donnais la permission.',
    yesNo: 'no',
    astrology: 'Mercure en Taureau.'
  },
  O06: {
    keywords: ['Donner', 'Recevoir', 'Échange juste'],
    energy: "Quelque chose passe d'une main à l'autre et les deux comptent.",
    advice: 'Regarde qui tient la balance dans cet échange.',
    light: ['Générosité', 'Aide réelle', 'Échange équilibré'],
    shadow: ['Donner pour garder le pouvoir', 'Recevoir avec une dette attachée', 'Charité qui humilie'],
    upright: "Le Six de Deniers parle de l'échange et de l'équilibre qu'il contient. Dans un tirage, il marque souvent le fait de donner ou de recevoir du soutien, et la question de ce que chacun en retire.",
    reversed: "À l'envers, il peut montrer une aide assortie de conditions, ou une dépendance déguisée en générosité.",
    love: 'Peut indiquer un déséquilibre dans ce que chacun apporte. Invite à regarder les comptes honnêtement.',
    work: 'Favorise les accords, les salaires et les négociations. Bon moment pour dire ce que vaut ton travail.',
    growth: 'Regarde si donner ou recevoir t’est le plus difficile.',
    yesNo: 'likely_yes',
    astrology: 'Lune en Taureau.'
  },
  O07: {
    keywords: ['Patience', 'Évaluation', 'Croissance lente'],
    energy: "Regarder ce qui a été planté et se demander si cela en vaut la peine.",
    advice: 'Décide s’il faut continuer d’arroser ou planter ailleurs.',
    light: ['Évaluation honnête', 'Patience avec le processus', 'Investissement qui mûrit'],
    shadow: ['Impatience avec ce qui prend du temps', 'Persister à cause de ce qui est déjà investi', 'Abandonner juste avant que cela marche'],
    upright: "Le Sept de Deniers parle de la pause pour évaluer un long effort. En lecture, il indique souvent un projet à mi-chemin, où la bonne question est si le retour justifie le temps.",
    reversed: "À l'envers, il peut montrer un effort versé dans quelque chose qui ne donnera rien, ou un abandon trop précoce.",
    love: 'Peut indiquer un lien qui a besoin d’un bilan plus que d’efforts supplémentaires. Invite à être honnête sur les progrès.',
    work: 'Bon moment pour mesurer les résultats et décider ce qui continue. Cela vaut la peine de poser un vrai critère.',
    growth: 'Demande-toi dans quoi tu continues d’investir par habitude.',
    yesNo: 'depends',
    astrology: 'Saturne en Taureau.'
  },
  O08: {
    keywords: ['Pratique', 'Métier', 'Répétition'],
    energy: 'Refaire la même chose, un peu mieux à chaque fois.',
    advice: "Continue ; c'est l'étape qui doit paraître ordinaire.",
    light: ['Dévouement', 'Savoir-faire qui progresse', 'Routine qui porte'],
    shadow: ['Répéter sans apprendre', 'Perfectionnisme', 'Travailler pour ne pas penser'],
    upright: "Le Huit de Deniers parle de l'acquisition patiente d'un métier. En lecture, il marque souvent une période de travail régulier où le progrès est réel mais pas encore visible.",
    reversed: "À l'envers, il peut montrer une répétition mécanique, ou un travail fait sans soin.",
    love: 'Peut indiquer un lien qui a besoin d’attention quotidienne. Invite à continuer d’être là dans les petites choses.',
    work: 'Favorise la formation, la pratique et le travail de détail. Bon moment pour améliorer le métier lui-même.',
    growth: 'Regarde ce que tu maîtriserais en y consacrant un an.',
    yesNo: 'likely_yes',
    astrology: 'Soleil en Vierge.'
  },
  O09: {
    keywords: ['Autonomie', 'Plaisir', 'Accomplissement'],
    energy: 'Profiter de ce que tu as bâti toi-même.',
    advice: "Autorise-le-toi sans t'en excuser.",
    light: ['Indépendance gagnée', 'Plaisir raffiné', 'Autosuffisance'],
    shadow: ['S’isoler dans le confort', 'Une fierté qui tient les autres à l’écart', 'Réussir sans compagnie'],
    upright: "Le Neuf de Deniers parle du bien-être qui vient de son propre effort. Dans un tirage, il marque souvent l'autonomie, le confort, et la capacité de savourer ce qui a été accompli.",
    reversed: "À l'envers, il peut montrer une indépendance devenue isolement, ou un confort qui coûte plus qu'il n'apporte.",
    love: 'Peut indiquer quelqu’un qui va bien seul et choisit la compagnie plutôt que d’en avoir besoin. Invite à partager sans céder ton terrain.',
    work: 'Favorise travailler de façon indépendante et savourer les résultats. Bon moment pour relever ton exigence.',
    growth: "Demande-toi ce que tu as bâti et ne t'es jamais arrêté pour regarder.",
    yesNo: 'yes',
    astrology: 'Vénus en Vierge.'
  },
  O10: {
    keywords: ['Héritage', 'Stabilité', 'Transmission'],
    energy: "Quelque chose de bâti qui dure plus longtemps que celui qui l'a bâti.",
    advice: 'Regarde ce que tu laisses, pas seulement ce que tu gagnes.',
    light: ['Sécurité durable', 'Famille et continuité', 'Richesse qui se partage'],
    shadow: ['Richesse sans sens', 'Poids hérité', 'Maintenir une structure que personne ne voulait'],
    upright: "Le Dix de Deniers parle de stabilité matérielle et familiale. Dans un tirage, il marque souvent une consolidation : quelque chose d'assez solide pour être transmis.",
    reversed: "À l'envers, il peut montrer des fardeaux hérités, ou une stabilité préservée au prix de tous ceux qui y vivent.",
    love: 'Peut indiquer un lien avec des projets à long terme. Invite à regarder si vous voulez la même structure.',
    work: 'Favorise les projets longs, le patrimoine et les décisions durables. Bon moment pour penser en années.',
    growth: 'Regarde ce que tu as hérité et n’as pas choisi.',
    yesNo: 'yes',
    astrology: 'Mercure en Vierge.'
  },
  O11: {
    keywords: ['Étude', 'Commencement', 'Application'],
    energy: "Quelqu'un qui commence à apprendre quelque chose pour de bon.",
    advice: 'Commence petit et concret ; le plan pourra grandir ensuite.',
    light: ["Envie d'apprendre", 'Début pratique', 'Constance tranquille'],
    shadow: ['Étudier sans appliquer', 'Repousser le début', 'Vouloir des résultats trop tôt'],
    upright: "Le Valet de Deniers parle d'un début enraciné dans l'effort. En lecture, il marque souvent des études, un nouveau travail, ou une occasion qui demande d'abord d'apprendre.",
    reversed: "À l'envers, il peut montrer un projet qui ne dépasse jamais la planification, ou une attention qui s'égare.",
    love: 'Peut indiquer un lien qui commence lentement et avec soin. Invite à le laisser se construire.',
    work: 'Favorise la formation, les stages et les premiers pas. Bon moment pour bien apprendre les bases.',
    growth: "Demande-toi ce que tu apprendrais si tu t'autorisais à être débutant.",
    yesNo: 'likely_yes',
    astrology: 'La terre dans la terre.'
  },
  O12: {
    keywords: ['Constance', 'Méthode', 'Fiabilité'],
    energy: 'Lent, régulier, et cela arrive.',
    advice: "Fie-toi à la routine ; c'est le rythme qui termine les choses.",
    light: ['Fiabilité', 'Effort soutenu', 'Travail bien fait'],
    shadow: ['Rigidité', 'Résistance au changement', 'Routine sans direction'],
    upright: "Le Cavalier de Deniers parle d'une avancée peu spectaculaire qui ne s'arrête pas. Dans un tirage, il marque souvent un travail patient et méthodique qui y arrivera.",
    reversed: "À l'envers, il peut montrer une stagnation déguisée en constance, ou une méthode appliquée sans but.",
    love: 'Peut indiquer un lien bâti sur la fiabilité. Invite à valoriser l’ordinaire.',
    work: 'Favorise les processus longs et tout ce qui demande de la discipline. Bon moment pour la tâche peu glorieuse.',
    growth: 'Regarde ce que tu accomplirais avec le même effort tenu plus longtemps.',
    yesNo: 'likely_yes',
    astrology: 'Le feu dans la terre.'
  },
  O13: {
    keywords: ['Soin', 'Abondance', 'Enracinement'],
    energy: "Quelqu'un qui prend soin de ce qui lui est confié, y compris de soi.",
    advice: "Prends soin du pratique ; c'est ce qui tient tout le reste.",
    light: ['Générosité pratique', 'Présence nourrissante', 'Lien avec le corps'],
    shadow: ['Prendre soin de tous sauf de soi', 'Surprotéger', "Mesurer sa valeur à son utilité"],
    upright: "La Reine de Deniers parle d'un soin devenu concret. En lecture, elle indique souvent quelqu'un qui pourvoit et soutient, ou un moment pour s'occuper du côté matériel de la vie.",
    reversed: "À l'envers, elle peut montrer un soin qui épuise, ou de l'attention pour tous sauf pour soi.",
    love: 'Peut indiquer un lien où le soin se voit dans les actes. Invite à recevoir aussi.',
    work: 'Favorise gérer, accueillir et tout ce qui fait tenir une structure. Bon moment pour soigner les bases.',
    growth: 'Demande-toi quand tu as fait quelque chose pour ton corps la dernière fois.',
    yesNo: 'yes',
    astrology: "L'eau dans la terre."
  },
  O14: {
    keywords: ['Prospérité', 'Maîtrise', 'Subsistance'],
    energy: "Quelqu'un qui a bâti quelque chose de solide et sait le garder.",
    advice: 'Administre ce que tu as avant d’en chercher davantage.',
    light: ['Maîtrise matérielle', 'Subsistance fiable', "Générosité venue de l'abondance"],
    shadow: ['Mesurer sa valeur à sa richesse', 'Rigidité dans ce qui a marché', 'Contrôle déguisé en subsistance'],
    upright: "Le Roi de Deniers parle d'une terre mûre : un effort devenu structure. Dans un tirage, il marque souvent la capacité de tenir quelque chose dans la durée et d'en faire vivre d'autres.",
    reversed: "À l'envers, il peut montrer un attachement à la sécurité, ou une structure défendue au-delà de son utilité.",
    love: 'Peut indiquer un lien qui offre une vraie stabilité. Invite à garder la chaleur à côté de la fiabilité.',
    work: 'Favorise gérer, investir et assumer une responsabilité économique. Bon moment pour la vue longue.',
    growth: "Regarde ce que assez voudrait dire pour toi.",
    yesNo: 'yes',
    astrology: "L'air dans la terre."
  },
};
