export const CARD_IMAGES = {
    'am00.png': 'https://i.ibb.co/PsNfZbGj/am00.png', 'am01.png': 'https://i.ibb.co/Q3by9R5f/am01.png',
    'am02.png': 'https://i.ibb.co/QvWP9f9C/am02.png', 'am03.png': 'https://i.ibb.co/zWy84MGh/am03.png',
    'am04.png': 'https://i.ibb.co/Z6YLDnRp/am04.png', 'am05.png': 'https://i.ibb.co/TMmfkvjC/am05.png',
    'am06.png': 'https://i.ibb.co/wZRXDK55/am06.png', 'am07.png': 'https://i.ibb.co/39MJFSYp/am07.png',
    'am08.png': 'https://i.ibb.co/1fsh4qVR/am08.png', 'am09.png': 'https://i.ibb.co/1YJw8dv5/am09.png',
    'am10.png': 'https://i.ibb.co/Pz0YnKjm/am10.png', 'am11.png': 'https://i.ibb.co/8Dxxg6sZ/am11.png',
    'am12.png': 'https://i.ibb.co/DgVzNgGx/am12.png', 'am13.png': 'https://i.ibb.co/yBNh7Kv1/am13.png',
    'am14.png': 'https://i.ibb.co/ynFWrBtP/am14.png', 'am15.png': 'https://i.ibb.co/jZfdnKFW/am15.png',
    'am16.png': 'https://i.ibb.co/gFchtzGq/am16.png', 'am17.png': 'https://i.ibb.co/hxVv0fqx/am17.png',
    'am18.png': 'https://i.ibb.co/wZRXDK55/am18.png', 'am19.png': 'https://i.ibb.co/v6YBFsK2/am19.png',
    'am20.png': 'https://i.ibb.co/21P8Pdpq/am20.png', 'am21.png': 'https://i.ibb.co/JWvZHmNN/am21.png',
    'ameb01.png': 'https://i.ibb.co/xqcvgMKV/ameb01.png', 'ameb02.png': 'https://i.ibb.co/3yhbq0Cr/ameb02.png',
    'ameb03.png': 'https://i.ibb.co/Fkd7RH6k/ameb03.png', 'ameb04.png': 'https://i.ibb.co/GfYTrXrs/ameb04.png',
    'ameb05.png': 'https://i.ibb.co/R4kYp9J5/ameb05.png', 'ameb06.png': 'https://i.ibb.co/ZpBJBkRj/ameb06.png',
    'ameb07.png': 'https://i.ibb.co/4nB2sbvd/ameb07.png', 'ameb08.png': 'https://i.ibb.co/67SNTsXL/ameb08.png',
    'ameb09.png': 'https://i.ibb.co/KcSPJVs2/ameb09.png', 'ameb10.png': 'https://i.ibb.co/pvgSTk2r/ameb10.png',
    'ameb11.png': 'https://i.ibb.co/MynLfqfn/ameb11.png', 'ameb12.png': 'https://i.ibb.co/bjvGKMjh/ameb12.png',
    'ameb13.png': 'https://i.ibb.co/SDTy5xYP/ameb13.png', 'ameb14.png': 'https://i.ibb.co/HTFBtpZ4/ameb14.png',
    'amec01.png': 'https://i.ibb.co/XxWyr0FN/amec01.png', 'amec02.png': 'https://i.ibb.co/rGDP0GtM/amec02.png',
    'amec03.png': 'https://i.ibb.co/gMR86sGR/amec03.png', 'amec04.png': 'https://i.ibb.co/HpncLtSf/amec04.png',
    'amec05.png': 'https://i.ibb.co/bqtGmJH/amec05.png', 'amec06.png': 'https://i.ibb.co/4ZDvnDRV/amec06.png',
    'amec07.png': 'https://i.ibb.co/XRpRcFh/amec07.png', 'amec08.png': 'https://i.ibb.co/cSfDyBMM/amec08.png',
    'amec09.png': 'https://i.ibb.co/9m5pZxGR/amec09.png', 'amec10.png': 'https://i.ibb.co/dd7PNCH/amec10.png',
    'amec11.png': 'https://i.ibb.co/2YvqpR8c/amec11.png', 'amec12.png': 'https://i.ibb.co/0pc6cbvb/amec12.png',
    'amec13.png': 'https://i.ibb.co/Z1Jqz85D/amec13.png', 'amec14.png': 'https://i.ibb.co/8Lj11Pxd/amec14.png',
    'amee01.png': 'https://i.ibb.co/TM0p8Xkb/amee01.png', 'amee02.png': 'https://i.ibb.co/jk4D7cPn/amee02.png',
    'amee03.png': 'https://i.ibb.co/m564jzNv/amee03.png', 'amee04.png': 'https://i.ibb.co/n8c8vBQP/amee04.png',
    'amee05.png': 'https://i.ibb.co/svLLLXX2/amee05.png', 'amee06.png': 'https://i.ibb.co/jPvnYbfd/amee06.png',
    'amee07.png': 'https://i.ibb.co/GNvz5Rn/amee07.png', 'amee08.png': 'https://i.ibb.co/cSdBW2Xx/amee08.png',
    'amee09.png': 'https://i.ibb.co/xpyXK09/amee09.png', 'amee10.png': 'https://i.ibb.co/27pHXHCV/amee10.png',
    'amee11.png': 'https://i.ibb.co/Y7GWfzFg/amee11.png', 'amee12.png': 'https://i.ibb.co/m5B0H5dh/amee12.png',
    'amee13.png': 'https://i.ibb.co/whRNh0G1/amee13.png', 'amee14.png': 'https://i.ibb.co/JgpbxjM/amee14.png',
    'ameo01.png': 'https://i.ibb.co/h1L6LYn5/ameo01.png', 'ameo02.png': 'https://i.ibb.co/S4jjQXxC/ameo02.png',
    'ameo03.png': 'https://i.ibb.co/5hQc9Nv2/ameo03.png', 'ameo04.png': 'https://i.ibb.co/ycc503hv/ameo04.png',
    'ameo05.png': 'https://i.ibb.co/nMhNkC6P/ameo05.png', 'ameo06.png': 'https://i.ibb.co/CKGc9YfQ/ameo06.png',
    'ameo07.png': 'https://i.ibb.co/zTpgPSqd/ameo07.png', 'ameo08.png': 'https://i.ibb.co/5WsVV8Nr/ameo08.png',
    'ameo09.png': 'https://i.ibb.co/MySP0Qt0/ameo09.png', 'ameo10.png': 'https://i.ibb.co/Mx6GVQZZ/ameo10.png',
    'ameo11.png': 'https://i.ibb.co/35nKK0QQ/ameo11.png', 'ameo12.png': 'https://i.ibb.co/HfWhCHkB/ameo12.png',
    'ameo13.png': 'https://i.ibb.co/9kQX5yf2/ameo13.png', 'ameo14.png': 'https://i.ibb.co/zTvvphs9/ameo14.png'
};

export function getCardImageUrl(fileName) { return CARD_IMAGES[fileName] || ''; }
export function imgObj(fileName) { return getCardImageUrl(fileName); }
export function getImgSrc(card) { return typeof card.img === 'string' ? card.img : ''; }
